### ISSUE TITLE
 multiple problems with generic file icon replacement of large images

### ISSUE THREAD

**Issue by mossmann** [signalapp/Signal-iOS#3866] opened 2018-09-07 00:46 UTC
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Greetings, friends! Thank you for your efforts to make the world a safer place with Signal!

I have several concerns (in addition to the more severe #3865 and #3860) about the "generic file icon" introduced in Version 2.29.1 for images "with excessively large dimensions".

- I've observed images as small as 1.6 MB being replaced with the generic file icon. I do not consider this to be excessively large. Images imported from any modern phone camera app are likely to exceed the size limit and have exceeded it in every case I'm aware of so far.

- There is no user setting to disable this feature or to tune it for a specific image size.

- Large images no longer appear in the All Media list.

- Senders are given no indication that an image is "exessively large" and may not be visible to the recipient.

- Senders are not given an opportunity to resize images so that they do not exceed the limit.

- There is no indication of the actual size limit nor of the dimensions of any image.

Because images of typical camera app size were routinely displayed previously, I think these should be considered bugs.

I urge you to eliminate this new feature as soon as possible or to at least greatly increase the size limit while considering these issues.

Thank you!

**Comment by michaelkirk-signal** [comment] 2018-09-07 15:32
> I've observed images as small as 1.6 MB being replaced with the generic file icon.

This is a dupe of #3860 - in this case we're talking about size in terms of pixel resolution, not file size.

This is fixed in the current beta. If you'd like to help test before we get to production, send a message to support@signal.org with the subject "sign me up for the iOS beta"

**Closed by michaelkirk-signal** 2018-09-07 15:32 UTC

**Comment by mossmann** [comment] 2018-09-07 21:53
I mentioned later in my report that one of the problems I identified was that there is no indication of pixel size anywhere in Signal. That's why I identified the image by file size; it was the only indication of size available to me in the app. The 1.6 MB file I mentioned was a photo from a typical phone camera app.

I believe I explained how my concerns differ from #3860, but perhaps it would help to clarify that by "senders" I meant people including non-iOS users who send images to iOS users. Those senders currently have an expectation, for example, that images they send will be listed in the recipient's All Media. I believe it is a bug that those images may or may not appear in All Media without any indication given to the sender.

**Comment by michaelkirk-signal** [comment] 2018-09-07 23:46
Hey @mossmann - thanks for your thoughtful report. I apologize that my initial response was so brief. We get a lot of feedback, and in my briefness I didn't address all the points in your issue. I'll try to do a better job now.

> I've observed images as small as 1.6 MB being replaced with the generic file icon. I do not consider this to be excessively large. Images imported from any modern phone camera app are likely to exceed the size limit and have exceeded it in every case I'm aware of so far.

You're right - it is a problem that the current version of Signal-iOS in the App Store cannot display many commonly sized images. We'd already addressed this and the fix is currently in beta (2.29.2). Every indication from our beta users has been positive. We are now only waiting for App Store review.

> There is no user setting to disable this feature or to tune it for a specific image size.

Now that we've addressed the regression and support displaying much larger images, we have no reason to believe this will be an issue in practice. It is unlikely that we, nor any app, will have a switch that allows you to send infinitely large images across the network.

> Large images no longer appear in the All Media list.

This was also a consequence of the same regression. Now that it's addressed, larger media will again appear in the "All Media" list.

> Senders are given no indication that an image is "exessively large" and may not be visible to the recipient.

> Senders are not given an opportunity to resize images so that they do not exceed the limit.

This was also a consequence of the same regression. The forthcoming release is aligned with resizing limits on other platforms, so in practice, this should no longer be an issue.

> There is no indication of the actual size limit

If you try to send an image whose file-size is too large, it will be downscaled. This is in line with other messengers, and we believe to be the most reasonable behavior for the vast majority of our users.

>  nor of the dimensions of any image.

I could parse this in two ways, I'm not sure which one you mean, so I'll address both

> There is no indication of [...] of the dimension [limit] of any image.

If you try to send an image whose resolution is too large, it will be downscaled. For the same reasons as above, we believe this is the correct behavior.

> There is no indication of ... of the dimension of image[s I'm sending/already sent/received].

We could show the resolution of sent and received images somewhere... for example maybe in the media details, or maybe in the outgoing media approval screen.  I'm not aware of other messaging apps that do this, but it's not a bad idea. There's some questions to be answered there (what other apps do this? How do they solve this problem? Or why don't they?). If you'd like to talk about that avenue more, could we move it to the [community forums](https://community.signalusers.org/)? It's a better avenue for discussion and design exploration, whereas we reserve Github for bug reports with existing functionality. 

Again, thanks for taking the time to give us thoughtful feedback. Feel free to respond here if I've misunderstood any of these items, and they actually are bugs in practice reflected in the current beta release. Or if instead you'd like to hash out the details on how we could add some new feature, let's talk more on the forums. I'm @michaelkirk  there if you want to tag me, but I read every post anyway.

**Comment by ethylmorphine** [comment] 2018-09-08 04:08
Telegram shows an actual size of an image during sending.
