### ISSUE TITLE
please show Signal in this list (screenshot attached)

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#2880] opened 2017-12-13 06:18 UTC
![img_7794](https://user-images.githubusercontent.com/2054302/33924285-0b18cd1c-dfde-11e7-84af-bba695f7f4c0.PNG)

**Comment by mateoeh** [comment] 2017-12-18 15:09
Duplicate of #650

**Comment by michaelkirk** [comment] 2018-02-06 16:09
closing as dupe of https://github.com/signalapp/Signal-iOS/issues/650

**Closed by michaelkirk** 2018-02-06 16:09 UTC
