### ISSUE TITLE
[Feature Request] Support "bubble" color scheme similar to Android app

### ISSUE THREAD

**Issue by yln** [signalapp/Signal-iOS#4148] opened 2019-03-06 07:02 UTC
I switched from Android to iPhone and noticed that the color scheme for the "bubbles" differs.
Incoming messages are gray, outgoing blue.

I think it is a good default to mirror Apple's iMessages to not confuse users. However, I would really appreciate an option that could give me the bubble colors similar to Signal on Android.

To me, the Android color scheme makes perfect sense: incoming messages have color, my own outgoing are gray. So what I am actually interested in gets highlighted. Every contact gets their own color, which prevents accidental confusion of message threads. Every contact having their own color is also very useful for group chats.

**Comment by Cerberus0** [comment] 2019-03-07 09:11
This submission is a duplicate of #1434.

@yln: I recommend reading the [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md) and using the bug report template that is provided when you submit new issues. Here is a link to the template if you're not able to see it in a third-party client or on mobile: https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE.md

**Comment by michaelkirk-signal** [comment] 2019-03-07 21:26
We no longer track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Closed by michaelkirk-signal** 2019-03-07 21:26 UTC
