### ISSUE TITLE
Sound is not clear and not loud Plus it hang on ios8

### ISSUE THREAD

**Issue by OmarNsy** [signalapp/Signal-iOS#1064] opened 2016-01-28 14:12 UTC
Good day everyone
First im sorry for my English is not that good, but I'll try :)
I like signal app, I'm always install the app after you updated but deleted after 3 days, I'm always doing this for same reasons.

The main reason is the voice is not clear enough and is not loud, I'm not the only one who said this, I shocked when i talked with my friends and the people at cafe more than 50 persons which they used variety phones (iPhone and android) who acknowledged that they delete the app for the same reasons.

We waited you to solve the voice clarity for more than a year and installing the app after every update but still the same voice problem so we deleted right away, but im certain that if you solve this, many people will coming on the door, because everyone compare the voice clarity and the loud with other apps like viber, hangouts, whatsapp, skype and many many others, everyone know that all these apps leaked privacy but there is no choice because the voice loud and the clarity on the other apps are hd clear.

In the other hand i face a problem on two iPhones 5s which runs ios 8, the problem is whenever i call these two iPhones and after I hang up the call i cant call them again, can't call them on signal, viber, whatsapp and even facetime , no one can reach them on these apps at all but after they remove signal everything went well, imagine what are those two old people say to me "don't ever ask us to install this app again".

I know I talked much but believe me if I don't like signal or I don't care about it i will never tired my self in typing which toke from me 1 hour to find the right terminology and check spelling to deliver what people want, so please help us to help you.

Best regards 
Privacy lover

**Comment by michaelkirk** [comment] 2016-03-05 18:12
Sound quality is dupe of https://github.com/WhisperSystems/Signal-iOS/issues/50

> In the other hand i face a problem on two iPhones 5s which runs ios 8, the problem is whenever i call these two iPhones and after I hang up the call i cant call them again, can't call them on signal, viber, whatsapp and even facetime , no one can reach them on these apps at all but after they remove signal everything went well, imagine what are those two old people say to me "don't ever ask us to install this app again".

This sounds like a separate issue. Is this what you're saying?

 - Initially Phone A can call Phone B successfully on viber, whatsapp, AND facetime
 - Phone A calls Phone B successfully on signal once
 - Now Phone A can no longer call Phone B via signal, viber, whatsapp, OR facetime
 - Phone A uninstalls Signal
 - Now Phone A can once again call Phone B via viber, whatstapp, AND facetime

If so, can you reproduce it?

**Comment by michaelkirk-signal** [comment] 2019-08-22 02:43
I'm going to close this issue as we never got any feedback.

**Closed by michaelkirk-signal** 2019-08-22 02:43 UTC
