### ISSUE TITLE
Share extension crashes when trying to share a link

### ISSUE THREAD

**Issue by denver-s** [signalapp/Signal-iOS#4896] opened 2021-02-25 15:06 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The share extension crashes when user tries to share a link.

### Steps to reproduce
- open Twitter and click on a link
- open the link on the native Safari link viewer of Twitter
- click share
- select Signal
- select a chat
- click "next" button

**Actual result:** Signal tries to generate a preview but it crashes/closes.

**Expected result:** Should not close the share extension.

### Device info

**Device**: iPhone 8 Plus

**iOS version**: 14.4

**Signal version:** 5.6.0.8

### Link to debug log
https://debuglogs.org/c64e5de2d20d15df3adafc8dbfcd9796c2727c9081302d82b2fc8444a78a37ed.zip

**Comment by tomxpcvx** [comment] 2021-03-01 23:11
Hi, it's maybe duplicate of #4855.

**Comment by tomxpcvx** [comment] 2022-01-24 10:40
Ticket should remain open, issue still exists.

**Comment by tomxpcvx** [comment] 2022-03-25 12:57
Ticket should remain open as the error still exists. Or it will be closed because of the duplicate with https://github.com/signalapp/Signal-iOS/issues/4855 .

**Closed** 2022-05-25 09:10 UTC
Labels: wontfix
