### ISSUE TITLE
Live Photos support

### ISSUE THREAD

**Issue by nanotechz9l** [signalapp/Signal-iOS#1016] opened 2015-12-20 05:17 UTC
Currently unable to view live photos/gifs.

**Comment by 2-4601** [comment] 2015-12-20 08:35
Duplicate of #525.
And best of all there's already a commit for that.

**Comment by FredericJacobs** [comment] 2015-12-20 10:41
GIFs will make it into the next build. I'll leave this issue open for Live Photos

**Comment by arekm** [comment] 2018-03-13 10:00
Viewing is not that big problem.

The main problem is that signal doesn't send full live photo and only associated jpg, so even after saving received image we cannot use iOS builtin browser to see live photo.

**Comment by danrivett** [comment] 2018-09-28 15:14
Any update on this? Is it just user error on my part? I'm trying to send a Live Photo as a gif but just sends it as a still image when I want to send it as an animated gif.

**Comment by hoechenberger** [comment] 2020-09-01 07:33
Hello, I just wanted to ask if this is still on the planned-features list? It's something that me and some friends of mine would really love to see being implemented in Signal :) In WhatsApp, you can just long-tap on a Live Photo to choose sending it as a GIF.

**Comment by iotmani** [comment] 2021-06-06 18:02
Hello,

One work-around I just realised is to add the "Loop" or "Bounce" effect to a live photo from Photos app. 
iOS will then share it natively as a gif :).

Hope that helps :)
Islam.

**Comment by hoechenberger** [comment] 2022-01-23 11:03
This is still relevant and, in fact, a bit of a disappointment this is still missing 😕

**Comment by RazorII** [comment] 2022-03-13 08:48
I've been getting a lot of people to switch to Signal but the lack of Live Photo support is making it harder ... it's an expected feature that brings a lot of disappointment and hesitance for casual users, especially the older folks in my extended family.

**Comment by Alyaron** [comment] 2022-05-12 09:41
yes!

**Comment by Cerberus0** [comment] 2022-07-13 18:19
Please ignore the stale bot, it does not know the difference between bugs and feature requests because [this is no longer the right place to submit or discuss feature requests](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md). Please let this GitHub issue be closed and continue this discussion on the community forum:

https://community.signalusers.org/t/live-photo-support/11687

Thanks!

**Comment by RazorII** [comment] 2022-10-12 02:19
This isn't stale, just being ignored!

**Comment by EvanHahn-Signal** [comment] 2022-10-12 14:52
As was mentioned, we'd like to use GitHub for bug reports, not feature requests. Please use [this community forum thread](https://community.signalusers.org/t/live-photo-support/11687) to discuss this feature further, and the community forums to discuss other feature requests in general.

**Closed by EvanHahn-Signal** 2022-10-12 14:52 UTC
