### ISSUE TITLE
Setting profile picture in iOS 13 fails

### ISSUE THREAD

**Issue by lucasjbyoung** [signalapp/Signal-iOS#4211] opened 2019-06-20 10:19 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Profile update fails when saving an avatar image selected either from the camera library or taking a photo on iOS 13 Developer beta 2. This does not occur if the username is updated, only the photo

### Steps to reproduce
- install signal from the App Store on iOS 13 developer beta 2
- During the profile creation process, select or take a photo
- Save your profile 

**Actual result:** An alert pop up “Error: Profile update failed”.

**Expected result:** The profile should save successfully 

### Device info

**Device**: iPhone X

**iOS version**: 13 developer beta 2

**Signal version:** 2.40.0.25

### Link to debug log

https://debuglogs.org/c0cb18682d768755bcba4eb392590f40339f45a76c7ca34aa387d7e75f53e318.zip

**Comment by u32i64** [comment] 2019-06-20 10:29
Maybe same cause as #4209

**Comment by Imperiopolis-Signal** [comment] 2019-06-25 07:04
Yep, this is a dupe of #4209. We are aware of and investigating the issue.

**Closed by Imperiopolis-Signal** 2019-06-25 07:04 UTC
