### ISSUE TITLE
Large photos (e.g. from a smart phone camera) cannot be opened at all on Signal 2.29.1

### ISSUE THREAD

**Issue by jmhertlein** [signalapp/Signal-iOS#3860] opened 2018-09-02 04:23 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After the recent update that changes it so signal doesn't display image previews for large-dimension images, images are no longer viewable in any way. Tapping on an image just brings up the "share" dialog. 

### Steps to reproduce
- send an image, or receive an image. In this case, my SO is sending photos taken on a Samsung Note 8's primary camera to my iphone.
- You'll see it just says "JPG" and a file size, instead of showing the thumbnail/preview
- Tapping on it does not open it, just pops up the "select an app" picker. 

**Actual result:** There is no clear way to view images in the app anymore.

**Expected result:** I should be able to easily view these images.

### Device info

**Device**: iPhone 8S

**iOS version**: 11.4.1

**Signal version:** 2.29.1

**Comment by czekaj** [comment] 2018-09-02 22:06
I have anecdotal evidence of the same thing happening on iOS with Signal 2.29.1 when I send a photo from my Pixel 2 camera or an mp4 video I downloaded. 

Smaller photos (like saved by WhatsApp which resizes and compresses photos) are received without a problem on Signal 2.29.1 on iOS.

**Comment by vaxus** [comment] 2018-09-02 22:57
I am seeing the same issue as well.

Device: iPhone 7 Plus

iOS Version: 11.4.1

Signal Version: 2.29.1.1

See attached screenshot.
![chat jpeg issue](https://user-images.githubusercontent.com/6054594/44961605-49cd3180-af57-11e8-8686-5eefac5f9a2e.jpeg)

**Comment by nzbart** [comment] 2018-09-03 03:26
This is affecting me, also. Is it only affecting a small group of people, or is it a really inconvenient bug that's affecting everyone?

**Comment by nzbart** [comment] 2018-09-03 04:33
Good point - my scenario is Android -> iOS as well.

**Comment by lostwithouthope** [comment] 2018-09-03 08:05
Same issue here wenn picture is sent from Android to iOS, but not in the other direction.

**Comment by zynexiz** [comment] 2018-09-03 09:58
My friend has an iOS device, and I'm on Android 8 (Sony firmware) and we both have this problem both ways. He can download it to show the image, in my case I don't even see that a image is sent.

**Comment by czekaj** [comment] 2018-09-03 17:27
I guess we'll need @michaelkirk-signal / @michaelkirk to get involved since he made the changes related to image and video validation in 2.29.1.

**Comment by skbdba192** [comment] 2018-09-03 22:14
Can confirm that iOS>iOS is having the same problem, as well as iOS>Android and back, for me at least. I am running iOS 12 pub beta 10, and signal 2.29.1.1

**Comment by KienHui** [comment] 2018-09-04 14:18
I'm just here to boost the signal on this issue. I've got the same issue (as does my family members on iOS).

**Comment by KienHui** [comment] 2018-09-04 14:39
So, looking through at the commit, I think the cause is in https://github.com/signalapp/Signal-iOS/blob/e715bf9ea2f51e2d0c4549d7b4fa68e442e4d026/SignalServiceKit/src/Util/NSData%2BImage.m , around line 138. It effectively restricts the image to being 4 megapixel in resolution. However, we're still sending images larger than that. If  `CGFloat kMaxDimension = 2 * 1024;` is changed to `CGFloat kMaxDimension = 4 * 1024;` Then most people's phones will be perfectly fine (until resolution increases for most people again). Or at least, it's there for pictures not showing up.

**Comment by michaelkirk-signal** [comment] 2018-09-04 16:31
Hey all, thanks for the feedback. We're aware of this issue and working on fixing it.

**Comment by mossmann** [comment] 2018-09-07 00:53
A little workaround I found for viewing "large" images within Signal: Copy and paste the image into an outgoing message (which you need not send). It isn't a great workaround, but maybe it will help someone until this issue is addressed.

**Comment by greveritt** [comment] 2018-09-07 01:29
My friend with an iPhone said he saved the file and opened it in another program. He said that did it.

**Comment by mossmann** [comment] 2018-09-07 01:41
Yes, exporting a large image works, but that exposes the image to another app, which could be undesirable for viewing private images.

**Comment by jmhertlein** [comment] 2018-09-07 03:59
It's also terrible UX, which IMO is a security concern, since it might drive users to a less-secure but more-convenient alternative.

**Comment by michaelkirk-signal** [comment] 2018-09-07 15:33
This is fixed in the current beta. If you'd like to help test before we get to production, send a message to support@signal.org with the subject "sign me up for the iOS beta"

**Comment by wormeyman** [comment] 2018-09-07 16:28
I don't see this issue taged in any commits what ended up being the fix?

**Comment by zynexiz** [comment] 2018-09-07 17:34
Got the update today, and as far as I can tell it's working.

**Comment by karlstr** [comment] 2018-09-08 22:13
When will this be in production?

**Comment by michaelkirk-signal** [comment] 2018-09-09 18:41
This fix has shipped with the 2.29.2 release - in the app store as of a few minutes ago.

**Closed by michaelkirk-signal** 2018-09-09 18:41 UTC

**Comment by czekaj** [comment] 2018-09-09 21:33
Just tested it and it seems to work for large photos but large videos still don't work 😢
Should we open another issue?

**Comment by mschenchang** [comment] 2018-09-10 06:01
But this problem still exist for my phone: iphone 6s, latest version of signal. The photo I sent is fine, I can see them, but not the photo other people sent to me, it's written always JPG file as shown above, no matter how big how small it is.

**Comment by michaelkirk-signal** [comment] 2018-09-10 13:07
@czekaj - what was the source of the videos? Do you know their resolution? Can you provide an example?

**Comment by michaelkirk-signal** [comment] 2018-09-10 13:08
@mschenchang - What version are you running? Can you submit a debug log?

**Comment by anniejalota** [comment] 2018-09-10 18:47
Thanks for the fix! My app didn't auto-update but just updated the app to 2.29.2 and seemed to have resolved the issue.

**Comment by mlindner** [comment] 2021-01-23 18:38
I'm seeing this same issue still.

**Comment by mmannes** [comment] 2021-02-02 18:49
> I'm seeing this same issue still.

Same here. Picture below shows how galery looks like:
![signal-2021-02-02-154338](https://user-images.githubusercontent.com/1824650/106647426-adffdf80-656d-11eb-8358-003f047c875a.jpeg)

When I wait a few time, like 30 seconds, some pictures become visible but when I scroll just a few pixels they become black again and sometimes another one shows and hides while scrolling a little more.

I am having this issue using a Samsung Galaxy S9. My wife's phone is a S9+ and this bug does not seems to occur.

**Comment by cfconrad** [comment] 2021-06-24 20:45
I also face this problem with larger images like
