### ISSUE TITLE
Prevent SS7 “bug”

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3011] opened 2018-02-15 10:01 UTC
What if during the installation of signal you implement a feature that could be enabled or not that makes the installer decide if after the sms of phone number verification he wants to link to that device codes backup like most of services do when you enable 2FA you usually print that codes. So furbo to the SS7 “bug” if someone’s Intercept my sms he can’t still login without those codes

**Comment by NinebitX** [comment] 2018-02-15 15:15
Dupe of https://github.com/signalapp/Signal-iOS/issues/1703

Related: https://github.com/signalapp/Signal-Android/issues/5599

**Comment by leonardoporpora** [comment] 2018-02-15 15:57
I think it could be done without problems. Just a code that someone have to copy and I repeat this feature is not enabled by default but someone who wants could enable it. I think it would be fair

**Comment by michaelkirk** [comment] 2018-02-15 17:10
closing as dupe of #1703

For further discussion please take it to the community forum: 
https://whispersystems.discoursehosting.net/

**Closed by michaelkirk** 2018-02-15 17:10 UTC
