### ISSUE TITLE
No notifications on iPhone8 / iOS 14.4

### ISSUE THREAD

**Issue by MatejKovacic** [signalapp/Signal-iOS#4852] opened 2021-01-30 10:25 UTC
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am not receiving notifications at all. I receive notifications only when I run Signal (enter into the app manually).

### Steps to reproduce
- user calls me or sends me a message
- I do not receive notifications
- when run the app manually, I get all old notifications 

**Actual result:** No notifications when app is running on background. Please note that I have not changed any iOS system settings and in the past I have been receiving notifications normally.

**Expected result:** I should get notifications when app in background.

### Device info
**Device**: iPhone 8

**iOS version**: 14.4

**Signal version:** 5.2.1.3 (the latest available on AppStore)

### Link to debug log
https://debuglogs.org/77aef09c6e8f5b9969755d2a10db71b0e206b258dccefca8dc4e6937a6f77355.zip

**Comment by i7u** [comment] 2021-01-31 13:08
Possible duplicate of https://github.com/signalapp/Signal-iOS/issues/4499

**Closed** 2022-01-31 02:31 UTC
Labels: wontfix
