### ISSUE TITLE
 Add support for formatting text with Markdown 

### ISSUE THREAD

**Issue by lokesh-krishna** [signalapp/Signal-iOS#1542] opened 2016-12-14 02:54 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Feature Description
There is currently no support to format text as italic, bold or to underline or strikethrough.

### Screenshots
WhatsApp handles this really well on Android and iOS (have never used the web interface) though it would be better to implement Markdown tags than to come up with our own tags like WhatsApp did.

The way WhatsApp does it is that it turns

![7c1a94e0-ab15-11e6-80b4-c5b8acf27e44](https://cloud.githubusercontent.com/assets/20235646/21167769/d78a831e-c1d4-11e6-9024-75eaebeb9d41.png)

Into 

![80dd3906-ab15-11e6-8f35-76830910d0e6](https://cloud.githubusercontent.com/assets/20235646/21167952/42bdb420-c1d6-11e6-9786-1c2592d5c4b0.png)

This is already a filed issue on the Android repository: https://github.com/WhisperSystems/Signal-Android/issues/5534

This is to make the feature cross platform.

**Comment by callodacity** [comment] 2017-07-08 01:29
Could this be implemented with something like https://github.com/iwasrobbed/Down ? It outputs into a variety of formats, including `NSAttributedString`, and is customisable (we obviously don't need to support *all* of Markdown, just a smaller subset of it).

**Comment by SRugina** [comment] 2020-02-17 22:27
Hi,

As I've explained on the [signal community forum](https://community.signalusers.org/t/font-styling-for-signal-messages-e-g-using-markdown/612/54), I'm very happy to work on this for android, desktop, and iOS. I've explained my methodology and decisions there too, but it will not be hard to add addition styling options on top of my 'minimum' requirements.

Also explained there is my current status on this. After 2 days, in my spare time, I've got the rendering of styles working on android and desktop - very soon I will port the functions across to iOS too. My next steps (again explained at the forum) are to get previewing of stylings, then the style menu popup options working. 

Currently my solution applies to bold (\*bold*), italic (\_italic_) and strikethrough (\~strikethrough~) - the reasons for deviating from commonmark explained in the forum post - but it will not be hard to expand on this, e.g. for \`monospace`.

**Comment by Merrit** [comment] 2020-03-19 14:10
I would strongly prefer to ability to use the markdown I am familiar with, like \*italic\*, \*\*bold\*\*, \~\~strikethrough\~\~.

**Comment by SRugina** [comment] 2020-04-09 16:01
@Merrit While for you that may be familiar markdown, for many transitioning from messaging apps such as WhatsApp or Slack, the single-length distinct styles are more familiar - and implementing the option to use all possible markdown variants would complicate the code considerably.

Code also has to be more complicated to deal with multiple character/same character usage - i.e. it is a lot simpler to deal with distinct differences of the same length, otherwise you might end up with \*\*bold** becoming both bold and italic, due to it containing a text wrapped in single-asterisks as well as being double-asterisk-wrapped text (this is a simple edge case to resolve, but the first that I could think of).

**Comment by WhyNotHugo** [comment] 2020-12-13 16:32
Is any work in this ongoing? I'd love to experiment on it, but given my lack of proficiency in iOS, doubt I can get something finalised on my own.

**Comment by SRugina** [comment] 2020-12-14 01:23
@WhyNotHugo The Desktop and Android versions are, in essence, functional. No progress on iOS, however. Though if you feel up to the challenge of translating the other implementations into the iOS version, go for it!

**Comment by fooness** [comment] 2021-01-12 11:52
Also `inline code` via \`code\` and …

```
code
blocks
```

via

\`\`\`
code
block
\`\`\`

… would be very helpful.

Please Signal, support basic markdown formatting.

**Comment by SRugina** [comment] 2021-01-13 13:27
It has been confirmed that Signal is working on implementing this feature.

> These things would really make the experience for my family and I complete
>
> - Support for backups and transfer on Android. Not manual, > but automatic like iOS
> - Support for ChromeOS via Android Tablet support
> - Support for simple markdown like bold, strike through etc.
>
> > **signal_app**: Great list, we’re working on all of these!

[Source](https://www.reddit.com/r/technology/comments/kt91qk/signal_private_messenger_team_here_we_support_an/gikr0l6/)

**Comment by Geremia** [comment] 2021-02-06 23:48
You can already [do this with Unicode](https://github.com/Geremia/RichTextUnicode); cf. the Javascript-based [YayText.com](https://yaytext.com/).

**Comment by WhyNotHugo** [comment] 2021-02-09 10:50
What yaytext.com generates is terrible: those characters cannot be read by screen readers, translators, or any form of accessibility tool.

**Comment by luismanriqueruiz** [comment] 2021-09-01 01:41
I hope this feature will be able in Android too. Thanks for your hard work by the way!

**Comment by Ectalite** [comment] 2022-01-23 10:10
Still relevant for me

**Comment by fvdm** [comment] 2022-01-23 10:47
Still relevant. The lack of formatting makes important text look boring and won't be read. Especially annoying with covid instructions in a group or guiding someone through difficult steps.

**Comment by finnegandewitt** [comment] 2022-01-25 20:51
**Still Relevant!**

**Comment by finnegantdewitt** [comment] 2022-01-25 20:52
**Still Relevant!!**

**Comment by Cerberus0** [comment] 2022-01-25 22:33
Hello everyone,

As much as I want this feature as well, I think we should first and foremost respect this project's [contribution guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md), which clearly state:

>**The issue tracker is for bugs, not feature requests**
>
>The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#issues). The purpose of this issue tracker is to track bugs in the iOS client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

Please close this GitHub issue and continue the discussion on the community forum:

https://community.signalusers.org/t/font-styling-for-signal-messages-e-g-using-markdown/612

Thanks!

**Comment by fvdm** [comment] 2022-03-26 23:34
Still relevant

**Comment by NiklasBr** [comment] 2022-03-28 08:06
@Cerberus0 This issue was created in 2016, when no such forum existed, the part of the contribution guideline you quote was added two years later.

**Comment by kaktusztea** [comment] 2022-03-28 16:20
I understand it was created earlier, but the devs now keep track on feature requests in the forum.
So you can keep this open, but nothing will happen to it 🤷‍♂️

**Comment by WhyNotHugo** [comment] 2022-05-28 21:59
Still relevant.

**Comment by Cerberus0** [comment] 2022-07-13 15:10
Please ignore the stale bot, it does not know the difference between bugs and feature requests because [this is the wrong place to submit and discuss feature requests to begin with](https://github.com/signalapp/Signal-iOS/blob/main/CONTRIBUTING.md). Please let this GitHub issue be closed and continue this discussion on the community forum:

https://community.signalusers.org/t/font-styling-for-signal-messages-e-g-using-markdown/612

Thanks!

**Comment by NiklasBr** [comment] 2022-07-13 19:26
This isn't a feature request, it's about resolving an issue regarding parity with the Android version.

**Comment by Cerberus0** [comment] 2022-07-13 19:37
Signal Android does not yet include support for markdown, either. Even if it did, issues regarding parity are still tracked on the community forum as separate feature requests:

https://community.signalusers.org/t/wiki-feature-comparison-android-ios-desktop/12003

**Comment by NiklasBr** [comment] 2022-07-14 07:06
Oh, sorry, it looked like the Android issue had been resolved a while ago.

**Comment by brettp** [comment] 2022-09-30 03:28
This is still a missing feature, and this ticket is the top Google result when searching. Has there been movement toward implementation? Anything that can be done to help since this is a very common feature in modern messaging apps?

**Comment by EvanHahn-Signal** [comment] 2022-11-30 16:41
We're trying to use GitHub for bug reports and [the community forums](https://community.signalusers.org/c/feature-requests/17) for feature requests. Please open a thread there (or find an existing one).

(PS: I'd love to have this feature, but we're a small team with a lot to do!)

**Closed by EvanHahn-Signal** 2022-11-30 16:41 UTC
