### ISSUE TITLE
Incorrect display of calling party identification of a conventional phone call after ending a signal call: wrong name displayed

### ISSUE THREAD

**Issue by EDR10000** [signalapp/Signal-iOS#4614] opened 2020-11-04 21:52 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Following the end of a signal call, a regular phone call displays incorrect calling party identification, leading you to believe you’re receiving a signal call (rather than a phone call) and from the person you most recently talked to on signal.

### Steps to reproduce
- make a signal call
- talk
- end call
- have someone call you with a regular voice line
- while ringing, incorrect caller ID is displayed

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Previous signal caller is displayed
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
iOS should display calling information for current call ringing.

Suspicion is that the code that ends call does not destroy/garbage collect/release resources and an object following call termination.  Note: this could be an iOS bug.

### Device info

**Device**: iPhone 8+

**iOS version**: 14.0.1

**Signal version:** 3.21

**Comment by Genis-Sage** [comment] 2020-11-05 18:57
hey @EDR10000 
this sounds quite similar to this report in the Signal community forum:
[Telemarketers calling me, appearing as contacts. This has now freaked me out twice](https://community.signalusers.org/t/telemarketers-calling-me-appearing-as-contacts-this-has-now-freaked-me-out-twice/17607)

if it's the same, it's a bug of iOS 14: [iOS 14: Wrong Caller ID on Incoming Call](https://discussions.apple.com/thread/251814822)

**Comment by EDR10000** [comment] 2020-11-05 18:59
It is. I didn’t see a GitHub bug report. If I missed one, I apologize in advance.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EDR10000** [comment] 2020-11-06 16:48
iOS 14.2 does NOT exhibit the problem.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Imperiopolis-Signal** [comment] 2020-11-06 22:51
As noted, this is a bug in iOS 14 and not a bug in Signal. Closing accordingly.

**Closed by Imperiopolis-Signal** 2020-11-06 22:51 UTC
