### ISSUE TITLE
UX Failure When Setting Up New iPhone

### ISSUE THREAD

**Issue by defuse** [signalapp/Signal-iOS#3899] opened 2018-09-22 02:22 UTC
The following just happened to me:

1. New iPhone arrives.
2. I'm setting up the new phone, talking to my friend over Signal Desktop on my Macbook.
3. I install Signal from the app store onto my iPhone.
4. There is no option to add the new iPhone as a linked device or anything like that, so I click the blue "Register" button. After entering the SMS code it seems to work, but none of my conversations are there.
5. Now, my Signal Desktop that I was just talking to my friend on is non-functional (sending any message immediately fails with "Invalid authentication, most likely someone re-registered and invalidated our registration."). Sending messages on my old iPhone errors out with "Your device is no longer registered for your phone number. You must remove and reinstall Signal."

This is a pretty bad UX problem in my opinion. If I didn't know enough to understand the error messages I would be *extremely* confused, and it's looking like I'm going to have to uninstall and then reinstall Signal on every device I use it on and then re-verify safety numbers with everyone.

**Comment by Cerberus0** [comment] 2018-09-22 23:38
As a fellow Signal user, thanks for posting about your experiences with the app!

However, the project’s [contributing guidelines](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md) state that requests for new functionality such as this should be posted on the [community forum](https://community.signalusers.org/c/feature-requests) instead of here on GitHub. You can easily join the forum with your existing GitHub account.

I believe this submission can also be closed as a duplicate of https://github.com/signalapp/Signal-iOS/issues/823 and https://github.com/signalapp/Signal-iOS/issues/2542.

**Comment by defuse** [comment] 2018-09-28 16:13
My intent was for this issue to be about the UX bug that currently makes it very easy to screw up your account, rather than a request for significant new features. A less-desirable fix that doesn't involve adding significant new features would be some kind of warning message like "WARNING: You are about to create a new account for this phone number. You will have to re-link your devices and re-verify any safety numbers you have verified." So IMO this issue is logically distinct from #823 and #2542, but completing either of those would resolve this issue.

**Comment by mrkiko** [comment] 2018-10-17 09:02
In my opinion, this is not a new feature, bug a bug.

**Closed** 2022-01-31 23:45 UTC
Labels: wontfix
