### ISSUE TITLE
Profile name set

### ISSUE THREAD

**Issue by applepb** [signalapp/Signal-iOS#4548] opened 2020-09-09 01:13 UTC
Changes were not reflecting after saving and re opening the app iOS 13.3

**Comment by michelle-signal** [comment] 2020-09-09 23:58
Thanks for the report. Unfortunately I'm not able to reproduce locally and without debug logs we don't really have much information to go on.

Are you able to reproduce? Could you provide debug logs?
As far as repro steps go:
1. You edited your profile name
2. You tapped save, and saw a modal spinner while the profile name was saved
3. After saving, you could see the updated profile name at the top of the settings page
4. You mention that you "re-opened" the app. Could you provide more detail on what you mean by this? This'll be collected in the debug logs, but hearing it from you would definitely be helpful too.

I'm going to close this issue for now, since we currently don't have enough info to investigate. But if you reply back with this info I'll re-open and we can continue looking into this.

**Closed by michelle-signal** 2020-09-09 23:58 UTC
