### ISSUE TITLE
Signal app taking a big bite of battery on iOS

### ISSUE THREAD

**Issue by hknaralasetty** [signalapp/Signal-iOS#4496] opened 2020-07-06 04:05 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal still takes a significant amount of battery. All the other issues on this topic are closed but it is not solved yet. 
![82454923-18A2-452C-89F1-6F3CD72C8921](https://user-images.githubusercontent.com/45716271/86554576-a93d6380-bf6b-11ea-9d47-2007ffc7babc.jpeg)
![CFC800FC-5068-449C-876D-E5A5C05AD6B4](https://user-images.githubusercontent.com/45716271/86554583-ab9fbd80-bf6b-11ea-8c24-6193badf8982.jpeg)

### Device info

**Device**: iPhone 11

**iOS version**: 13.5.1

**Signal version:** 3.12.2.4

### Link to debug log

https://debuglogs.org/b671213f922b007169186fec2cd98b1d28ff036b65f2af6b041ce959712181a9.zip

**Comment by jmg1023** [comment] 2020-07-08 14:46
Have had this same problem. It drains the battery even when charging.

**Comment by tomiteko** [comment] 2020-07-09 17:37
same issue here
iPhone SE 2020
iOS 13.5.1
Signal 3.12.4.1

**Comment by ilokhov** [comment] 2020-07-19 09:44
Experiencing the same issue.

### Device info

**Device:** iPhone 8
**iOS version:** iOS 13.5.1
**Signal version:** Signal 3.12.4.1

### Link to debug log

https://debuglogs.org/01ecc71620d0e2f1610e6e509f3abad71c834112b89af9e8684143ec5ebbdb89.zip

**Comment by DXCanas** [comment] 2020-07-23 03:10
Checking in after latest update - same behavior. 

Might this have to do with just having really long conversations?

https://debuglogs.org/16936008659db11a1641e10fe05979851a51b20b6eb868ff867e180898d8c45d.zip

Pinging #4471  here, because this issue is open and that ones closed.

**Comment by f00b4r0** [comment] 2020-08-15 15:57
Same issue. iPhone SE 2020 gets hot when in chat mode, and burning hot when video chatting, with the battery depleting really fast. So fast that the standard wall plug can't keep up.

**Comment by witcheries** [comment] 2020-08-28 02:43
I'm seeing this issue as well. Signal is _always_ my top battery user app, going over 50% if I actually use it on my phone. Right now it's at 51% of battery with 22 minutes onscreen and 2 hours in the background. Honestly it's mind-boggling.
iPhone 11, iOS 13.6.1, Signal 3.15.0.23.

**Comment by komape** [comment] 2020-09-12 15:16
Please fix this. It forces me to always shut down Signal if I want to get through the day without intermediate charging 😕

**Comment by philnord** [comment] 2020-09-14 13:48
I also have this issue. iPhone X, 3.17. I installed yesterday and only have about 5 chats.

**Comment by Noonien-Soong** [comment] 2021-01-09 07:38
Same issue on my iPhone. Signal version 5.0.3.0. This month will see a lot of people moving to Signal due to them rejecting WhatsApp's new terms and conditions. Like others, I also asked a lot of people to move to Signal yesterday. I would say that makes this issue a high priority as the large number of new users will either make or break people's perception of the app. Please, please prioritize...

**Comment by febLey** [comment] 2021-01-19 08:40
I can confirm this as well, iOS 14.3 with Signal 5.2.1.

**Comment by brianlener** [comment] 2021-02-13 01:18
I have this issue too.

iPhone 11 Pro
iOS 14.4
Signal 5.3.2.1

**Comment by tfugmann** [comment] 2021-02-23 13:29
Same Issue:
iOS 14.4
iPhone 12mini
Signal 5.4.0.17

**Comment by levithanius** [comment] 2021-06-15 15:54
Also having this problem.
iOS 14.6
iPhone 12
Signal 5.14.0.35

**Comment by filikun** [comment] 2021-07-13 07:48
Yeah I have the same issue, the background usage goes bananas. Same spec/firmware as above. 

![CE6807D3-C794-4A1E-B992-E10020101879](https://user-images.githubusercontent.com/9947929/125412806-5679dc18-8880-4147-a35f-b830c083f80c.jpeg)
![1F6A22F7-F475-4B8E-A5B6-F8E98868E311](https://user-images.githubusercontent.com/9947929/125412813-8ab04a80-e3bf-11eb-8ca3-66b9060b616d.jpeg)

**Comment by febLey** [comment] 2021-08-31 07:18
I've kept an eye on my battery since 5.16 released and it improved the situation a lot for me:

https://github.com/signalapp/Signal-iOS/releases/tag/5.16.0.45

**Comment by levithanius** [comment] 2021-08-31 07:19
Can confirm, doesn't drain the battery for me anymore.

**Comment by meatballs** [comment] 2021-09-15 12:05
I have this problem on:

iOS 14.7.1
iPhone SE (2020 model)
Signal 5.20.0.93

**Comment by etavarez** [comment] 2022-01-10 03:33
wanted to comment in this issue to note that this appears to be an active issue for me on the latest iOS 14.8.1 and iOS 15.2. Background app activity is unusually high (30min onscreen, yet 1hr & 42mins of activity). Background refresh is disabled.

5.26.9.2

https://debuglogs.org/e84bfe9fc5d6a024c5ce7dc88e1a8df3d291a581bf2b8403d065cf2e84c1c090.zip

![43079489-8128-4EE2-A4A7-AD0375C78FBA](https://user-images.githubusercontent.com/12282651/148715485-b9161f7b-4bc9-4f17-8d04-b582522b069f.png)

**Comment by FuzzyQuills** [comment] 2022-01-11 02:34
I am also seeing this same issue on my iPhone SE 2016, with the battery monitor showing notifications as the high battery drain source. 

OS: iOS 15.2
Signal version: 5.26.9.2

Can attach screenshots if needed.

**Closed** 2022-03-19 06:23 UTC
Labels: wontfix
