### ISSUE TITLE
Image editor > crop tool rotates the image in the wrong direction

### ISSUE THREAD

**Issue by u32i64** [signalapp/Signal-iOS#4178] opened 2019-04-16 14:21 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the image editor, the crop tool rotates the image in the wrong direction.

### Steps to reproduce
- open Signal's image editor by using any photo
- select the crop tool
- tap the "rotate image" button

**Actual result:** Image rotates clockwise.
**Expected result:** As clearly indicated by the icon, the image should rotate **counter**clockwise.

### Screen recording gif
![20D487E0-3110-48B0-9640-0ECFE8B14D22](https://user-images.githubusercontent.com/19972511/56217533-136a9f80-606c-11e9-949f-b5226fd154c0.gif)

### Device info

**Device**: iPhone 6 Plus
**iOS version**: 12.3 Public Beta
**Signal version:** `2.38.1.2`

**Comment by denver-s** [comment] 2019-04-16 15:15
I can confirm this bug. 

Also, if you rotate 180° and then click the "undo" icon, the images goes back to the original orientation and not at 90°.

**Comment by michaelkirk-signal** [comment] 2019-04-23 15:34
Thanks for reporting. This will be fixed in the next beta - 2.39.0.3 or later.

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

> Also, if you rotate 180° and then click the "undo" icon, the images goes back to the original orientation and not at 90°.

This is intentional. The "undo" button returns to the original state, since we though that would be more useful than an incremental undo in the context of this particular tool.

**Closed** 2019-04-23 15:34 UTC
