### ISSUE TITLE
Frozen app, slow typing etc. while searching for contancts with defalut iOS keyboard

### ISSUE THREAD

**Issue by gsbabil** [signalapp/Signal-iOS#3304] opened 2018-04-17 09:59 UTC
- [x] I have searched open and closed issues for duplicates

-----------------------------------------------------------

### Bug description

1. Keyboard local-echo of typed words in the Signal contact-list
   search-bar (in the "New Message" screen) is very slow in the
   latest `2.23.4.2` version.

2. After navigating to the "New Message" screen (by tapping the
   top-right corner icon), the keyboard almost hangs on the first
   key-press (screenshot attached).

  - After the keyboard gets unstuck, the subsequent key-presses
    behave normally.

  - However, if the user goes back from "New Message" screen and
    come back, the same issue repeats.

  - This issue is unrelated to #2884, where a related problem is
    experienced, but with 3rd-party keyboards such as [Gboard][1].
    The issue described here is experienced with iOS's default
    English keyboard.

### Steps to reproduce

1. Start the Signal app

2. Tap on the top-right corner icon to initiate chat with a new
   contact

   - The new screen is called "New Message"

3. Start typing a contact's name. At the very first key-press with
   iOS's default English keyboard, the app/keyboard will freeze.

   - It will unfreeze in about 5 seconds, and act normal from there,
     until the user leaves the "New Message" screen.

   - The same freezing behavior will repeat if the user leaves the
     "New Message" screen, comes back again and start typing for a
     contact's name.

**Actual result:**

- The typed name/word would show up in the contact search-bar on the
  "New Message" screen after a noticeable delay of ~5 seconds.

**Expected result:**

- Immediate local-echo/feedback of any typed words is expected in
  the contact-list search-bar.

- The app should not freeze up while doing contact search in the
  background.

### Device info

- **Device**         : `iPhone 6`
- **iOS version**    : `11.3.1 (15E216)`
- **Signal version** : `2.23.4.2`

### Link to debug log

- https://debuglogs.org/cd140ca66a6cfbae802af73630ab15cb7e8c8652dd10b933253fe3dfe62f41b5.zip

### Screenshots

![signal-2018-04-017](https://user-images.githubusercontent.com/1061108/38862968-b60937e0-4279-11e8-92d2-663db10b625d.png)

[1]: https://itunes.apple.com/us/app/gboard/id1091700242?mt=8

**Comment by michaelkirk-signal** [comment] 2018-04-17 15:50
dupe of #2884, posting some details there.

**Closed by michaelkirk-signal** 2018-04-17 15:50 UTC
