### ISSUE TITLE
Photo taken in landscape mode didn't rotate when sent

### ISSUE THREAD

**Issue by BioTeckna** [signalapp/Signal-iOS#4334] opened 2019-12-11 17:01 UTC
### Bug description

This issue happens on my wife's iPhone SE (I was not able to reproduce on my iPhone XR). When a picture is taken horizontally from the Signal App , it doesn't rotate as it should when being sent. 

Normally, if the user takes a picture horizontally, on the next screen it rotates and it's possible to write a comment about the picture. On this screen the photo hasn't rotated correctly and is being send with the wrong orientation. 

### Steps to reproduce
- On an iPhone SE. Open a chat with a friend.
- Click on the little Camera icon to take a picture
- Rotate your phone to take the picture horizontally.
- Take the picture
- note that the picture hasn't rotate to a vertical position so the picture is 90° in the wrong orientation.
- Send the picture with the wrong orientation.

**Actual result:** Picture is taken oriented 90° incorrectly

**Expected result:** The picture should have rotated so we can see it in portrait mode

### Screenshots

![IMG_9548](https://user-images.githubusercontent.com/3942982/70642468-8b12bd80-1c3f-11ea-9d5c-3e51e755f0be.jpeg)

### Device info

**Device**: iPhone SE

**iOS version**: 13.2.3

**Signal version:** 3.0.6.0

The App isn't crashing so I don't know if I should provide some logs for this issue ?

**Comment by denver-s** [comment] 2019-12-11 17:55
I cannot replicate this behavior with iPhone 8 Plus (Signal 3.0.6.0).

**Comment by BioTeckna** [comment] 2019-12-11 18:31
I have more information: This only happens if the phone rotation is disabled. 
To reproduce, make sure the phone rotation is disabled and then follow the "Steps to reproduce" part. 

The question is: when phone rotation is locked, is it expected that pictures don't rotate?
In order to compare with other chat apps, whatsapp and telegram do rotate the picture even if the phone rotation is disabled.
If it's expected and by design, we can close this issue.

**Comment by michaelkirk-signal** [comment] 2019-12-13 18:02
Thanks for reporting. I've been able to reproduce and am taking a look. 

Disabling device rotation is key to reproducing the bug, since we've been using the device orientation to determine how to rotate the camera.

**Comment by rabbidiesel** [comment] 2021-01-21 21:15
Hi There,

This issue still persists.

iPhone 12 pro, iOS 14.3

**Comment by rhmarras** [comment] 2021-02-03 21:40
Issue persists. Motorola One Hyper with v5.3.10 Android 10 - screen orientation locked in portrait. photos taken in landscape appear locked in portrait (thus making the picture not autorotated and with the not-intended orientation) - thank you

**Comment by tyctor** [comment] 2021-04-12 08:57
On Iphone SE, photos from front camera (selfie) are wrongly rotated
![Screenshot from 2021-04-12 10-56-19](https://user-images.githubusercontent.com/44854182/114368629-de6f8580-9b7d-11eb-8ecb-4b55fe427a01.png)

**Comment by EbonyBirch** [comment] 2021-04-13 06:51
Signal's the only app I believe that doesn't automatically rotate images. I'm on Android 10 (Mi 9 Lite), I can confirm that this bug still does exist.
I've checked that recently and if I take a picture with built-in app, whether I rotate phone from vertical position 90 degrees right or left, the image taken is displayed horizontally, so there's some kind of detection how's the phone positioned via accelerometer readings and has nothing to do with the screen rotation function.

**Comment by BioTeckna** [comment] 2021-04-13 09:33
Agreed

Le mar. 13 avr. 2021 à 08:51, EbonyBirch ***@***.***> a
écrit :

**Comment by cravend** [comment] 2021-09-03 09:38
Just wanted to confirm it's affecting my iPhone 12 Pro! (I was about to make a new issue but realised it was a duplicate of this). Same as above, it's related to "rotation lock" being enabled on the device.

I assume it's partially due to the fact that signal has its own camera implemented. However, other apps that have their own cameras (e.g. [Halide](https://halide.cam)) rotate as expected, so Apple must provide _some_ sort of API to bypass rotation lock. I'd like to help more but my Swift skills are sorely lacking.

**Comment by BioTeckna** [comment] 2022-01-23 19:08
Yep, the issue still happen. If rotation is locked, taking pictures isn’t
rotating


Le dim. 23 janv. 2022 à 11:03, stale[bot] ***@***.***> a
écrit :

**Comment by tyctor** [comment] 2022-01-23 21:42
now there is edit option, so image can be rotated as needed
so for me this is ok

**Comment by EbonyBirch** [comment] 2022-01-23 23:15
> yes when rotation is locked image is not rotating, but i am not sure if it should (user choosen rotation lock can be interpreted variously) and also now there is edit option, so image can be rotated as needed so for me this is ok 👍

"Edit" option should be there for a situation where you want to rotate the image for some reason, not to fix something that's confirmed not working as it should. They could do it in WhatsApp properly, so why doesn't that work here? Signal is basically a better, more secure WA.

**Comment by kNsja5w** [comment] 2022-01-26 13:16
It's still a thing. Please fix this issue, it's a ticket on the community as well and hasn't been solved yet.
https://community.signalusers.org/t/auto-rotate-image-when-taken-horizontally/15528/10

**Comment by cravend** [comment] 2022-03-27 14:04
this issue is still relevant

**Comment by larstobi** [comment] 2022-05-26 18:41
This is still relevant.

**Comment by cravend** [comment] 2022-09-02 02:20
still relevant!

**Comment by andrew-hill** [comment] 2022-09-05 06:08
Still relevant on Signal 5.49.0.13 and iOS 15.6.1.

And this is definitely unexpected behaviour. I disagree with tyctor's comment that rotation lock might imply you want to lock the picture orientation. The rotation lock's purpose is to keep the user interface in portrait mode. It is not touted as a camera function. Other messaging apps rotate images accordingly, and I'm actually a little surprised the orientation of the photo isn't handled by iOS. Is it possible Signal is doing something unnecessary with the camera UI to create the problem?

**Comment by newhinton** [comment] 2022-10-22 16:44
This has also been an issue on android, but it has been fixed there:
https://github.com/signalapp/Signal-Android/issues/8611

The fix:
https://github.com/signalapp/Signal-Android/commit/9c7c94b2d423f6abf450702491f0d6090ac6f025
(Obviously it doesn't apply to ios, but for documentations-sake)
It was just allowed to rotate the camera-ui regardless of the lock. This automatically "fixes" the orientation of the image, just by allowing it to rotate.

Since android correctly handles this usecase, ios should follow this behaviour to keep it equal featurewise.

**Comment by wikir01** [comment] 2022-11-05 08:48
> Looks like this was fixed in 5.59 which is publicly available now? My iPhone 13 correctly keeps orientation of photos regardless of orientation lock.
> 
> [2dd12d8](https://github.com/signalapp/Signal-iOS/commit/2dd12d8566563aa5451389f45d4db9c23e26258a)

Yup, I just tried on my 14 and it works too. I guess this issue is fixed now 👏

**Closed** 2022-11-30 16:43 UTC
