### ISSUE TITLE
SIGNAL GET HANG AND WARMING MY IPHONE ON DOING MESSAGE 

### ISSUE THREAD

**Issue by AbroMansoor** [signalapp/Signal-iOS#4351] opened 2019-12-26 06:16 UTC
After new update to build # 3.1.0.20 signal behaving very weird like sending 3 or 4 message they get hang not go to chat person it shows it process and dots kept moving in circle have to complete go out side on main page of iphone than they get transfer to the chat person.

Please look in to this matter.

**Comment by alex-r24** [comment] 2019-12-27 08:50
I can also confirm this behaviour on an Iphone SE with an android chat partner with a long chat history containing many pictures.

situation after rebooting the phone
- signal on iphone receives messages from chat partner without problems
- I'm able to write to every one except to this chat partner
- as soon as I start replying or writing new messages towards this chat partner, the problem described by AbroMansoor happens and my phone gets warmer and warmer
- after closing the signal task, the chat messages are transferred to the chat partner as soon as I open the signal app
- phone cools down until next communication attempt
- writing messages to others works fine at any time as long as I don't try to chat with my "big chat history android chat partner".

**Comment by mheckel** [comment] 2019-12-29 13:12
I can confirm this as well. It affects only one conversation (the by far largest), ever since the recent updates. I run the most up to date version from the App Store.

Additionally, I cannot delete the conversation that is affected. The phone heats up and never finishes the deletion. The longest I've let it try to delete was around 20 minutes and since have given up.

**Comment by lliberadzki** [comment] 2019-12-29 21:50
Upvoted. Since recent updates very large conversations started freezing signal app. When i try to type anything, with that specific contacts, app freezes for over a dozen of seconds and then letters starts to appear slowly. Other conversations are unaffected. Using latest signal version form AppStore.

**Comment by jjohns71** [comment] 2019-12-29 22:00
Can also reproduce the issues reported above in the latest `3.1.0.20` ios update. (messages not sending, unable to delete the message thread entirely, phone heating up, etc.) In addition to the issues reported above, my default alternate keyboard (Gboard in my case) fails to load in the long message thread and image previews after clicking attachment icon remain blurry and won't attach to a message. I can provide additional debug logs if needed.

**Comment by richlv** [comment] 2019-12-30 09:19
Seems to be a duplicate of #4347.

**Comment by michaelkirk-signal** [comment] 2019-12-30 18:19
> @Nerd2k We're going to have a fix out as soon as the app store reopens from the holiday. Could be Sunday.

The 3.1.1 release is now available in the app store. Please update and let us know if you continue to experience this issue.

**Closed by michaelkirk-signal** 2019-12-30 18:19 UTC

**Comment by mheckel** [comment] 2020-01-03 07:45
Thank you! The update resolves the immediate issue, the conversation can be opened again and messages can be sent.

However, there is still a noticeable delay when opening the long conversation. Although typing is possible again, it is still sluggish and spell checking for instance often doesnt work as well. Also, I still cannot delete the conversation.

**Comment by Nerd2k** [comment] 2020-01-03 14:48
> Thank you! The update resolves the immediate issue, the conversation can be opened again and messages can be sent.

Confirmed 👍

> However, there is still a noticeable delay when opening the long conversation.

I can confirm that.
