### ISSUE TITLE
App Crashing on open

### ISSUE THREAD

**Issue by m-inglis** [signalapp/Signal-iOS#4240] opened 2019-08-11 03:06 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashing on opening

### Steps to reproduce
click on the app icon from phone main screen

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
App launches, goes to the base loading screen then closes.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
the app opens

### Screenshots

![Untitled](https://user-images.githubusercontent.com/53986751/62829055-5b30ac00-bbb2-11e9-9b6a-9d78f10e2a69.png)
![IMG_8943](https://user-images.githubusercontent.com/53986751/62829058-5e2b9c80-bbb2-11e9-894e-a87a29ce7a46.PNG)

### Device info

**Device**: iPhone 6s

**iOS version**: 12.4

**Signal version:** 2.41.0

### Link to debug log

I cannot get into the app to generate a debug log.

There is no crash log generated for signal.

![IMG_8941](https://user-images.githubusercontent.com/53986751/62829051-46541880-bbb2-11e9-8012-30bc425074ce.PNG)

I've attempted to delete and reinstall the app and the same thing happens.

**Comment by barboni** [comment] 2019-10-08 08:22
I have the same issue after upgrading to iOS 13. Restarting the iPhone helps, but after some time, the Signal App hangs again

**Comment by danielsmw** [comment] 2019-10-30 20:13
I have also had this problem ever since iOS 13 upgrade. It's extremely frustrating, and I end up restarting my phone 1-3 times a day depending on how often I use Signal.

**Comment by m-inglis** [comment] 2019-10-31 00:30
Never was able to get this fixed on the phone it was having issues on, stopped using signal for months because of it. Got a new phone eventually because the screen broke and a it started working again.

**Comment by sushidave** [comment] 2019-11-08 19:36
Same effect on a:
- Device: iPhone 5
- iOS version: 10.3.4
- Signal version: 2.45.2

On launch, the blue Signal startup screen auto-closes after 2 - 3 seconds. It stays open in the background though as if the app would be active.

**Comment by danielsmw** [comment] 2019-12-09 23:19
Okay, after living with this bug for a few months, I’ve had a lot of time to observe its behavior. I’m now almost certain that this is a memory issue. As long as I never open a very high memory demand program (like a game), the problem doesn’t seem to occur. As soon as I play around in a game for a while, signal gets stuck in the blue screen and I can no longer access the app interface. Interestingly, I do still seem to get message notifications after the app freezes, though I haven’t verified that 100%. 

This memory issue hypothesis may at least partially explain why the OP’s issue was resolved by upgrading their phone. 

Other apps crash when greedy apps take up all the memory, too. But those apps generally recover gracefully. Signal’s problem may be that it’s not handling properly the problem of systemwide memory exhaustion.

**Comment by Mihahn** [comment] 2020-12-11 17:22
Can't reproduce, is this still an issue? If not, please close your issue.

**Comment by sushidave** [comment] 2021-03-27 20:46
It's not an issue for me as I dont' use the mentioned device and app version anymore.

**Comment by danielsmw** [comment] 2021-05-10 20:01
I no longer use the device this was giving me issues on, but my wife does, and I can anecdotally confirm that this is no longer an issue.

**Closed** 2022-01-30 22:03 UTC
Labels: wontfix
