### ISSUE TITLE
URL breaks when message has “read more” link

### ISSUE THREAD

**Issue by menteb** [signalapp/Signal-iOS#4659] opened 2020-12-27 20:14 UTC
When receiving a message that is too long, one gets the "Read more" to expand. If the last part before the "..." happens to be a link, it opens the link with the abbreviated URL instead of the full link. Click read more and the underlying URL is correct.

E.g before clicking "Read more" you see: Https://signa...
It is clickable and opens the browser with the URL "https://signa" instead of the full URL.

**Comment by rohrz4nge** [comment] 2021-03-04 17:19
Is this a duplicate of #4394?

**Closed** 2022-01-31 03:31 UTC
Labels: wontfix
