### ISSUE TITLE
latest two testflights crash when sending or viewing media

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#4059] opened 2018-11-23 08:55 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

### Link to debug log

ios diagnostics crash id: B9E3260F-5895-47C5-A863-228A9D142A7A

**Comment by mailinglists35** [comment] 2018-11-23 08:56
https://debuglogs.org/233c4b520c45669c04aba09a5bbe5fee7613788ab2fd916724349197bf700cd7.zip-crash (delete -crash)

**Comment by michaelkirk-signal** [comment] 2018-11-23 13:49
Can you fill out the template details, especially the iOS version and the Signal version?

Can you also include a crash report?

https://github.com/signalapp/Signal-iOS/wiki/Submitting-crash-reports

**Comment by michaelkirk-signal** [comment] 2018-11-23 17:33
Ok - unpacking your debug log, you're running iOS10.2 and running Signal-iOS Beta: 2.32.0.13

This sounds like a dupe of https://github.com/signalapp/Signal-iOS/issues/4048, which was fixed and shipped yesterday in 2.32.0.14.

I'm going to close this, but if you are still experiencing this issue please reopen.

**Closed by michaelkirk-signal** 2018-11-23 17:33 UTC
