### ISSUE TITLE
[Feature Request] Optional alternative to using number

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-iOS#2654] opened 2017-10-17 11:36 UTC
For extra privacy, can you please allow users to use something other than their number.

For example, maybe a randomly generated number or username or, a salted hash of their number similar to wickr and some other private messengers.

Thanks

**Comment by nrizzio** [comment] 2017-10-17 22:02
Duplicate of #101

**Closed** 2022-01-31 21:44 UTC
Labels: wontfix
