### ISSUE TITLE
No notifications coming through

### ISSUE THREAD

**Issue by foxandsqueeze** [signalapp/Signal-iOS#4912] opened 2021-03-09 22:25 UTC
- [ ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I’ve updated and everything but no matter what I do I no longer get notifications for Signal. I don’t even receive the messages until I go into the app, even if they were sent beforehand. All my settings are set for them to work, and they did originally- and though I haven’t changed anything to make this glitch happen, it now is. Please help!

### Steps to reproduce
- I don’t have to do anything they just don’t come through
- the only time they do come through normally is if I have my phone open and the app open as well. Otherwise no notifications or any indication of a message received comes through.

**Actual result:** no notifications come through.

**Expected result:* I would like to receive notifications like I originally did please.

### Device info

**Device**: iPhone X

**iOS version**: 14.4.1

**Signal version:** 5.7

**Comment by dalaeance** [comment] 2021-03-24 23:14
I am not having this problem, personally, (I use Android), but I've heard from 2 individual iOS users that this is happening to them. And this was within the past couple days.

**Comment by aleph-naught2tog** [comment] 2021-05-12 13:43
I'm unsure when I started having this issue, but I also am not receiving notifications at all on my iPhone 8. As in the OP, I've triple-checked all the settings.

**Comment by foxandsqueeze** [comment] 2021-05-12 13:56
My issue never went away on my phone BUT I got a new iPhone 12 (for
unrelated reasons lol) and I downloaded signal (signed in with same account
and everything) and I now receive notifications again. I know that’s not a
cheap or easy fix, but since it DID fix the issue, I thought I’d let
everyone know!!
Good luck and I’m sorry because it is so frustrating!

**Comment by krinoid** [comment] 2021-07-25 19:32
Same issue here - no notifications when signal is in the background/closed. When I open the app, messages/missed calls notifications start showing up. I know at least 1 other person with the same issue. I've tried every workaround from https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#ios_notifications_troubleshooting
but it didn't help.

Let me know what info might be useful to debug, thanks!

**Comment by krinoid** [comment] 2022-01-24 13:19
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

I'm on the latest Signal version on iOS and the problem persists, no notifications. My friend had this problem a while ago but it got solved after one update but no luck for me.

**Comment by krinoid** [comment] 2022-03-29 20:24
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

The issue is still relevant. Commenting so it stays visible.

**Comment by T4cC0re** [comment] 2022-03-30 19:47
Seems to be a dupe of #5072

**Closed** 2022-06-05 22:21 UTC
Labels: wontfix
