### ISSUE TITLE
Show time stamps by sliding left

### ISSUE THREAD

**Issue by petergault** [signalapp/Signal-iOS#1058] opened 2016-01-26 01:40 UTC
i love signal! Great app, I use it every day. The only thing I miss is seeing time stamps of the messages.

**Comment by 2-4601** [comment] 2016-01-26 01:42
Duplicate of #695 :)

**Comment by Ginari** [comment] 2016-01-26 08:13
I think he is meaning that when you slide right in imessage for example it shows you the exact time the message was received/sent.

**Comment by Mojo90** [comment] 2016-01-26 17:26
Swipe left in iMessage shows the time stamps.
Swipe right is normally to get to the previous screen

**Comment by Ginari** [comment] 2016-01-28 10:51
I think that was meant. Sliding left then.

**Comment by iadmir** [comment] 2016-11-25 07:14
This feature really missing on Signal for iOS.
https://media.giphy.com/media/3oEduTcKZONTsu3PUs/giphy.gif

**Comment by basnijholt** [comment] 2017-07-04 06:53
Yes, this would be great. I have had multiple times that I needed to know the exact time of a certain message. Until now I did it by exporting the debug log and then figure it out, which is a quite horrible solution...

**Comment by iadmir** [comment] 2017-08-25 21:27
Is there any chance of implemanting this in JSQMessageViewController:
https://github.com/shaps80/iMessageStyleReveal
@charlesmchen

**Comment by Spylon** [comment] 2018-11-07 02:13
Any chance of this getting implemented soon?

I would be willing to make the change if I got some pointers.

**Comment by michaelkirk-signal** [comment] 2019-08-22 03:10
We don't track feature requests on GitHub, only bugs with existing functionality. Please see https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md for details.

The forum would be a better place to discuss new features: https://community.signalusers.org/

**Closed by michaelkirk-signal** 2019-08-22 03:10 UTC
