### ISSUE TITLE
Missing Landscape Mode

### ISSUE THREAD

**Issue by jeyca** [signalapp/Signal-iOS#3638] opened 2018-07-02 18:53 UTC
As in #937, I want to ask about the status of the implementation of a landscape mode. I know users who keep switching to Whatsapp because they can't write comfortably on the small keyboard in Signal. 

Like @MarianneF, I would just like to know which hurdles still exist to implement this feature, which has been discussed for a long time. And where we could help.

**Comment by Cerberus0** [comment] 2018-07-05 11:21
Hi @jeyca!

Welcome to the Signal iOS issue tracker!

This particular issue can be closed as a duplicate of https://github.com/signalapp/Signal-iOS/issues/937. If you would like to discuss the topic, please start a new discussion at https://community.signalusers.org/c/feature-requests/ios-feature-requests (you can sign up/login with your GitHub account).

If you decide to stick around and participate here on GitHub, please make sure to read [the project's contributing guideline](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#issues) and fill out [the bug report template](https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE.md) when you submit new issues.

Thanks!

**Closed** 2018-07-05 23:56 UTC
