### ISSUE TITLE
Last line of text for received message is randomly cut-off when UI font is set to large.

### ISSUE THREAD

**Issue by bentemple** [signalapp/Signal-iOS#5004] opened 2021-05-25 17:44 UTC
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
One of my messages that I sent to my wife was cut-off. The notification she received showed it correctly, and my messages show it correctly as well. In her app, it does not show correctly.
There are also reports of this happening here, though the issue is slightly different as it never resolves itself: https://www.reddit.com/r/signal/comments/dspc06/signal_cuts_messages_short_on_ios/ 
I believe it's probably related to the font size she has set on her phone. I included a screenshot of this setting as well.

### Steps to reproduce
- Send message "Wanna try vanilla?"
- Receiving device on iOS shows the word "vanilla?" cut-off.
- I verified this repeats for the same message multiple times by re-sending the same message "Wanna try vanilla?"
- It always shows up as cut-off on her phone in the messages.

**Actual result:** 
The text of random messages can be cut-off and not displayed.

**Expected result:** 
The text should _not_ be cut-off and should show the full message.

### Screenshots
Her phone:
![signal-2021-05-24-203312](https://user-images.githubusercontent.com/6243881/119543972-1bff2b00-bd46-11eb-9fc7-e1632f93c555.jpeg)

My messages:
![Screen Shot 2021-05-25 at 10 38 26 AM](https://user-images.githubusercontent.com/6243881/119543343-692ecd00-bd45-11eb-8b6c-758d9366ea04.png)

Her font setting:
![signal-2021-05-25-104147](https://user-images.githubusercontent.com/6243881/119543766-e2c6bb00-bd45-11eb-922d-e32744e2b895.jpeg)

### Device info
**Device**: iPhone 12 Mini

**iOS version**: iOS 14.5.1 (with font text size set fairly high)

**Signal version:** 5.12.0.51

**Comment by bentemple** [comment] 2021-05-27 00:21
Happened again with another message:
![Screen Shot 2021-05-26 at 5 20 37 PM](https://user-images.githubusercontent.com/6243881/119747073-c3fc1d80-be46-11eb-8e42-2dae6c5a2413.png)

**Comment by sriedl** [comment] 2021-06-14 17:09
I can confirm and this bug and reproduce it on my iPhone SE (1st gen).

**With large UI font, the last line of some messages is cut off.**
I assume that this happens when the larger text produces a line break / extra line which is somehow not incorporated in the calculation of the message box height.
This especially happens on **narrow screens**, e.g. iPhone SE or iPhone 12 mini

### Steps to reproduce:
**iOS Settings:**
  Settings > Display & Brightness, then select Text Size, move slider to the right (largest textsize)

**Example messages:** _(send them without quotes)_
"Die sind sehr behende"
"Die sind sehr behende ⏎test 2"
"Gut immer eine Entdeckung"

The last word(s) get cut off and won't be displayed in portrait mode.
(As a side note, the text boxes of the corresponding messages are rather narrow. Longer text messages seem to be shown in wider boxes and are much easier to read.)



### Screenshots:
Font settings: _(iOS Settings > Display & Brightness, then select Text Size)_
![signal-2021-06-14-174812](https://user-images.githubusercontent.com/17789747/121926148-f316f800-cd3d-11eb-960f-a900275f97f2.jpg)

Working text in landscape mode: _(note the words that are underlined in red)_
![signal-2021-06-14-174812 (1)](https://user-images.githubusercontent.com/17789747/121926283-193c9800-cd3e-11eb-93eb-cb1160f54f71.jpg)

Cut-off text in portrait mode: _(missing text marked red)_
![signal-2021-06-14-174812 (2)](https://user-images.githubusercontent.com/17789747/121926335-29ed0e00-cd3e-11eb-901e-b476adbefe3e.jpg)

### Device info:
**Device:** iPhone SE (1st gen)
**iOS version:** iOS 14.6 (with UI font text size set to highest)
**Signal version:** 5.14.0.35

**Comment by sriedl** [comment] 2021-06-14 17:13
I suggest to rename this issue to: **"Last line of text for received message is randomly cut-off when UI font is set to large."**

**Comment by davidperrenoud** [comment] 2021-09-14 12:54
It seems to be fixed in version 5.20.0.

**Closed** 2022-01-30 10:04 UTC
Labels: wontfix
