### ISSUE TITLE
Disappearing notifications on iOS and MacOS

### ISSUE THREAD

**Issue by pmetzger** [signalapp/Signal-iOS#4255] opened 2019-09-02 00:51 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Frequently, message notifications will pop up on my iOS device and then immediately disappear, as though they had been read on the desktop. However, the desktop app does not have focus and is not even visible.

### Steps to reproduce

I'm not sure how. It happens to me at least every day or two; I've caught it occurring more than once, but I cannot reliably reproduce the behavior.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I would normally expect that notifications would remain live on the iOS device until I cleared them, read the message on the iOS device, or read the message on the MacOS desktop app. However, as I noted, sometimes notifications simply pop up on my lock screen and disappear within a fraction of a second.

### Screenshots

Sadly, I can't reproduce this at will so I can't take screenshots or video of it

### Device info

**Device**: iPhone 6

**iOS version**: 12.4.1

**Signal version:** 2.41.1.2

### Link to debug log

If a debug log would be useful, I'm happy to submit one.

**Comment by pmetzger** [comment] 2019-09-02 00:56
BTW, note that for all I know this is a MacOS signal problem. Just in case: I'm running Signal Desktop v1.26.2. It does not appear that I'm getting proper desktop notifications all the time, either, so it may be that the desktop app is incorrectly acting as though it has focus or some such when it does not in fact have focus. Again, though, it is hard for me to debug this on my own without assistance.

**Comment by michaelkirk-signal** [comment] 2019-09-04 20:18
This sounds like a duplicate of a Signal-Desktop issue: https://github.com/signalapp/Signal-Desktop/issues/3310#issuecomment-527800594

If your behavior is different from what's described there, please re-open and we can discuss further.

**Closed by michaelkirk-signal** 2019-09-04 20:18 UTC

**Comment by pmetzger** [comment] 2019-09-06 23:41
This is indeed a duplicate of signalapp/Signal-Desktop#3310! Thank you!
