### ISSUE TITLE
Pulling down Control Center in Landscape causes orientation flips

### ISSUE THREAD

**Issue by teor2345** [signalapp/Signal-iOS#4128] opened 2019-02-08 23:04 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is related to #4127, but it's not the same bug.

When Signal Is in Landscape orientation (see #4127 to reliably get into landscape), and swipe down the Control Center, Signal reacts badly. It cancels the pull down, flips to Portrait, then flips back to Landscape again.

Pulling down Notification Center and pulling up the App Switcher also triggers this bug. Pulling up the Dock does not.

### Steps to reproduce
- lock your device in Landscape orientation
- open Signal, and get into Landscape orientation (see #4127)
- pull down the Control Center
- (you can also repeat the last step with the Notification Center or the App Switcher)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

For Control and Notification Center: Signal cancels the pull down, flips to Portrait, then flips back to Landscape again.

For App Switcher: Signal flips to Portrait, possibly causing the App Switcher to momentarily flip, then Signal flips back to Landscape, possibly causing the App Switcher to flip back.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

All orientations should stay Landscape. Control and Notifications Centers should be allowed to pull down.

### Screenshots

I can not sufficiently obfuscate the screenshots on my iPad.
Let me know if that's an issue, and I'll go fix them on my desktop.

### Device info

Device: iPad (iPad5,2)
iOS Version: 12.1.1 
Signal Version: 2.35.0.13 

### Link to debug log

I can't open the zip file on my iPad. I would like to know what it contains before I link to it publicly. (The app doesn't explain, or let me view it before submitting.)

If it's important, please let me know, and I'll use my laptop to check it.

### Link to Code Responsible

The bug is probably in this code, or the subsequent fixes:
https://github.com/signalapp/Signal-iOS/commit/39de96ac261b89542767b4f971f9d91dac2f2cce#diff-497fb8e87e6b43d3eed8fa7aa9a38927R71

**Comment by tzs1** [comment] 2019-03-27 17:52
Seems to be fixed (beta 2.38.0.9).

**Comment by michaelkirk-signal** [comment] 2019-03-28 17:10
Thanks for reporting, this should be fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

The orientation vs. app activation issues like this can be a bit hairy to track down. If you can still reproduce this behavior, please reopen the issue with the version you were running and the steps to reproduce.

**Closed by michaelkirk-signal** 2019-03-28 17:10 UTC
