### ISSUE TITLE
Adding ability to reply from Apple Watch

### ISSUE THREAD

**Issue by ventz** [signalapp/Signal-iOS#2618] opened 2017-10-06 08:30 UTC
Hi,

Could we get the ability to reply to messages directly from the Apple watch?

Getting the notifications is great, but not being able to reply renders it almost useless, since for each one you still need to pull out your phone.

**Comment by Mihahn** [comment] 2017-10-12 21:50
Duplicate of #774

**Closed** 2018-04-23 14:24 UTC
