### ISSUE TITLE
UX feedback: select mesages -> "Delete All"

### ISSUE THREAD

**Issue by crantok** [signalapp/Signal-iOS#5263] opened 2022-02-12 15:08 UTC
I searched in case anyone else has posted an issue about this. Apologies if I missed something.

The interface:
 -  I long-press a message on iPad and then choose Select from the menu that appears.
 - Now the message is selected and I have the opportunity to select other messages by tapping them.
 - In the top left of the message pane are the words "Delete All".
 - In the bottom left of the message pane is a dustbin symbol.

My experience:
 - The first time I used this interface, I tapped "Delete All" in the top left deleting all messages in the conversation, not just all messages that I had selected.
 - I only noticed the little symbol in the bottom afterwards
 - On subsequent occasions I have sometimes started to reach for "Delete All" reflexively when I only wanted to delete selected messages.

Comments:
 - I don't think the message-selection interface is an appropriate place to feature "Delete All". YMMV.
 - "Delete All" in the top left is much more prominent for me than the smaller symbol in the bottom left. If other people experience this too then that creates a high probability of "Delete All" being used inadvertently.

Request:
 - Please would you either remove "Delete All" from the message-selection interface, or make the interface for deleting only the _selected_ messages more prominent?

**Comment by Cerberus0** [comment] 2022-02-12 18:41
Hi @crantok,

Welcome to the Signal iOS issue tracker. Please note that this issue tracker is [only meant for bug reports](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#issues). Bugs should only be reported for existing functionality that does not work as intended. All other discussions/questions/requests belong on the [Signal Community forum](https://community.signalusers.org/), which you can easily join with your existing GitHub account. Please close this GitHub issue and submit your UX feedback there:

* https://community.signalusers.org/c/ux/28  

If you would like to submit bug reports here in the future, please use the provided [issue template](https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE/bug_report.md). If you feel like you are unable to make an idea fit within the confines of the template, that might be a sign that you are about to submit something that isn't a bug. Thanks!

**Closed as completed** 2022-02-13 10:30 UTC
