### ISSUE TITLE
Video always freeze

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-iOS#5046] opened 2021-07-02 12:22 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

when I send video through the integrated camera of signal every time it happens that they stop while the audio continues to be heard, sometimes it happens in the middle of the video while others at the beginning or at the end.  while sending videos made by the iphone camera I do not find this bug, I tested this bug by sending videos from iphone to android via signal and the videos are always seen the same as I see them so it is not just a visual bug.  while vice versa from android to iphone the videos are never freezed
edit: sometimes even if very rarely the videos are all black

### Video
https://user-images.githubusercontent.com/86835503/124273432-4c559880-db40-11eb-9f64-a2f4e879860c.MOV

### Device info

**Device**: iPhone SE (2nd generation)

**iOS version**: 14.6
Edit: 14.7.1

**Signal version:** 5.16.0.45
Edit: 5.16.1.3

Debug log: https://debuglogs.org/b421c099d4cf526e2891bdce31e42e58ef258d033f30532b6f4b4343249876f5.zip

**Comment by Anonban** [comment] 2021-07-28 19:51
It appears that the Signal team is not interested in such a serious bug, especially if for iOS... I noticed that the reports of bug for Android are closed faster 😫

**Comment by Anonban** [comment] 2021-08-05 20:57
Update: deleted my Signal account ad now im using threema... no bug... thanks Signal...

**Comment by naturalpb** [comment] 2021-12-16 15:54
This is a duplicate of issue [4577](https://github.com/signalapp/Signal-iOS/issues/4577)

Unfortunately, it's been open more than 14 months with no comment or activity.

**Comment by digitalsignalperson** [comment] 2022-02-15 00:30
Whenever someone with ios phone tries to send me video, I have to say "doesn't work let's use this other app". And it's been like that for years. Came searching for a bug after experiencing again today.

Exactly as described here https://github.com/signalapp/Signal-Android/issues/11542

- All videos I receive from ios contacts are frozen for several seconds with just audio playing. 
- If it's a short video you get one frozen frame. 
- It's been like this for me for all time (a couple years of using signal) on two different phones (pixel 2, pixel 4a)

**Comment by Tugzrida** [comment] 2022-04-16 03:36
I can confirm that this is still an issue on version 5.35.0. Sending videos from the selfie camera of my iPhone X to a friend with a Pixel does work, but videos taken with the main camera on my iPhone don't play properly on the Pixel.

I also tried exporting the video from signal to my camera roll and sending the video to my friend via email, and the video won't play in the camera roll on their phone either, so it seems to be that Signal is recording videos from the main camera on iPhones in a way that is not quite compatible with Android devices.

I tried playing the same exported video that I emailed to my friend on my MacBook and it plays fine in QuickTime and VLC, so really quite an odd issue.

**Comment by digitalsignalperson** [comment] 2022-09-14 00:52
Still relevant. Just had an IOS user send me a video to my android phone. First 3 seconds is frozen.

Not using signal much because of this.

**Comment by digitalsignalperson** [comment] 2022-12-13 09:33
i am not aware of this being fixed. not stale

**Comment by digitalsignalperson** [comment] 2023-03-14 02:58
bump

**Comment by Tugzrida** [comment] 2023-06-13 03:41
Just tried to reproduce this in a setup that had previously been broken, and it now seems to work. So that's one tick for the "this is solved" column 🤷🏻‍♂️

**Closed** 2023-06-13 16:33 UTC
