### ISSUE TITLE
Documents & Data in iPhone Storage doesn't change after deleting over a Gig of conversations

### ISSUE THREAD

**Issue by alias1a** [signalapp/Signal-iOS#2906] opened 2018-01-03 10:36 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Documents & Data in iPhone Storage doesn't change after deleting over a Gig of conversations.

### Steps to reproduce
- Create a one to one or one to group conversation
- Send multiple attachments (videos, photos, ... etc)
- Documents & Data in iPhone Storage capacity increases
- Deleting those conversations and attachments doesn't free the space
- Deleting and reinstalling the Signal App freed the space 

**Actual result:** A single or a group conversation that has a lot of attachments took a considerable space in the iPhone when checking the Signal App's Documents & Data under iPhone Storage, deleting the conversation doesn't free the space only deleting and reinstalling the app did.
**Expected result:** Deleting the conversation should clear the space from the iPhone storage.

### Device info

**Device**: iPhone 6S
**iOS version**: 11.2.1
**Signal version:** 2.19.3.3

**Comment by Mihahn** [comment] 2020-12-11 16:43
Duplicate of #2480.

**Comment by b3hni4** [comment] 2021-01-18 21:08
I also have the same issue.

Device: iPhone Xs 
iOS version: 14.3
Signal Version: 5.2.1.3

**Closed** 2022-01-31 07:47 UTC
Labels: wontfix
