### ISSUE TITLE
Textinput hidden by virtual keyboard when scaling font size systemwide

### ISSUE THREAD

**Issue by oldnick1818** [signalapp/Signal-iOS#5708] opened 2023-11-20 12:45 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The "autoscroll" function when typing a message isn't funtioning correctly when the font size is increased systemwide in the ios settings app.
Exact behavior: The last line of a message you are writing gets covered by the virtual keyboard. I believe the autoscrolling behaves like the fonts were not increased and therefore scrolls "to late" to the line you are actually writing.  The bug behavior seems to be also related to the length of the words you are typing. It doesn't appear, when the words a very short

### Steps to reproduce
- increase fonts system wide through iPhone setting. Increase by 1 step is sufficient.
- type a new message in the Signal app long enough (at least 2 lines).
- The bug seems only to appear if the messages contains longer words, as they are frequently in German for examply. Writing a message with only short words doesn't lead to the buggy bevaior.
- the buggy behaviour increases, the longer the message you are writing gets.

**Actual result:** the last line of the message you are writing gets hidden by the virtual keyboard

**Expected result:**  the last line of the message you are writing should be seen as otherwise you don't see what you are writing at the moment.

### Screenshots

![E5F30C04-0437-43EE-BA53-CB01B450F8C5](https://github.com/signalapp/Signal-iOS/assets/120641780/29adfc4b-e2cb-458b-80b2-c51b4d0e0828)
![3FAA3A03-667D-4926-A02A-6236EAD38003](https://github.com/signalapp/Signal-iOS/assets/120641780/c5ef9119-3020-4a60-8934-1729d10b1cb3)

### Device info

**Device**: iPhone SE 2020

**iOS version**: 17.1.1

**Signal version:** 60.50.0.13

### Link to debug log
[ https://debuglogs.org/ios/6.50.0/ecbd89f62ac7e37afb018fc8e0e1e9287354b3e4068e5c9aa8f80dc529631df6.zip

**Comment by oldnick1818** [comment] 2023-11-21 16:35
I should add that it is not possibe to scroll down to the line where the cursor is, as it scrolls back up immediately in the unfortunate position shown in the screenshots above.

**Comment by Miguel-Signal** [comment] 2023-11-21 16:38
Hi @oldnick1818, could you please email support@signal.org with a link to your debug logs and reference this Github issue?

To share a debug log from Signal iOS, tap your profile, Settings, Help, Submit Debug Log, Copy Link.

**Comment by Janikson9** [comment] 2023-11-25 14:17
There was a slight improvement in the course of the update.
However, the problem still occurs occasionally with some chats.

I have already written to signal support (with debug log) several times. So far without success.



https://github.com/signalapp/Signal-iOS/assets/152014058/3628fd63-47b7-4785-9784-b193aaf2ee44

**Comment by koch86** [comment] 2023-11-25 16:50
I can confirm the issue with iPhone 15 Pro / iOS 17.1.1

![IMG_0306](https://github.com/signalapp/Signal-iOS/assets/3626543/c2d1713d-6687-4655-97d7-8335283ea43e)

I did not change the text size - so for me the issue occurs with default setting.
Issue was first observed quite some versions ago (also with iOS 16).

![IMG_0309](https://github.com/signalapp/Signal-iOS/assets/3626543/ed84627c-f3e5-4780-bb89-7fc9acbe6b22)

**Comment by meyermarcel** [comment] 2023-12-04 11:36
This issue still exists for me as well.

I have the following versions:

iOS 17.1.2
iPhone SE 2nd Gen (A2296)
Signal 6.51

I have these preferences that deviate from the default view preferences in iOS to allow better readability for my eyes:

![IMG_4713](https://github.com/signalapp/Signal-iOS/assets/3398801/e6720d9b-04bf-4380-b17f-f61e561fe8a1) ![IMG_4714](https://github.com/signalapp/Signal-iOS/assets/3398801/690b98e9-5a0e-443c-8ffa-15464e6102b8)


I reproduced this bug by inserting

```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

in a note to myself and deleting the last words:


https://github.com/signalapp/Signal-iOS/assets/3398801/fe830e58-29e5-49f4-9f9f-8a17290b546a

**Comment by meyermarcel** [comment] 2023-12-06 19:58
> Would anyone willing to try out the latest Signal Beta (version 6.52.0.8) install it and tell me if it fixes this issue?
> 
> Follow steps from the support page here to join the iOS Beta: https://support.signal.org/hc/articles/360007318471

I installed the iOS Signal beta (Preferences -> Help -> Version -> `6.52.0.8`) and I get the exact same behaviour with my zoomed preferences and the `lorem ipsum...` reproducer shown in the video.

**Comment by hembeh** [comment] 2023-12-06 22:34
Can confirm that this behavior is present on iPhone 15 pro max 17.2 running signal 2.2. The issue is there since iOS 15 and is quite annoying.

**Comment by Miguel-Signal** [comment] 2023-12-07 13:56
We've just released Beta version 6.53.0.5, and would appreciate some feedback on this version!

**Comment by meyermarcel** [comment] 2023-12-07 19:31
> We've just released Beta version 6.53.0.5, and would appreciate some feedback on this version!

The bug seems to be fixed and Signal `6.53.0.5` with these reproducers:
* ✅ see comment above (https://github.com/signalapp/Signal-iOS/issues/5708#issuecomment-1838451760)
* ✅ `Standard` view zoom level and text size slider in the middle and entering these random words manually by typing:
  ```
  Kekdkdbd dndkd dkdkdldldldkfkkfkfkflflrnfkflfllfnfkfkfkfkrnfkkfkfkrnrr frkflrilrkff fkfkfldldlkfnfkdkdodidjdjd dfndkdllfkfkfkfkfkfkfkofifkrknfkfkfkrkf fnfkfkdlkr rkfkfkfldldöf ffkfllrd flflf reldlldd dkdkkdldf dldodllfld dldlfld flflfokdkd dkdkdldlkrlfkfkd dkdkdldkkrnff fkfkde dldllrldkd fkfofodlkr dkfkfkkfkf fnfkfkkdne dkdkdkkfd dkdkdld dkdldllflfldld ddkfldldlkrlfkf. Dkdkdldld fkflfkddnndldllflflf fkflfldf fkfkfknrkfofof fkfofodldösüüwüekfbf fnfkfkdldkd ffkfldlkekfkfbdkd dkdldldldllf fkdldlkfkfld dndlld dkdkkdd dkdldofidkf fkfkflpspd dkdlodod ddkfldooflfld dkdldllfnd dkdkkdoeüdükdd dndkd kdd dkd dkdkd skf dkd dkd dks dkd did dkd dkd dkd dke dkd dkd ekd dn
  ```

Maybe some other reproducer produces a different result.

**Comment by Miguel-Signal** [comment] 2023-12-13 19:35
This issue should now be resolved with the production version 6.53!

https://apps.apple.com/us/app/signal-private-messenger/id874139669

**Closed by Miguel-Signal** 2023-12-13 19:35 UTC
Labels: Acknowledged

**Comment by meyermarcel** [comment] 2023-12-13 20:02
Thanks for fixing this bug :)

>  There might already be a self-referential German word to describe “German words that are so big they won’t fit on a single line,” but we fixed the “lost cursor” bug that was affecting some long German words on iOS 17.

I don't believe that this bug only affected german users. I think this was a global bug. But I have no proof and I think that the version description was done with diligence.

At the end it is fixed and that's a good thing 🎉

**Comment by oldnick1818** [comment] 2023-12-19 16:09
Great thanks a lot!! 
The bug was rly annoying and fixing it improved my daily experience with the app a lot 🥳
