### ISSUE TITLE
Cannot share anything to signal 

### ISSUE THREAD

**Issue by wtangofoxtrot** [signalapp/Signal-iOS#4658] opened 2020-12-27 18:16 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description.
Sharing text, links or photos etc from an external app (say Firefox) won’t show signal as a share option in iOS

### Steps to reproduce
- share a website from Firefox, a photo from photos 
- select the more option to see all apps available

**Actual result:**  signal won’t show in the app list of supported targets to share text or media. Only way is to copy the content the. Open signal, manually find the group/contact to share with then paste it in there. 

**Expected result:** there should be an option to share content to signal

### Device info

**Device**: iPhone11

**iOS version**: 14.2

**Signal version:** 5.0.3.0

### Link to debug log

https://debuglogs.org/a5c59513e061797ed1c461f641eaff316b14581ffa5f7e82d2d077ec968f5769.zip

**Comment by Genis-Sage** [comment] 2020-12-27 22:54
Hey @wtangofoxtrot
this seems to be a duplicate of #4625

Answer from there:
This is an ios 14.2 bug 

Reboot can help

**Comment by wtangofoxtrot** [comment] 2020-12-29 02:01
Closing as a dupe of https://github.com/signalapp/Signal-iOS/issues/4625

**Closed** 2020-12-29 02:00 UTC
