### ISSUE TITLE
Add theme that is dependent on sunrise/sunset (Night Mode)

### ISSUE THREAD

**Issue by ilhe1s** [signalapp/Signal-iOS#4271] opened 2019-09-26 22:12 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

**Comment by Cerberus0** [comment] 2019-09-28 10:21
Hi @ilhe1s,

Welcome to the Signal iOS issue tracker! Please note that this issue tracker is only meant for bug reports. Bug reports should only be submitted for existing functionality that does not work as intended. Signal does not currently include a theme that is dependent on sunrise/sunset, which makes this a feature request. All feature requests are meant to be discussed and tracked on the community forum. I have now created this feature request on the forum:

* https://community.signalusers.org/t/allow-syncing-dark-mode-with-ios-system-theme/9445

I suggest closing this issue and continue the discussion there. You can easily join the forum with your existing GitHub account.

**Closed** 2019-10-02 13:35 UTC
