### ISSUE TITLE
I want to suggest a new feature

### ISSUE THREAD

**Issue by kimfom01** [signalapp/Signal-iOS#4692] opened 2021-01-10 16:49 UTC
Due to the fact that many of your new users are those who ditched WhatsApp, I want to suggest that you should add status update feature (maybe call it something else like "moments") so that we won't miss WhatsApp 😭

**Comment by AbhiVaidya95** [comment] 2021-01-10 17:32
I think the focus should be privacy based messaging application instead of creating a clone of Whatsapp or some other messaging application.

I don't think status/stories adds any productivity to the core functionality of messaging application.

**Comment by Genis-Sage** [comment] 2021-01-10 17:47
hey @kimfom01 and @AbhiVaidya95 

as stated in the [contributing.md](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests) (and also in the github issue template), feature request belong onto the [community forum](https://community.signalusers.org/c/feature-requests)

**Comment by Lord-V15** [comment] 2021-01-10 20:16
Yes, kindly close this as it is not a bug or an issue in the app.

**Closed** 2021-01-11 13:49 UTC
