### ISSUE TITLE
UISwitch displayed in wrong place

### ISSUE THREAD

**Issue by ajRiverav** [signalapp/Signal-iOS#4227] opened 2019-07-20 05:21 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Switch label for "Display Indicators" option is displayed in the wrong place. 

### Steps to reproduce
Settings -> Privacy. Sealed Sender section. 

### Screenshots

![IMG_F09292DDB525-1](https://user-images.githubusercontent.com/22076301/61574329-4ddd4180-aa8c-11e9-9fb7-523c6c25b8ef.jpeg)

### Device info

**Device**: XR

**iOS version**: iOS 13 beta 3. 

**Signal version:** 2.40.1.3

**Comment by ajRiverav** [comment] 2019-07-20 05:25
Issue must be in lines
https://github.com/signalapp/Signal-iOS/blob/master/Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m#L328-L353

**Comment by ajRiverav** [comment] 2019-07-20 05:28
Also, why is the next UISwitch in the Sealed Sender section (SETTINGS_UNIDENTIFIED_DELIVERY_UNRESTRICTED_ACCESS, aka Allow from Anyone) created in such a different way?

**Comment by ajRiverav** [comment] 2019-07-20 05:30
cc: @Imperiopolis-Signal (commit 5f4a4cb8e1), @charlesmchen-signal (commit 79d6384bc9)

**Comment by u32i64** [comment] 2019-07-20 08:41
Looks like this is a duplicate of #4219.

**Comment by Imperiopolis-Signal** [comment] 2019-07-20 15:36
This was fixed in 2.40.3.

**Closed by Imperiopolis-Signal** 2019-07-20 15:36 UTC
