### ISSUE TITLE
iOS app records the initial vibration

### ISSUE THREAD

**Issue by richlv** [signalapp/Signal-iOS#4616] opened 2020-11-07 13:02 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When recording a voice message, the initial sound from the vibration is recorded.

### Steps to reproduce
- Have vibration enabled.
- Record a voice message.
- Play it back.

**Actual result:** The initial vibration sound when tapping and holding the microphone icon is recorded.

**Expected result:** It is not recorded.

This seems to be different from https://github.com/signalapp/Signal-Android/issues/10150, as the vibration sound is actually recorded.

### Device info
**Device**: iPhone 6

**iOS version**: 12.4.9

**Signal version:** 3.21.0.10

**Comment by riyapenn-signal** [comment] 2021-01-06 18:02
Closing as duplicate of https://github.com/signalapp/Signal-iOS/issues/3900

**Closed by riyapenn-signal** 2021-01-06 18:02 UTC
