### ISSUE TITLE
Download Failed: PHOTOS , VIDEOS & VOICE messages are not able to download.

### ISSUE THREAD

**Issue by Hax0rgurl** [signalapp/Signal-iOS#4396] opened 2020-02-27 21:57 UTC
Temporarily resolved. See last comment. 

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Download Failed. PHOTOS , VIDEOS & VOICE messages not able to download.
If I reset my connection they will work briefly. 

### Steps to reproduce
- sender sends me a message
- appears as failed. 
- Close the app open again, and nothing. It happens for every message sent and received.
**Actual result:** photos appear to not have downloaded and voice messages say download failed. Messages sent take very long even though they are connected to the server.  Sometimes they never go through. 

**Expected result:** 
To see, hear messages, video and photos.

****temporary fix**** 
So apparently it was Adguard blocking the DNS to Signal. So they aren’t playing nice together for some odd reason. I’m going to submit a report on their side as well.  
### Device info

**Device**: iDevice iPhone Xr

**iOS version**: 13.4

**Signal version:** 3.5.0.2

### Link to debug log
 https://debuglogs.org/6d33cbc63991357ab8380aacb94b609279d562781223d67171ff71e1f7b4104b.zip

**Comment by Mihahn** [comment] 2020-12-11 17:37
Can't reproduce, is this still an issue? If not, please close it.

**Closed** 2022-01-31 09:46 UTC
Labels: wontfix
