### ISSUE TITLE
Read receipts are not always synced from linked iPad

### ISSUE THREAD

**Issue by NFM-8** [signalapp/Signal-iOS#4340] opened 2019-12-16 19:04 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Read receipts are not always synced from linked iPad to master device running latest Android version.

### Steps to reproduce
- Link and iPad to Android master
- Chat withy the linked iPad for a while without opening signal on the master device
- Open Android master device and observe that some messages are not marked as read, even if they are (happens only now and then)

### Device info

**Device**: iPad mini

**iOS version**: 13.3

**Signal version:** 3.0.6.0

### Link to debug log
https://debuglogs.org/61336111c182fd25f5bd5e0b2f1c8d2623dde1c63a2b03009f9448993c364ecd.zip

**Comment by NFM-8** [comment] 2019-12-18 08:58
Perhaps not related to iPad version, but delayed message delivery, as reported E.g. in https://github.com/signalapp/Signal-Android/issues/9267

**Comment by NFM-8** [comment] 2020-01-19 10:47
More indormation regarding this:

This happens way too often to be caused by random delays on message delivery. Additionally, this issue seems to only happen between iOS and Android, not between iOS and desktop.

I have Android as a primary device with linked iOS and desktop apps. I was able to reproduce this and capture logs from all of the devices.

Android: https://debuglogs.org/4e242a217933e24d462c25badb651b76e707df201e5c4482fe334a19dfead66b

Desktop: https://debuglogs.org/8b03eae520f7c620d238047e828bd639c3b90b27ea227443b2e0e1533d6fd64d

iOS: 
https://debuglogs.org/f1f611821b86b0a807656fd7636aa71e4976c562bfa5e973f99089d74008445e.zip

I think the sync message has timestamp 1579429432183. Read status was synced correctly to the desktop application, but not to the Android application.

**Comment by Mihahn** [comment] 2020-12-11 17:33
Can't reproduce, is this still an issue? If not, please close it.

**Closed** 2022-01-31 09:46 UTC
Labels: wontfix
