### ISSUE TITLE
App freezes when new chat icon is tapped.

### ISSUE THREAD

**Issue by rizwan95** [signalapp/Signal-iOS#4139] opened 2019-02-26 00:45 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app freezes when the new chat icon is tapped. I suspect that some heavy operation is done on the main thread. 

### Steps to reproduce
- Install a fresh Signal app.
- Start a new chat with a contact. The feature will work normally.
- Again try to tap the new chat icon and the app will freeze. 

Actual result: The app freezes. Unable to do any operation in the app. 

Expected result: My contacts list should have been presented.

### Device info

**Device**: iPhone 7 plus

**iOS version**: 12.1.4

**Signal version:** 2.36.0

### Link to debug log
https://debuglogs.org/29ec0682d7f3cc412407d6f8dc671a269f96b41da7d3a41b6d79889b3a04c140.zip

**Comment by pmeystre** [comment] 2019-02-27 22:07
I am also able to replicate this issue:

**Description**:
Tapping the 'New Message' icon, the application causes the app to hang for approximately 10 seconds. During this time, the app does not respond to any taps or to scrolling. The app behaves as expected once the 'Select a Contact' screen' loads.

Steps to Reproduce:
1. Open Signal, then tap the compose icon
2. Wait for 10-15 seconds

**Device Configuration**
- iPhone X 
- iOS 12.1.4 (16D57)
- Issue occurs both on Wifi and LTE

**App Configuration**
- Signal 2.36.1.0
- Issue occurs both in light mode and dark mode

Debug Log: https://debuglogs.org/0640a0cb2b55b890cafdd0ad56a7bfc7af69fda9fa37a5220d7ac6ba86df8b24.zip

**Comment by pmeystre** [comment] 2019-02-27 22:39
Update to above:

I found the cause (and solution) to this issue on another thread.

> I ended up finding the cause of the issue. It's because I had a contact added for the purpose of listing spam numbers. There is another issue open related to this, but at the time of creating this issue, I wasn't aware that it was the cause of what I was experiencing.
> 
> #4094

At some point I had [TrueCaller](https://www.truecaller.com/) installed on my device. This app created a single contact that included hundreds of spam numbers. 

I uninstalled Truecaller months ago, but I never removed the contact. I can't remember this causing Signal to freeze until version 2.36.1.0

After deleting the 'Spam' contact resolved the issue. Tapping the compose icon no longer causes the

**Comment by iamioannis** [comment] 2019-03-13 22:42
Can confirm replication. Experienceing too.

**Comment by rizwan95** [comment] 2019-03-14 04:13
The issue is not related to truecaller itseems.

**Comment by gsbabil** [comment] 2019-03-15 20:51
Likely to be the same issues as: #3304 and #2884.

**Comment by tzs1** [comment] 2019-03-27 17:50
Seems to be fixed (beta 2.38.0.9).

**Comment by michaelkirk-signal** [comment] 2019-03-28 17:12
This is fixed in the latest beta (2.38.0)

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Closed by michaelkirk-signal** 2019-03-28 17:12 UTC
