### ISSUE TITLE
disappearing messages should also apply to calls history

### ISSUE THREAD

**Issue by arekm** [signalapp/Signal-iOS#3672] opened 2018-07-07 08:19 UTC
### Bug description

Currently when disappearing messages are turned on for conversation messages do disappear but calls history doesn't not. That doesn't look good and isn't consistent IMO.

**Actual result:** Calls history stays for ever.

**Expected result:** Calls history should disappear according to disappearing messages setting.

### Screenshots

![not-expiring-calls](https://user-images.githubusercontent.com/50869/42408628-3914fe50-81cf-11e8-9584-93edcc09142b.png)

### Device info
**Device**: iphone 7 plus
**iOS version**: 11.4
**Signal version:** 2.27.1.4

**Comment by 2-4601** [comment] 2018-07-08 11:15
Duplicate of #2060

**Comment by PeterWulff** [comment] 2018-07-19 07:01
Yes, it is a duplicate of #2060.
But what happened in #2060? Someone mentioned this behavior of the disappearing messages within Signal, which obviously makes no sense for anyone. The screenshot of arekm shows this and anyone using Signal also for phone calls, is annoyed by this. For years now!
A team of talanted programmers, who work on a project they are really involved in and would like to push it, would not even waste the time of arguing or writing an answer. They would see at once, that this behaviour makes no sense at all, and try to fix it as soon as possible.
And what happened? michaelkirk simply wrote "this is working as intended", relegated to the signaluser community (where you can make suggestions for years and nothing will happen) and closed the ticket.
This is the behavior of a bureaucrat, and such people will never really push a project successfully.
I believe, the Signal project should try to find a more dedicated programmer, who is really focussed on improving the app. The ios version of Signal is not really improving for 2 years now and is too far behind the android version.

**Comment by M09NST3R** [comment] 2021-04-16 17:24
Any updates on this? Seems like a concerning privacy-compromising bug that has been reported already 4 years ago and shouldn't be terribly difficult to fix.

**Comment by foss-** [comment] 2022-01-24 10:45
Post to remove wontfix label. This problem is persisting.

**Comment by foss-** [comment] 2022-03-25 13:10
Still relevant

**Comment by kaktusztea** [comment] 2022-04-01 12:20
Still an issue.

**Closed** 2022-04-08 12:25 UTC
Labels: wontfix

**Comment by foss-** [comment] 2022-04-08 12:34
Uhg and now closed the bug 👀

**Comment by kaktusztea** [comment] 2022-04-08 12:41
It looks like you can keep alive with comments even though if Stale bot (for some reason) doesn't remove the label after commenting.
In that case it will close 1 week after the last comment.

**Comment by xanoni** [comment] 2022-05-03 01:23
Think still a problem
