### ISSUE TITLE
Sleep Button Ends Calls

### ISSUE THREAD

**Issue by khashyarkh** [signalapp/Signal-iOS#2915] opened 2018-01-09 15:44 UTC
the call gets ended if you push the Sleep Button.

**Device**: iPhone 6S
**iOS version**: 11.2
**Signal version:** 2.19.3

**Comment by NinebitX** [comment] 2018-01-09 22:01
Is this a duplicate of https://github.com/WhisperSystems/Signal-iOS/issues/1168?

**Comment by NotARealUsernamee** [comment] 2018-01-20 00:12
That's normal on iOS unless you put the call on speaker first.

**Comment by michaelkirk** [comment] 2018-01-30 02:42
> the call gets ended if you push the Sleep Button.

This is indeed iOS behavior, and not something we can do anything about. Unless you have headphone or speakerphone plugged in, iOS interprets locking as a hangup.

**Closed by michaelkirk** 2018-01-30 02:42 UTC

**Comment by mailinglists35** [comment] 2020-06-30 11:11
> @michaelkirk commented on Jan 30, 2018 •
edited
>This is indeed iOS behavior, and not something we can do anything about. 

Please reopen. This never worked on Signal, not even on speaker.

This is not enforced by iOS. This is 100% in control of iOS app.

The reason we press the sleep/wake button is to lock the screen and turn it off to prevent accidental taps while talking.

Have a look at [jitsi](https://apps.apple.com/us/app/jitsi-meet/id1165103905) for example, you can press sleep/power button and the conversation keeps going.

**Comment by readstead** [comment] 2022-06-27 09:12
Extremely annoying. Same issue as #4167, which has more visibility.
