### ISSUE TITLE
Can not delete Link/URL only message

### ISSUE THREAD

**Issue by vijaynikam** [signalapp/Signal-iOS#4668] opened 2021-01-09 01:37 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can not delete message if message body has link/URL as only text.

### Steps to reproduce
- copy and paste any link as a message
- send message
- try deleting sent message

**Actual result:** Instead showing usual options like emojis, forward, delete etc.. you only see link related options i.e. Copy link, Open Link etc..

**Expected result:** All other generic options 

### Device info

**Device**: iPhone XR

**iOS version**: 13.4.1

**Signal version:** 5.0.3

**Comment by Fondor1** [comment] 2021-01-09 02:17
I have the same Signal version, but an iPhone SE running 14.2.

I am able to long-press on the checkmark delivery status of the message, not on the link text itself, to delete the message. Are you able to click the (understandably small) checkmarks to pop open the correct menu?

**Comment by sertsedat** [comment] 2021-01-09 12:41
You can also long press on the empty space to the left or to the right of the message to get the context.

**Comment by Himanshu-998** [comment] 2021-01-09 14:03
I am using signal 5.0.3 on iPhone XR  iOS 14.3 and I am seeing the delete option. It is working fine for me.

**Comment by vijaynikam** [comment] 2021-01-09 23:07
Thanks, It worked after few tries.. clicking on delivery status however it's really difficult to use that tiny area for selection and it's not very intuitive. Also for some reason it doesn't work all times.

**Comment by Genis-Sage** [comment] 2021-01-11 10:02
hey @vijaynikam 
this is a duplicate of #849 , or at least a related issue to that,
because the main issue is the selection part

**Closed** 2022-01-31 07:47 UTC
Labels: wontfix
