### ISSUE TITLE
Deleted groups are still searchable

### ISSUE THREAD

**Issue by BionicBison05** [signalapp/Signal-iOS#5250] opened 2022-01-24 00:13 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Groups that I have left and deleted are still searchable, along with all their previous members. This seriously pollutes search results

### Steps to reproduce
- Join a group [(like the mobile coin group)](https://signal.group/#CjQKIFg2P0aasMR0eytD-_YRP7X9k739V_jUVdW3PJ3O1_rrEhBETJmx-sZfv97sAiFs-vF5)
- Leave the group and delete it
- Observe that when creating a new message, you can still search for members of the group and the group itself

**Actual result:** Group and members appear when searching in the new message prompt

**Expected result:** Group and members are nowhere to be found, as the group was left and deleted.

### Screenshots
![image](https://user-images.githubusercontent.com/93722725/150703931-2b22abf4-90e7-476a-8653-6ac4790b65c0.jpeg)

### Device info

**Device**: iPhone 12

**iOS version**: 15.2.1

**Signal version:** 5.26.10.0

### Link to debug log

https://debuglogs.org/e1777616eb081d62ee206b644ec9a5c3bba351c3d320e1d202bfd5007fa391e0.zip

**Comment by halo** [comment] 2022-01-25 13:15
This appears to be a duplicate of https://github.com/signalapp/Signal-iOS/issues/4542

**Closed** 2022-04-02 17:01 UTC
Labels: wontfix
