### ISSUE TITLE
Non standard Latin letters replaced

### ISSUE THREAD

**Issue by pardahlman** [signalapp/Signal-iOS#3485] opened 2018-05-29 05:04 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My messages on Signal usually contains some none standard, Latin letters: _å_, _ä_ and _ö_. Every once in while (I would say more often than 2 times out of 100) the sent message is changed so that these letters are replaced with _a_, _a_ and _o_.

### Steps to reproduce
I haven't found a deterministic way to reproduce this, I haven't found any patterns as to whom I'm sending a message. I haven't noticed this problem with the desktop version (mac and Windows).

### Device info
**Device**: iPhone X

**iOS version**: 11.3.1

**Signal version:** 2.25.1.1

**Comment by tzs1** [comment] 2019-03-28 18:44
I have tried with multiple non-standard letters and I never experienced any issue (iOS and Desktop).

**Comment by lanurmi** [comment] 2021-05-05 06:39
This is happening to me on iOS 14.4.2, with Signal 5.11.0.26. And much more often than 2 times out of 100.

I haven't figured out a pattern either, but it could be related to having emojis in the same message.

Also, I should not that _å_, _ä_ and _ö_ are not "non standard"; they are part various standards, including the Unicode standard, which should suffice.

**Comment by lanurmi** [comment] 2021-05-31 09:20
The issue is 100% reproducible when the emoji 👩‍❤️‍💋‍👨 ("Kiss: Woman, Man") is present in the message body. @pardahlman Can you confirm this?

**Comment by lanurmi** [comment] 2021-06-01 21:10
Just to add simple steps to reproduce:

1. I write a message containing the emoji and letter Ä, for example: `👩‍❤️‍💋‍👨 Ä`
2. The message will now show as `👩‍❤️‍💋‍👨 A` on both my screen and on the receiver's screen. The Ä lost its diacritics and became A.
3. Both me and the receiver are using Signal on iOS (on iPhone, iOS 14).

In my experience the letter might as well be á, é, ö, whatever with diacritics/accents, the issue is not specific to the capital Ä.

**Comment by pardahlman** [comment] 2021-06-02 17:42
Yes, I could reproduce this by following the steps above, sending to myself (the "Notes to self" feature)  iOS 14.4.2 / Signal 5.13.0.33

**Comment by faern** [comment] 2021-08-29 13:18
This is also 100% reproducible with all emojis of a family of four (👨‍👩‍👧‍👧, 👨‍👨‍👧‍👧 etc..) but not with the family of three or two emojis. So an example of a message that always breaks is:

> 👨‍👨‍👧‍👧 åäö

The text looks good when you input it in the text field. But if you tap back to the conversation list (essentially making it a draft) and go back to the conversation again, it has lost all its diacritics. The same happen if you send the message. It will show up without diacritics on my device and the receiver's.

This bug does not exist on Android. But if an Android signal user sends me one of the broken messages, "👨‍👨‍👧‍👧 åäö", it will show up as "👨‍👨‍👧‍👧 aao" on my iOS device.

**Comment by faern** [comment] 2022-01-23 10:07
Yes. This is still a bug on latest Signal for iOS.

**Comment by soulman-hh** [comment] 2022-01-24 06:21
I can confirm that. The bug is still existing. If I send or receive messages containing one of the emojis mentioned above (most often it is the 👩‍❤️‍💋‍👨, what is good for me that I receive this so often), characters like ä, ö, ü are replaced by their "normal" characters (a, o, u). This happens with all special characters and also with other emojis.

Signal Version 5.26.10.0
iOS version 15.1

**Comment by faern** [comment] 2022-03-25 08:37
Yes. This bug still exists on latest signal, version 5.33.0

**Comment by soulman-hh** [comment] 2022-03-25 09:04
Again, I can confirm that. Still not fixed.

**Comment by faern** [comment] 2022-05-24 12:24
Yes, this is still a bug in Signal 5.38 from App Store.

**Comment by soulman-hh** [comment] 2022-05-24 13:48
Very annoying for all users using non standard characters. Still not fixed after nearly 4 years. :-(

**Comment by lanurmi** [comment] 2022-05-24 15:37
> Very annoying for all users using non standard characters. Still not fixed after nearly 4 years. :-(

I don't think this will ever get fixed, unless someone knows the right people to contact.

**Comment by soulman-hh** [comment] 2022-06-04 07:56
> > Very annoying for all users using non standard characters. Still not fixed after nearly 4 years. :-(
> 
> I don't think this will ever get fixed, unless someone knows the right people to contact.

That was a very good idea. I contacted a contributor from Germany ... and, tataaaa, he made a bugfix already. It will take a while, but finally something happens.

**Comment by soulman-hh** [comment] 2022-08-15 09:10
Today, I received the first message with one of the affected emojis and correct non-standard Latin letters!

A big applause and many, many thanks to [Martin](https://github.com/mboe-signal) for making the life of so many Signal users better!

**Comment by faern** [comment] 2022-08-15 11:12
Works here as well! :partying_face: Thanks!

**Comment by lanurmi** [comment] 2022-08-15 11:21
Seems to be working indeed. I wonder what/where is the commit that fixed it.

**Comment by soulman-hh** [comment] 2022-08-19 07:36
If someone from the Signal team is reading this:
**The bug has been fixed** in iOS Signal 5.48.0.8 (I think it was that version, anyhow this is the version that I have now on my iPhone now).
It only affected iOS, so **this issue can be closed**.

Many, many thanks again to [Martin](https://github.com/mboe-signal) for taking care of that!

**Comment by EvanHahn-Signal** [comment] 2022-08-25 14:46
I believe this was fixed in https://github.com/signalapp/SignalCoreKit/commit/2f866beb00634e4f5cc712429b176a563feb76df (not sure). Closing because this has been resolved!

**Closed by EvanHahn-Signal** 2022-08-25 14:46 UTC
