### ISSUE TITLE
Signal 5.3.71 - 5.42.0 Crashes on Launch on iPhone 6

### ISSUE THREAD

**Issue by MikaChanSA** [signalapp/Signal-iOS#5344] opened 2022-05-09 19:47 UTC
I'm not sure if this is a duplicate given that there have been similar reports for different iPhone models but those appear to have been fixed in the latest update. The app still seems to crash on launch on iPhone 6 though. The latest version of iOS available for iPhone 6 is 12.5.3 if that has anything to do with it.

Debug log: https://debuglogs.org/ios/5.37.1/7b8621263626c768ca30394cda9181dc65f46c6e5c654565f79f7d39a0d0db78.zip

I've been sideloading my dumped version of 5.35.2 in order to continue using the app.

**Comment by jrose-signal** [comment] 2022-05-11 17:39
If you get the chance, can you attach your [crash report](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug) as well? You can also see if the upcoming 5.37.2 fixes your issue—we identified a crash-on-launch that could have affected you in updating from 5.35.2.

**Comment by jrose-signal** [comment] 2022-05-11 17:44
(Checked and this does seem to be distinct from #5343, but there were two fixes in 5.35.2 and this is liekly to be the other one.)

**Comment by MikaChanSA** [comment] 2022-05-12 01:15
Still not fixed in 5.37.2. I get a message saying "couldn't open Signal" that offers to submit a debug log or "open signal instead". selecting open instead leads to a crash.

Debug log: https://debuglogs.org/ios/5.37.2/3abd61c9e9095f0d7b6edfe8b5855b6d59a3e1ee806aad48538cfc6242837583.zip

**Comment by jrose-signal** [comment] 2022-05-12 17:22
Darn. OS crash report would still be appreciated. Sorry for the trouble!

**Comment by MikaChanSA** [comment] 2022-05-17 12:29
> Darn. OS crash report would still be appreciated. Sorry for the trouble!

I've managed to generate a crash report! 

Please note that though my phone is jailbroken, the error occurs when the jailbreak is disabled as well
[Signal-2022-05-17-142419.zip](https://github.com/signalapp/Signal-iOS/files/8708200/Signal-2022-05-17-142419.zip)
.

**Comment by MikaChanSA** [comment] 2022-05-17 12:36
Here is a crash report generated in a non-jailbroken state: 
[Signal-2022-05-17-143411.zip](https://github.com/signalapp/Signal-iOS/files/8708270/Signal-2022-05-17-143411.zip)

**Comment by jrose-signal** [comment] 2022-05-17 19:06
Thank you! We've been investigating some other remaining issues in this area, but yours doesn't exactly match any of them. We'll keep working on this.

**Comment by highway900** [comment] 2022-05-18 06:19
I can confirm this issue with iPhone 11, iOS 15.4.1 and signal 5.37.2. Application opens very briefly and then crashes. I am unable to get a debug log, I get an error saying "could not find any logs".
Not sure if I should open another issue, I recently had my phone repaired and part were replaced and now the phone is stuck power cycling every 5mins or so, it does not seem correlated but thought I best mention it just in case.

**Comment by jrose-signal** [comment] 2022-05-18 17:19
@highway900 if you have crash reports we'd like to see them as well, but if the phone is power cycling that often it wouldn't surprise me if they're not getting saved properly by the OS. :-( Otherwise the best I can suggest right now is to try 5.38 when it comes out.

**Comment by MikaChanSA** [comment] 2022-05-20 01:19
Unfortunately, this particular crash still hasn't been fixed in 5.38.0 but thank you for being so responsive! Hopefully we can get to the bottom of this soon.

**Comment by highway900** [comment] 2022-05-20 02:23
Thanks for the update @jrose-signal but I can confirm with @MikaChanSA that this issue is not resolved with 5.38.0 for me either. I am still unable to submit debug logs. Signal crashes instantly.

**Comment by jrose-signal** [comment] 2022-05-20 17:29
@highway900 I do want to be clear that I'm asking for the [*OS* crash reports](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug), if present, not debug logs!

**Comment by MikaChanSA** [comment] 2022-05-20 17:48
@highway900 I think you might be experiencing a different issue to mine because I'm able to submit debug logs but not to briefly open the app, which doesn't launch at all. @jrose-signal included a link explaining how to share iOS crash reports in his first response to this issue.

**Comment by highway900** [comment] 2022-05-21 23:54
Ah yes my bad, apologies for not paying enough attention to the difference.
I agree it is likely my issue is different, I have sent through the iOS
crash logs to support email address. Thanks for the help everyone. I will
open a new issue.

**Comment by EvanHahn-Signal** [comment] 2022-11-30 17:00
Closing because it's been marked stale for 2 months.

**Closed by EvanHahn-Signal** 2022-11-30 17:00 UTC
