### ISSUE TITLE
Only one photo from those selected is being sent

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3147] opened 2018-03-18 18:25 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
If I go to photo app in iOS and I select more than 1 photo for example 3 and send them with Signal, only one of those is sent

### Steps to reproduce
- open photos app
- select at least 2 photos, and send them through Signal
- open Signal and you will see that only one of those has been sent

**Actual result:** Only one photo has been sent
**Expected result:** all photo should be sent

### Device info

**Device**: iPhone 6s
**iOS version**: 11.3
**Signal version:** 2.23.0.14

### Link to debug log

https://debuglogs.org/56daf602cb7115b8c918cba85da605b8c00a0a598e94a3a7ea06d81811c19c94.zip

**Comment by ebelinski** [comment] 2018-03-23 20:30
I can confirm that this is an issue for me as well, and I don't think it's a duplicate of #2890 or #858.

### Bug description
It is possible to select multiple images in the Photos app and share them via Signal, but only the first image is actually sent. If you select an image in your camera roll from within Signal, you can only select one. But this doesn't prevent a user from selecting multiple images in the Photos app, then sharing to Signal.

### Steps to reproduce
- Open the Photos app.
- Select 2 or more images.
- Tap on the share button at the bottom-left and select Signal in the middle row.
- Select the user to share with.
- Tap 'Send' at the bottom-right.

**Actual result:** Only the first image I selected is sent.
**Expected result:** All of the images I selected should have been sent. 

### Device info
**Device**: iPhone 7
**iOS version**: 11.2.6
**Signal version:** 2.22.0.4

**Comment by rex4539** [comment] 2018-08-09 10:32
It’s time this bug gets fixed. This is a major inconvenience.

**Comment by thennarasug** [comment] 2018-10-31 06:45
expecting an update on this feature soon.

**Comment by NinebitX** [comment] 2019-01-25 15:52
This issue is now fixed in version 2.34.0.

**Comment by Tlamatinime** [comment] 2019-04-01 08:45
@michaelkirk-signal you can close this issue.

**Closed** 2019-04-01 20:12 UTC
