### ISSUE TITLE
Reactions are not accessible with Voiceover

### ISSUE THREAD

**Issue by heull001** [signalapp/Signal-iOS#5497] opened 2022-12-02 16:31 UTC
Reactions on Messages are not accessible with Voiceover. The Lockscreen-Notification is accessible, but in the App there is no ability to get access.

**Comment by heull001** [comment] 2023-03-03 08:39
This problem is not solved yet.

**Comment by cannona** [comment] 2023-04-08 01:11
Can confirm. It is not possible to hear the reactions on messages when using VoiceOver.

**Comment by cannona** [comment] 2023-07-09 16:33
This issue should remain open, as it does not appear to have been resolved
in the latest production version.

**Comment by Miguel-Signal** [comment] 2023-07-19 15:31
@cannona @heull001 Could you please update to the [latest version of Signal](https://apps.apple.com/us/app/signal-private-messenger/id874139669) and see if this resolves the issue? Then, if the issue is still happening, could you write in to support@signal.org with your debug logs from this new version?

To share a debug log from Signal iOS, tap your profile Profile Avatar, Settings, Help, Submit Debug Log, Copy Link, then open this email, long-press and choose paste to paste the link.

**Comment by DGrothe-PhD** [comment] 2023-09-13 21:52
Can confirm the issue on ios 16.6.1

**Comment by marissa-signal** [comment] 2023-12-08 21:48
Hi - This will be fixed in app version 6.54, which will go to beta next week.

**Closed by marissa-signal** 2023-12-08 21:48 UTC
Labels: Acknowledged
