### ISSUE TITLE
signal _false

### ISSUE THREAD

**Issue by arturoiam** [signalapp/Signal-iOS#4454] opened 2020-05-16 15:30 UTC
[](https://debuglogs.org/c19cbda1bf8dfc6f048ce0141b6a4da11b51e689249ea3f5d65661eef997f21f.zip)

**Comment by arturoiam** [comment] 2020-05-17 05:41
Send to end

**Comment by Genis-Sage** [comment] 2020-05-26 07:59
hey @arturoiam 
what is your issue about?

please fill out the issue template, or close the issue:
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device**: iDevice X

**iOS version**: X.Y.Z

**Signal version:** Z.Y

### Link to debug log

**Closed** 2020-06-02 19:22 UTC
