### ISSUE TITLE
Feature request - Password protection for Desktop app

### ISSUE THREAD

**Issue by venfawkes** [signalapp/Signal-iOS#4320] opened 2019-12-02 03:56 UTC
Hello,

There is not really much more needed to say about this feature suggestion as it should be very straight forward.

I'm unsure if and how Singal currently stores conversations and related media securely on PC, without the need of an input.

Additionally, it would be good to have a few additional options for this, such as a time-out lock.

**Comment by michaelkirk-signal** [comment] 2019-12-04 16:13
Hi @venfawkes - you've posted in the iOS issue tracker, but it sounds like you're talking about Signal Desktop, which lives here: https://github.com/signalapp/Signal-Desktop

Also, this sounds like a dupe of the existing Desktop issue: https://github.com/signalapp/Signal-Desktop/issues/1895

**Closed by michaelkirk-signal** 2019-12-04 16:13 UTC

**Comment by venfawkes** [comment] 2019-12-04 18:55
You are 100% correct. Just noticed I posted in completely wrong section.
