### ISSUE TITLE
Bypass screen lock 

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3224] opened 2018-04-03 16:41 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Bypass screen lock

### Steps to reproduce
- open the app
- Click cancel 
- click home button 
- open app and u get in without passcode

**Actual result:** Diesnt ask passcode
**Expected result:** Should ask passcode

### Device info

**Device**: iPhone 6s
**iOS version**: 11.3
**Signal version:** 2.23.0.14

**Comment by leonardoporpora** [comment] 2018-04-03 16:42
Debug log: https://debuglogs.org/785f6cd444069b46bae5dc8b5f763db536e9d84216a9d0bd7deb8e9b44eeb757.zip

**Comment by leonardoporpora** [comment] 2018-04-03 16:42
I made a video if you want I can send you

**Comment by michaelkirk-signal** [comment] 2018-04-03 16:46
I can't reproduce this. What is your screen lock timeout set to?

Keep in mind, we re-use biometric auth if it just happened. So if you've just unlocked your phone with your thumb a few seconds before, we don't redundantly ask you again when launching Signal.

Can you reproduce this behavior with the following:

- Switch hands so as not to inadvertently auth with TouchID
- Launch Signal
- See screen lock (as expected)
- Cancel alert, hit home button (with non TouchID hand!)
- You're now on your iOS home screen
- Launch Signal
- See screen lock (as expected)
- Signal launches and you see the Signal inbox without the lock screen

**Comment by leonardoporpora** [comment] 2018-04-03 16:48
I will send you a video for PoC where should I send it?

**Comment by michaelkirk-signal** [comment] 2018-04-03 16:49
You can send it to support@signal.org, please reference this issue URL.

**Comment by michaelkirk-signal** [comment] 2018-04-03 16:50
Can you also answer my questions?

> What is your screen lock timeout set to?


Can you reproduce this behavior with the following:

- Switch hands so as not to inadvertently auth with TouchID
- Launch Signal
- See screen lock (as expected)
- Cancel alert, hit home button (with non TouchID hand!)
- You're now on your iOS home screen
- Launch Signal
- See screen lock (as expected)
- Signal launches and you see the Signal inbox without the lock screen

Unless the video shows your hands it's not going to be the helpful.

**Comment by leonardoporpora** [comment] 2018-04-03 16:53
I sent the video. The screen lock was set to 15 minutes than I tried also with one minute. I don’t use touchID I use passcode as you will be able to see in the video I sent right now

**Comment by jkic** [comment] 2018-04-03 18:59
I am able to reproduce this as well by following [the recommended steps](#issuecomment-378319276), both with Touch ID enabled and with Touch ID disabled, with a one-minute timeout, using Signal 2.23.0.14 on iOS 11.3. (The second to _last_ step, “See screen lock (as expected)” seems like a copy/paste mistake, so I’ve ignored it).

I noticed something else that may be helpful in finding the source of the problem (if I should file it as a separate issue, please let me know). Steps:

 1. Set the “Screen Lock Timeout” to anything but “immediate”
 2. _Quit_ the app
 3. Immediately start Signal again

In this scenario, the “Screen Lock” is displayed, even though it’s far from reaching the end of the timeout.

It didn’t surprise me that if I cancel the “Screen Lock”, leave Signal and switch back to it, I am not bothered by the “Screen Lock” again. That the “Screen Lock” is displayed _at all_ the first time is what is unexpected.

I originally thought that _this_ was the real problem, but as I said, I am able to consistently reproduce the problem as originally described.

Unless I set the “Screen Lock Timeout” to “Immediate,” it would appear the “Screen Lock” is not enforced for me.

**Comment by leonardoporpora** [comment] 2018-04-04 12:29
@michaelkirk-signal I sent also the PoC of bypass with touchID and the phone that I used was not mine and there wan none of my fingers memorized in it :+1:

**Comment by michaelkirk-signal** [comment] 2018-04-04 14:46
Fixed in #3235, thanks for the report

**Closed by michaelkirk-signal** 2018-04-04 14:46 UTC
