### ISSUE TITLE
Chat opened from notification is not scrolled to bottom

### ISSUE THREAD

**Issue by igorkulman** [signalapp/Signal-iOS#4186] opened 2019-05-03 16:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When you open a chat from a push notification, the list of messages is not scrolled to bottom the same way when you open a chat from the main screen

### Steps to reproduce
- Receive a push notification for a new message in a chat
- Tap the notification so Signal opens showing the chat

**Actual result:** The chat should is not scrolled to bottom but to some place above or in the middle of the latest message

**Expected result:** Chat scrolled to the bottom the same way when you open a chat from the main screen

### Device info

**Device**: iPhone 6S

**iOS version**: 12.2

**Signal version:** 2.38.1

**Comment by philshem** [comment] 2019-05-05 19:19
I think this is a duplicate of this issue: https://github.com/signalapp/Signal-iOS/issues/4185

Is it all chats, or group chat only?

Is there any messages about verifying safety numbers?

**Comment by igorkulman** [comment] 2019-05-05 19:32
Definitely not a duplicate, this happens to me in 1:1 chats, no verifications messages displayed.

**Comment by philshem** [comment] 2019-05-06 06:35
I suspect it’s related, and the big can occur under various conditions. Let’s see what the devs say.

**Comment by drozzy** [comment] 2019-05-10 18:24
Same issue. Signal never remembers the place the conversation was. 
This started happening since a few updates ago.

**Comment by seveke3** [comment] 2019-06-01 07:10
Same issue here. Only it happens just in 1 chat (group) and all the time, also if I open it with the app (not the notification). All the other chats don’t have that problem (group and individual).

**Comment by drozzy** [comment] 2019-06-03 17:34
Seems to have been fixed **after** I deleted the mid-chat system notification of the verification code change.

**Comment by thegesuser** [comment] 2019-06-05 15:51
Same issue. 
And when trying to scroll to that new message, it jumps to 5-6 messages above.

**Comment by blapcity** [comment] 2021-06-21 01:01
Still having this issue. My OS and app are all updated. I've also tried reinstalling.

**Closed** 2022-01-30 15:46 UTC
Labels: wontfix
