### ISSUE TITLE
Group call feature

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3010] opened 2018-02-15 09:03 UTC
Add group call feature. But I don’t have to be obliged to have created a group I would like to simply call someone and once I am in the call add other people to this call

**Comment by NinebitX** [comment] 2018-02-15 15:20
Dupe of https://github.com/signalapp/Signal-iOS/issues/1804

**Comment by michaelkirk** [comment] 2018-02-15 17:12
closing as dupe of #1804

@leonardoporpora - please search for existing issues and follow the issue template if you're going to post here again.

(thanks @NinebitX)

**Closed by michaelkirk** 2018-02-15 17:12 UTC
