### ISSUE TITLE
[Req]

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-iOS#3181] opened 2018-03-25 16:31 UTC
Give the possibility to share a contact with signal.
1 enter in Phone app
2 go to Bob contact
3 slide down to share contact
4 add the possibility to share this contact through signal

**Comment by michaelkirk** [comment] 2018-03-25 18:06
dupe of https://github.com/signalapp/Signal-iOS/issues/3062

**Closed by michaelkirk** 2018-03-25 18:06 UTC
