### ISSUE TITLE
Signal freezes when i open a group

### ISSUE THREAD

**Issue by monicacalcagnini** [signalapp/Signal-iOS#3907] opened 2018-09-25 08:42 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal freezes when i open a group

### Steps to reproduce
I dont know

**Actual result:** Group doesnt open

**Expected result:** Group should open 

### Device info

**Device**: iDevice X

**iOS version**: 12

**Signal version:** latest

### Link to debug log

https://debuglogs.org/b433b5e886001268a479904194e77bb162943ffaedfa52218523109645f5a4ab.zip

**Comment by michaelkirk-signal** [comment] 2018-09-25 19:02
Does it freeze forever, forcing you to kill the app? Or does it, after several seconds eventually show you the group conversation?

**Comment by monicacalcagnini** [comment] 2018-09-25 19:55
I used to kill it and once reopened it the issue persisted, so right now i have no access to that hroup

**Comment by michaelkirk-signal** [comment] 2018-09-25 21:48
Can you try something for me?

Open Signal
Tap on the conversation in question
Count to 10

Did the conversation eventually load?

Regardless, can you submit a new debug log right after doing the above?

**Comment by michaelkirk-signal** [comment] 2018-09-25 21:50
If it does eventually load, it's likely a dupe of https://github.com/signalapp/Signal-iOS/issues/3907

Your logs indicate that you're having at least this issue, but you might additionally have another issue.

**Comment by Mihahn** [comment] 2020-12-11 16:58
Can't reproduce, is this still an issue? If not, please close your issue.

**Closed** 2022-01-31 10:47 UTC
Labels: wontfix
