### ISSUE TITLE
Signal state gets confused when accepting a picture from iOS "send to"

### ISSUE THREAD

**Issue by wdormann** [signalapp/Signal-iOS#3993] opened 2018-11-07 03:25 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal exposes itself as a recipient of "send to" capabilities in iOS.  For example, when viewing a picture, you can send it to Signal, where you can select a recipient to send it to.  The problem is that when using this capability, an already-running Signal instance seems to get confused about its state.  Symptoms include:
 - Signal doesn't show the picture you just sent
 - Signal doesn't show a message you just received 
 - Signal crashes.

### Steps to reproduce
- Have Signal open, and in a conversation with a contact.
- Switch to iOS Photos
- Share a picture to Signal, and select the current-conversation recipient
- Switch back to Signal
- Continue the conversation

**Actual result:** 
The picture that you just sent is often not present in the existing conversation.  Continuing the conversation often results in Signal crashing.

**Expected result:** 
The picture you sent is there, in the relevant position in the conversation thread.  Continuing the conversation doesn't result in a crash.

### Device info

**Device:** iPhone 6s
**iOS version:** 12.1
**Signal version:** 2.30.2.16

**Comment by cmr** [comment] 2018-11-07 19:07
I’ve only observed this with photos, never sharing text.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by huyachao** [comment] 2018-11-27 05:02
I can confirm the bug with the latest ios version.
Device info
Device: iPhone 8
iOS version: 12.1
Signal version: 2.31.0.39

**Comment by huyachao** [comment] 2018-12-03 07:13
It looks that the bug has been fixed in latest stable release 2.31.1.3.

**Comment by huyachao** [comment] 2018-12-04 01:09
Sorry, after upgrading to 2.31.2.0 this morning, I reproduced it again. -_-

**Comment by huyachao** [comment] 2018-12-14 07:12
Reproduced in 2.32.0.23

**Comment by michaelkirk-signal** [comment] 2019-01-18 16:50
Are any of you who are experiencing this behavior when sharing images to Signal on the iOS Beta?

We've just released 2.34.0 to our Beta community, which includes some changes that should address this. Let us know how it goes!

https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by wdormann** [comment] 2019-01-18 18:51
After a few test messages to myself, it seems OK so far.  With the Test Flight version, after sending a picture to myself (via the send-to option from iOS Photos, and then switching back to Signal:
1) The picture isn't there automatically.
2) Upon sending additional text, the picture appears before the text I just sent.  I believe this is where the prior signal would have crashed.

Given the intermittent behavior of this crash, time will tell if it's truly fixed.  But so far so good...

**Comment by michaelkirk-signal** [comment] 2019-01-19 02:07
> After a few test messages to myself, it seems OK so far. With the Test Flight version, after sending a picture to myself (via the send-to option from iOS Photos, and then switching back to Signal:

To clarify @wdormann  - you're saying it's somewhat improved in that the app is no longer crashing after sharing, but you're *still* not seeing the shared image appear until after you send another message from *within* the main app?

**Comment by wdormann** [comment] 2019-01-19 15:53
Sorry, I should have ben more clear.   Steps to reproduce:

1. Send a picture from iOS Photos to a Signal recipient.
2. Wait a minute or two so that iOS unloads Signal from memory again. (This is important)
3. Launch signal and open that same Signal thread.
4. Send a text message.

With old Signal:
With step 3., Signal doesn't show the picture you sent from Photos.
With step 4., Signal crashes.

With Test Flight Signal:
With step 3., Signal doesn't show the picture you sent from Photos.
With step 4., Signal loads the picture you sent from Photos into the thread, in the proper location.


So, as far as the crash is concerned, this appears to be fixed.  The current behavior of step 4. where the picture doesn't appear until you start typing is a tad confusing.  But the important part (the crash) looks to be addressed.

**Comment by denver-s** [comment] 2020-02-06 20:17
I cannot reproduce this bug. Version 3.4.0.7

**Comment by wdormann** [comment] 2020-02-06 20:37
I can no longer reproduce this either.  I suspect it was addressed in the 1+ years since I reported it.

**Comment by Mihahn** [comment] 2020-02-06 22:29
> I can no longer reproduce this either. I suspect it was addressed in the 1+ years since I reported it.

If the issue is fixed, feel free to close it - this helps to keep the issue tracker clean!

**Closed** 2020-02-07 02:45 UTC
