### ISSUE TITLE
iOS 7.26 critical bug: I can no longer send messages!

### ISSUE THREAD

**Issue by Jamo33** [signalapp/Signal-iOS#5860] opened 2024-08-31 10:40 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since updating to 7.26, sending any message from within the app causes the message to be instantly deleted. No message is sent. However, if i share an image or link with signal, the message does get sent! 

### Steps to reproduce
- type message
- press send

**Actual result:** message deletes itself (see video attached)

**Expected result:** message would send as per usual

### Screenshots

https://github.com/user-attachments/assets/22481f24-86ea-4597-9dba-a21484124f06

### Device info

**Device**: iPhone 14 Pro Max

**iOS version**: 17.6.1

**Signal version:** 7.26

### Link to debug log

https://debuglogs.org/ios/7.26.0/e75bb92aef642e5f93facb277a50aef57d2926b5d385031bf27ca75462e29e3f.zip

**Comment by Jamo33** [comment] 2024-08-31 10:52
Also interesting secondary bug to note is that i can view a message but when i return to the main menu it shows the message as unread. See video:


https://github.com/user-attachments/assets/cb05d337-a542-44a2-9bc3-8fe57af21a80

**Comment by Jamo33** [comment] 2024-08-31 17:24
I just noticed that I can get it to send messages if i share a photo or link from an external app.

**Comment by mfsen10** [comment] 2024-08-31 17:32
Similar issues as above, the donate notification can't be dismissed and cannot open any threads nor create new threads or anything. Strangely sometimes it will respond and enter a thread but mostly just unresponsive.

**Comment by Jamo33** [comment] 2024-08-31 19:20
This issue resolved itself! Not sure how.

**Comment by Achom852** [comment] 2024-09-01 06:34
@Jamo33 can you estimate how long it took to self resolve or if you did anything that might trigger that?

I have the same issue, I suspect the donate notification, as I cannot dismiss it neither can I actually donate.
And as of now it exists

**Comment by Jamo33** [comment] 2024-09-01 07:33
It took about 48 hours to fix itself. Nothing i did had any effect -
including offloading the app and reinstalling it. If you haven’t tried that
i suggest you do (it’s not the same as deleting it, because it keeps all
your chats safe).

Regards,

Jamie Allen

**Comment by jindro33** [comment] 2024-09-01 11:27
I'm reporting that the problem is present - my current exp:
- started somewhere after update to 7.26 (yesterday, afternoon), iPhone Xs, iOS 17.6.1
- symptoms like reported by @Jamo33 + : 
* outgoing calls are not being connected/reported to receivers, but you can hear a connection signal
* receiving calls works (2 times already, re-testing again)
* app crashes on: 
donate pop-up -> cancel = crash/frozen; donate = donate options/frozen; 
stories -> crash/frozen
contact us -> crashed twice after pressing next, on the 3rd try it transferred to the mail app; on 4th try it crashed again,
* app receives occasional messages if closed (notification is visible and readable), but they can't be recognised as read once I open the app; outgoing messages sent from desktop app are being downloaded only after closing the app

Tested: standard on/off, restarting, wi-fi/mobile, VPN/no-VPN, etc.

**Comment by jindro33** [comment] 2024-09-01 13:16
@Jamo33 please reopen the issue, since it's not solved.

**Comment by Jamo33** [comment] 2024-09-01 13:36
Issue reopened as requested

**Comment by jindro33** [comment] 2024-09-02 06:39
Adding my debuglog:

[org.whispersystems.signal 2024-08-31--19-12-57-088.log](https://github.com/user-attachments/files/16833159/org.whispersystems.signal.2024-08-31--19-12-57-088.log)

**Comment by Xovval** [comment] 2024-09-02 08:29
I can affirm this bug with the addition that it did not resolve itself after 48 hours on my device. (iPhone 13, iOS 17.6.1, App Ver: 7.26)

If not already happened, I would propose to add a "critical" tag to this issue, as the app is pretty much unusable at this point.

**Comment by seheyah** [comment] 2024-09-02 08:32
Hi team, I also have this issue describe by @jindro33 since the update to version 7.26.301, thx for your help ;)

**Comment by Jamo33** [comment] 2024-09-02 09:20
> If not already happened, I would propose to add a "critical" tag to this issue, as the app is pretty much unusable at this point.

Hmmm - I can't seem to find a "critical" tag or label anywhere.  Is it right under my nose?

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/fd456d5c-7792-43a0-9db8-5e7834fcdf8f">

**Comment by jindro33** [comment] 2024-09-02 14:35
@Xovval probably meant editing the title and adding there "critical" to bug.

**Comment by jindro33** [comment] 2024-09-03 08:46
Update:
- after over 48h nothing has changed for me (@Jamo33 seems like a lucky shot for you)
- I've decided to risk offloading the app and downloading it again, to see how this will end up -> no changes so far, luckily the app behaved as it should - historical content is available (tbh not really surprised), other symptoms still present

**Comment by boschlo** [comment] 2024-09-03 10:59
I have the same issue.

**Comment by Achom852** [comment] 2024-09-03 11:04
I remember that I had this issue once a few months ago, but I did pay close attention as the "self resolve" was after a few hours. To give an update, nothing has changed.
I tried:
- restarting signal
- restarting iPhone
- offloading Signal
- waiting (^^)

lucky for me signal desktop still works fine and I can still receive messages as normal (but as described above, reading the message on the phone does not acutally "read" it, I guess because that also has some sending components, which does not work)

(iPhone 12 Mini, iOS 17.6.1, App Ver: 7.26)

**Comment by boschlo** [comment] 2024-09-04 06:52
Still experiencing this issue. Can we somehow upvote/push this to the devs? Signal is pretty useless for me right now... Thanks!

**Comment by Jamo33** [comment] 2024-09-04 07:13
Prior to posting this issue in Github, I wrote to Signal directly to explain the problem.  Today I received this email in reply:

"Hello,
 
Thanks for bringing this to our attention.
 
We're aware of the issue and we're currently looking for a solution. While our engineers will be working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug included in the release notes for future versions of Signal.
 
Thanks again for your help in reporting this."

**Comment by mstoffel-sag** [comment] 2024-09-04 10:18
Got the same issue. Really annoying. Funny thing is, Signal is working perfectly on my iPad

**Comment by boschlo** [comment] 2024-09-04 10:20
+ I can’t cancel my donation subscription anymore through Signal as the page crashes as well. Is there another way to cancel it? I suspect this bug to have something to do with donations.

**Comment by huntforweeks** [comment] 2024-09-04 19:36
Had this occur today, couldn't send messages for about 30 minutes. Was not fixed by restarting phone, but seemed to fix itself after attempting to start a call and letting it spin for 5 minutes.

**Comment by mstoffel-sag** [comment] 2024-09-05 05:14
Does anybody know when the next release is planned? This impacts my whole communication.

**Comment by lexveritasss** [comment] 2024-09-05 12:06
Got the same issue. iPhone 14 Plus

**Comment by jindro33** [comment] 2024-09-05 12:45
**Update:**
1. There appears to be a certain "workaround":
 - iOS native share feature works and delivers 
 - tested with Photos - picture delivered, both with/without comment, Safari - link delivered, Files - file delivered
 - no delay between the app & desktop app
 - works both for contacts/conversations in suggestions as well as through choosing signal and then finding the contact

**Anyone could repeat and confirm?**


2. Not really useful, but got myself a reaction to report from Saturday:
"Hello,
 
Thank you for your message. We are sorry you are experiencing issues.
 
I've gone ahead and filed this bug with our engineering team. While our engineers are working on a fix, I unfortunately can't give out a specific timeline for a resolution. You may see a fix for this bug specifically included in the release notes in future versions of Signal.
 
Thanks again for your help in reporting this and improving Signal for everyone."

**Comment by Jamo33** [comment] 2024-09-05 12:51
Yes i can confirm that if you share something like a web address or photo,
it then worked for me.

**Comment by mmrojo** [comment] 2024-09-05 18:01
Got the same issue. iPhone 13. iOS 17.6.1

**Comment by mstoffel-sag** [comment] 2024-09-06 04:49
Solved in version 7.26.1

**Comment by boschlo** [comment] 2024-09-06 05:41
Thank you for fixing this!

**Comment by lexveritasss** [comment] 2024-09-06 07:41
It seemed to work after today's upgrade

**Closed** 2024-09-06 07:43 UTC

**Comment by jindro33** [comment] 2024-09-06 08:31
> Solved in version 7.26.1

Worked also for me, but there’s a possible delay between updating and working as it should - I started writing the post around 30 minutes before posting it now and after taking some time for testing, left it as it’s below 20 min ago.

(~~)**Unfortunately nothing has changed for me**.

**Updated** -> tested, no changes.
**Offload/install** -> tested, still nothing.
**ON/OFF** -> tested, nothing. (~~)

**Signal’s** email from 7 hours ago:
“Hi there,
 
All fixed now! Sorry for the inconvenience!“

**Comment by Achom852** [comment] 2024-09-06 10:07
@jindro33 thanks a lot for your comment, I really appreciate it, as of course, it was the same for me.
immediately after the update I could not send messages. 

on a side note, not sure if this is relevant for develepment:
I could answer a message (thumbs up reaction) with my apple watch and that actually worked with version 7.26.

Back to the iPhone bug - so far:
- installed update -> nothing changed
- restarted phone -> nothing changed
- clicked on the donate banner -> first time since the bug that I could actually dismiss it without freezing the app -> but nothing changed regarding sending messages
- waited at least 30 minutes -> I can send again from the iPhone. 

Thanks for all the messages and support!
I guess I will finally be a supporting member, as I really like how fast this was solved!
(And I really appreciate the free software in general, as usual you can see the value for real when you cannot use what you take for granted)
