### ISSUE TITLE
Unable to log into existing signal account. 

### ISSUE THREAD

**Issue by DannyW909** [signalapp/Signal-iOS#2454] opened 2017-08-21 17:51 UTC
- [ x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
On the home screen I am unable to log into my account. 
It's asking for a phone number to 'activate this device'.
Below this button it says 'Already have a signal account', I presume this is a login button but the onscreen number pad covers it too quickly to click. 
Unable to hide this keyboard.

### Steps to reproduce
- Log out of account.
- Attempt to log back into account from home screen (using iphone 6).
- Unable to hide number pad to access login button. 

**Actual result:** 

I'm stuck on the initial landing page, unable to progress to log into the app.

**Expected result:** 
Should be able to click on 'Already have a signal account', be taken to a login page and enter valid credentials which would permit entry into the account. 

### Screenshots
![img_4284](https://user-images.githubusercontent.com/4306742/29531653-5b700d84-86a1-11e7-920d-3466111576fa.PNG)
![img_4285](https://user-images.githubusercontent.com/4306742/29531654-5b75da70-86a1-11e7-9cbc-d179ef9af665.PNG)

### Device info

**Device**: iPhone 6
**iOS version**: 10.3.3
**Signal version:** 2.15.3.2

**Comment by NinebitX** [comment] 2017-09-23 10:08
It looks like this is a duplicate of https://github.com/WhisperSystems/Signal-iOS/issues/2321.

**Closed** 2022-01-31 21:44 UTC
Labels: wontfix
