### ISSUE TITLE
Signal crashing every time I open a chat

### ISSUE THREAD

**Issue by undeadpixel** [signalapp/Signal-iOS#5343] opened 2022-05-09 17:25 UTC
Hi!

I just installed Signal to an iPhone Mini 13 with iOS 15.4.1 and it doesn't seem to work alright. In the first minutes, I can chat normally but after a few minutest every time I tap a chat it just crashes the app completely. Clean reinstalls do not work, as the same behavior happens again after a few minutes. 

Here is the debug log: https://debuglogs.org/ios/5.37.1/a48b42bb59160ffd7ab4f4b31b60d25e666262829e56da171ba5030fe5a16d8b.zip

Thanks for your help, and please tell me if you need any extra info.

**Comment by bau666** [comment] 2022-05-09 22:42
In my Iphone 11 it’s the same. I can’t open the first chat

**Comment by fosfa** [comment] 2022-05-11 06:47
Same here. iPhone 7 with iOS 15.4.1. Can't open chats, when tap in a chat Signal crashes.
https://debuglogs.org/ios/5.37.1/681e5c1cfbfad91c6826fe71dc3a6d7de86a61c67d9ceb3588b7bfe8b93391d1.zip

**Comment by jrose-signal** [comment] 2022-05-11 17:43
I'm afraid we had a crash when running in Catalan. It will be fixed in the upcoming 5.37.2 update (already submitted to Apple), but as a workaround you should be able to run Signal in English or Spanish in the meantime (or most other languages; a few others were also affected).

**Comment by highway900** [comment] 2022-05-12 02:44
I can confirm this issue with iPhone 11, iOS 15.4.1 and signal 5.37.2. Application opens very briefly and then crashes. I am unable to get a debug log, I get an error saying "could not find any logs"
I attempted changing languages from English to Spanish and back but this did not effect the crashing issue.

**Comment by jmontane** [comment] 2022-05-12 14:57
> I'm afraid we had a crash when running in Catalan. It will be fixed in the upcoming 5.37.2 update (already submitted to Apple)

I'm curious about this issue and how it impact Catalan language, because I translate Signal to Catalan at Transifex. So, please, where was the problem? In code (where?) or in translated strings? Thanks.

**Comment by jrose-signal** [comment] 2022-05-12 17:26
One of the translated strings used a `%d` format specifier in the original, but `%@` in the translation. We normally have a checker for this, but some of our strings weren't going through the checker (the ones that are stored in Apple's stringsdict format for plural-aware translations). We now check this on our end even for stringsdict files.

**Comment by fosfa** [comment] 2022-05-13 11:43
Running Signal in English solve the problem,thanks. Waiting for next update.

> I'm afraid we had a crash when running in Catalan. It will be fixed in the upcoming 5.37.2 update (already submitted to Apple), but as a workaround you should be able to run Signal in English or Spanish in the meantime (or most other languages; a few others were also affected).

**Comment by jrose-signal** [comment] 2022-05-17 17:56
5.37.2 is out and seems to be fixing the issue for people, so, closing!

**Closed by jrose-signal** 2022-05-17 17:56 UTC
