### ISSUE TITLE
Notifications randomly not appearing

### ISSUE THREAD

**Issue by aleck7** [signalapp/Signal-iOS#4244] opened 2019-08-16 00:32 UTC
### Bug description
On two iPhone 6s the messages arrive with vibrate alarm, but no other notification and no badge. iOS setting allow all notifications. Occures often, but not always. Both on WiFi and 4G.

### Steps to reproduce
- send a message to iOS device
- some message will not generate a visual notification and no badge will appear

### Device info
**Device**: iPhone 6s, another device iPhone 6s Plus

**iOS version**: 12.4

**Signal version:** 2.41.0.21

**Comment by michaelkirk-signal** [comment] 2019-08-16 03:36
Do you have a linked desktop device?

**Comment by aleck7** [comment] 2019-08-16 04:59
Yes, both phones have a linked mac each.

**Comment by michaelkirk-signal** [comment] 2019-08-16 13:44
It sounds like you're experiencing this issue: https://github.com/signalapp/Signal-Desktop/issues/3310

Please subscribe there for updates.

I'm going to close this as a dupe of https://github.com/signalapp/Signal-Desktop/issues/3310, but if it sounds like a different issue, feel free to re-open, along with:

1. iOS debug log
2. Desktop debug log
3. the "sender timestamp" of the message for which a notification was missing so we can cross reference it in the logs.
 The easiest way to get the sender timestamp is on desktop, hover on the message, go to "info" and copy and paste the number after the sent time (highlighted in the screenshot below):
<img width="466" alt="Screen Shot 2019-08-16 at 7 42 35 AM" src="https://user-images.githubusercontent.com/36971200/63171783-858ec900-bff9-11e9-8eff-2427304a9396.png">

**Closed by michaelkirk-signal** 2019-08-16 13:44 UTC
