### ISSUE TITLE
Push notifications are not delivered after update to 2.5.0.19

### ISSUE THREAD

**Issue by acoffman** [signalapp/Signal-iOS#1342] opened 2016-09-22 22:56 UTC
- [x] I have searched open and closed issues for duplicates

---
### Bug description

I downloaded the Signal 2.5.0.18 beta via TestFlight a couple days ago and successfully linked it to a copy of Signal Desktop on an Ubuntu laptop. Everything worked smoothly and as expected.

After updating to the newest build (2.5.0.19) I no longer receive push notifications on my phone. I have "re-registered for push notifications" in the app and that did not seem to fix it. Additionally, new messages do not create an unread count "badge" on the app icon as expected.

**Actual result:**

Receive a message and do not receive a notification or app badge.

**Expected result:**

Receive a message and receive a notification and app badge.
### Device info

**Device**: iPhone 7
**iOS version**: 10.0.0
**Signal version:** 2.0.5.19
### Link to debug log

https://gist.github.com/anonymous/6e3c8b435df0fe63d3e9d203d2e2ee71

**Comment by acoffman** [comment] 2016-09-22 23:03
I'm not 100% positive, but it _seems_ as if my phone screen lights up briefly when a new message is received, but no notification is presented and no badge is generated. I have double checked my "notification" settings in the iOS settings menu and Signal is allowed to produce all notification types.

**Comment by michaelkirk** [comment] 2016-09-23 02:03
Thanks for the report @acoffman. I'm not able to reproduce this and there's nothing interesting in your debug log. 😕 

Do you have an open desktop session? We intentionally track read status and remove notifications from the phone if the thread was viewed on desktop.

It seems like you've already tried this but here's what I'd try:
1. On you device go to settings > advance > register for push notifications
2. You should see "successfully re-registered for push notifications"
3. Kill the app by double pressing your home button, then swiping up on signal
4. Have someone send you a message
5. Check your lock screen - it should appear with the text of the message.

Wait for 60 seconds. If nothing happens, open Signal. Signal will immediately try to fetch any outstanding messages, so try to note the initial state of the inbox, and see if the messages appear to get download *after* launching the app.

Report back if you can.

If you want, you should be able to safely re-install the old Signal from the appstore **after unlinking any linked devices**. If you do, make sure you go through the above steps to re-register for push.

**Comment by acoffman** [comment] 2016-09-23 17:28
Hi @michaelkirk 

Thanks for the followup! Yeah, I didn't see anything odd in the debug logs either, but I figured it was better to attach them than not.

I tried what you indicated and saw no change in behavior. Still no push notifications. A couple of notes if they're helpful:

 * Its not all conversations, only certain ones. Some conversations still send push notifications just fine.
 * I did not have an open desktop session while this was occurring, in fact, the laptop was powered off completely.
 * This behavior to persists after unlinking my desktop session through the settings app on the phone.
 * Unlinking the desktop, deleting the beta version, and re-installing the app store version fixed it.

If no one else in the beta has experienced this issue, and you can't reproduce it either, I'm willing to chalk it up to some random weirdness with my particular setup heh.

**Comment by michaelkirk** [comment] 2016-09-23 20:37
@acoffman Can you explain what you *do* see when someone sends a message?

Do you *never* receive the message or do you not receive it until you open the app?

**Comment by peterpanondrugs** [comment] 2016-12-07 23:57
Since last weeks, my friend has the same problem. 
Until she opens the app, she does not get any notifcations.

https://gist.github.com/9a83919deba899e7c73a78a2dd510496

**Comment by riyapenn** [comment] 2016-12-08 00:06
Have your friend contact support@whispersystems.org and also share the support page here: https://support.whispersystems.org/hc/en-us/articles/213133077-What-settings-or-permissions-do-I-need-to-enable-on-my-iPhone-  She should check the permissions for Signal.

**Comment by peterpanondrugs** [comment] 2016-12-08 00:12
Shes not new to Signal. and it always worked since the last weeks and has never changed it.
She did send you Email.

**Comment by maggiedelano** [comment] 2016-12-13 06:11
I am having what seems to be a similar issue. Here's my debug log in case it is helpful: https://gist.github.com/anonymous/d32fdeb5f871a5b63d90007c2f7f4dba

I'm on iOS10.1.1, Signal 2.6.7, Signal Desktop 0.27.0.

My issue is as follows: things were fine for several months, then I noticed that I wasn't getting push notifications for messages (from one person, have not confirmed with others). I would get a vibrate on my phone, and the message would be there when I searched for it, but no push notification. This happened a few weeks ago and the only way I got it to go away was by uninstalling and reinstalling signal (a reboot did not work). This happened again today. I read this thread and tried re-registering for push notifications as suggested above. That did not solve the issue. Most recently I received a message and the signal desktop dock icon jumped up and down and my phone vibrated, but I did not receive a push notification on desktop OR on iOS.

I'm trying to see if unlinking the desktops I use affects the issue before I reinstall again.

Any suggestions would be appreciated. Thanks for your time.

**Comment by michaelkirk** [comment] 2016-12-13 16:40
> On Dec 13, 2016, at 1:11 AM, Maggie Delano <notifications@github.com> wrote:
> 
> My issue is as follows: things were fine for several months, then I noticed that I wasn't getting push notifications for messages (from one person, have not confirmed with others). I would get a vibrate on my phone, and the message would be there when I searched for it, but no push notification. This happened a few weeks ago and the only way I got it to go away was by uninstalling and reinstalling signal (a reboot did not work). This happened again today. I read this thread and tried re-registering for push notifications as suggested above. That did not solve the issue. Most recently I received a message and the signal desktop dock icon jumped up and down and my phone vibrated, but I did not receive a push notification on desktop OR on iOS.
> 
> 



To clarify, when this happens are you seeing **no** notification, or are you seeing a generic “New Message” notification?

If your phone is vibrating when you get the message, it sounds like you *are* receiving notification of the message, but for some reason it’s not being displayed.

There’s two possibilities that come to mind that would prevent you from seeing a notification.

1. If you view the message on Desktop, we clear the notification from the notification screen.
2. Check your notification settings in the system settings app. Settings > Notifications > Signal, and make sure all are enabled.

**Comment by maggiedelano** [comment] 2016-12-13 16:57
Confirming, I am seeing no notification at all. I verified my notification settings on the app and they are fine.

Last night I unlinked both computers I use and the push notifications work again this AM. I will try relinking and see if I can replicate the issue again.

Could it be possible that the desktop app thinks a message is being viewed when it actually isn't? Because last night I had a case where I had the jumping dock icon on my mac laptop and the vibrate on my phone with neither displaying an actual push notification, but both otherwise indicating receipt of a message. Either no device displayed the push notification, it got cleared promptly, or it got displayed (and somehow marked as viewed) on a different desktop (my work desktop?) instead.

**Comment by vinyll** [comment] 2018-04-09 09:40
I'm fine on my phone but some friends experiment the same issue.
@acoffman / @maggiedelano, did you find a workaround?

**Comment by michaelkirk-signal** [comment] 2018-04-09 19:51
@vinyll - could you have your friends contact support@signal.org?

And if they could include a few things:

- [ ] a fresh debug log (Advanced > Submit Debug Log)
- [ ] mention what time they received the message
- [ ] what time they *should* have received the message.

Thanks for any help.

**Comment by weinberz** [comment] 2019-08-08 12:58
Hello,

I've been experiencing what I think is the same issue and I think I have reproduction steps.

1. Register Signal on an iPhone
2. Link that to a desktop app
3. Select a thread in the desktop app.
4. Lock the desktop or activate the screensaver (so that the app is in the foreground, but is not 'active')
5. Have someone respond in the the thread you previously selected in the desktop app.

Expected result:
A notification is thrown on the iPhone and the desktop for the new thread.

Actual result:
A notification is thrown on the desktop. The iPhone wakes up, briefly displays a notification, and then the notification vanishes.

----------
I noticed this because I was leaving Signal up on my work desktop overnight, and whatever thread was selected in the app would not display notifications on my phone overnight.

I appreciate tracking read status between, but perhaps there could be further criteria implemented on the desktop to mark something as read? For example, I think Messages requires that you click in the text field after foregrounding the app before a message is marked as read.

Happy to provide debug logs if this doesn't repro :)

**Comment by marbetschar** [comment] 2019-09-15 18:36
FWIW: I think I'm experiencing the same issue with iOS App version 2.42.4.0 and macOS Desktop version 1.27.2. Can't really say what is causing the issue, but I don't receive any push notifications and/or badges on the iOS App anymore.

**Closed** 2022-01-31 16:44 UTC
Labels: needs user feedback, wontfix
