### ISSUE TITLE
Support Receiving and Saving WebP Image files

### ISSUE THREAD

**Issue by purpleplatypus** [signalapp/Signal-iOS#1547] opened 2016-12-16 05:01 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
This is vaguely related to #1431 and possibly a part of #902 's implementation as well, but I think this issue deserves its own bug since it deals with picture messaging which is one of the main use cases of Signal. Android users downloading pictures from the web may get them in WebP format. If these pictures are sent to any iOS Signal users, the iOS folks get a nasty unsupported attachment type message. Apple added WebP support to the iOS 10 beta, but it seems they dropped this in the final release. 

iMessage has this compatibility problem as well, if Signal could implement WebP support by having the app auto convert to some iOS ready format, that would be a leg up for Signal.

### Steps to reproduce
- Download a WebP image file by using Chrome on an Android device
- Using Signal, send this file to an iOS Signal user

**Actual result:** iOS Signal user receives no notification that someone even attempted to send them a message. When opening the conversation, iOS Signal user gets an "unsupported attachment type" error. I can attach screenshots if that would help.
**Expected result:** iOS Signal user should get a notification for the picture message and be able to view it in Signal, as well as download it to their device as some non-WebP file, seamlessly.

### Device info

**Device**: Observed: iPhone 6S, iPhone SE, all devices most likely affected
**iOS version**: 10.1.1 and below.
**Signal version:** 2.6.8

### Link to debug log
https://gist.github.com/anonymous/029bf8160bd5d0aef6972d55eb038764

**Comment by Swivelgames** [comment] 2019-02-08 22:36
Any update on this or #902 ?

**Comment by denver-s** [comment] 2019-04-17 18:57
I tried sending [this WebP picture](https://www.gstatic.com/webp/gallery/1.webp) from Signal Desktop to Signal iOS and it worked. I cannot send a WebP image from iOS because it seems that iOS does not support it.

**Comment by okias** [comment] 2019-10-07 07:42
Cannot receive webp on iOS 12.4.2 :(

**Comment by geofurb** [comment] 2020-08-29 07:28
Confirmed this issue persists in iOS 13.6.1 on an iPhone 7.

**Comment by reinhart1010** [comment] 2021-12-29 16:38
Since iOS 14 already supports WEBP images natively and #4572 has been solved, is it safe to close this issue?

**Closed** 2022-03-06 18:31 UTC
Labels: wontfix
