### ISSUE TITLE
Cannot delete a (long/large) conversation

### ISSUE THREAD

**Issue by mheckel** [signalapp/Signal-iOS#4354] opened 2020-01-03 07:56 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I try to delete a long/large conversation, Signal is stuck. The only feedback I get is my phone warming up considerably. The conversation is never deleted, at least not during my several attempts where I kept the phone in this state (on, (stuck) Signal active) for 15-30 minutes. When I then closed Signal and reopened it, it crashed the first time. When I opened it the second time, it worked again, but the conversation was not deleted. iPhone storage settings also reports no change for Signal.

### Steps to reproduce

- Delete a long/large conversation
- Wait (keeping Signal open)

**Actual result:** Conversation not deleted / deletion does not complete within 30 minutes.

**Expected result:** Conversation should be deleted within seconds or a few minutes. Process should show progress. Process should be at least incremental, i.e. delete as long as Signal open (which seems not the case given that Signal storage usage is not affected).

### Device info

**Signal version:** latest App Store version by today

**Comment by mortoray** [comment] 2020-01-27 12:28
I'm experiencing the same problem with the newest iOS Signal release.

**Comment by Mihahn** [comment] 2020-12-11 17:34
Can't reproduce, is this still an issue? If not, please close it.

**Closed** 2022-01-31 09:46 UTC
Labels: wontfix
