### ISSUE TITLE
Always getting a 2nd push notification `New Message!` for every message

### ISSUE THREAD

**Issue by hodgesmr** [signalapp/Signal-iOS#3421] opened 2018-05-13 23:24 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
I am getting two notifications for every message. The first is the expected notification (I choose not to display the content, only the sender, so `Message from ...`), but now I'm constantly getting a second notification: `New Message!` as well immediately after.

### Screenshots
![signal](https://user-images.githubusercontent.com/1208575/39972704-1371cdf4-56d2-11e8-8473-585391c5d4df.jpg)

### Device info

**Device**: iPhone 6S
**iOS version**: 11.3.1
**Signal version:** 2.24.1.0

**Comment by hodgesmr** [comment] 2018-05-13 23:29
**Update:** I didn't realize I had censorship circumvention turned on, so this may be a dupe of #3294.

I've disabled it and will use for a while to see if the notification issue goes away.

**Comment by michaelkirk-signal** [comment] 2018-05-14 14:36
dupe of #3294

**Closed** 2018-05-14 14:36 UTC
