### ISSUE TITLE
🐞APP ALWAYS CRASHES

### ISSUE THREAD

**Issue by OmarBasem** [signalapp/Signal-iOS#4425] opened 2020-04-07 03:57 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion

# describe the problem

App always crashes on the splash screen half a second after opening the app.

### Steps to reproduce

Just open the app

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

App crashes immediately

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The app to open

### Device info

**Device**: iDevice X
Iphone 6s

**iOS version**: X.Y.Z
13

**Signal version:** Z.Y
latest version from the app store as of today

**Comment by charlesmchen-signal** [comment] 2020-04-07 13:31
Hi @OmarBasem Can you please send us your crash report(s)? 

iOS Settings app > Privacy > Analytics & Improvements > Analytics Data > find the most recent crash report(s) that starts with Signal and send them to me at matthew@signal.org.

**Comment by OmarBasem** [comment] 2020-04-09 05:46
@charlesmchen-signal sent.

**Comment by 20k-ultra** [comment] 2020-04-09 22:24
Same exact behavior as Omar just different environment. When I go to find my most recent crash report that latest date is 2019 so there's no report being generated. I'm open to trying out anything to help. @charlesmchen-signal 

I've been using signal for awhile and this only happened after the update. It began as soon as I updated as well. Force closing app or restarting device does nothing. I haven't tried re-installing out of not wanting to lose my messages.

Device: iphone X
iOS version: 13.3
Signal version: 3.7.1

**Comment by JensC** [comment] 2020-04-12 14:35
The same here too ...
Iphone: 6
iOS 12.x
 Signal version: 3.7.1

**Comment by OmarBasem** [comment] 2020-04-17 08:28
@charlesmchen-signal any updates?

**Comment by gir489** [comment] 2020-04-18 00:11
Is this project dead? No updates in almost 15 days, no official devs responding to tickets, and I can't even get Signal to load my contacts.

**Comment by charlesmchen-signal** [comment] 2020-04-22 12:43
Hi @JensC Can you please send us your crash report(s)?

iOS Settings app > Privacy > Analytics & Improvements > Analytics Data > find the most recent crash report(s) that starts with Signal and send them to me at matthew@signal.org.

**Comment by charlesmchen-signal** [comment] 2020-04-22 12:43
@OmarBasem Thank you for the crash report Omar.  The app is failing in its first setup steps while accessing the file system.  Is it possible your phone's storage is full or very nearly full?  Are you seeing issues in other apps?

**Comment by n0sign4l-cys4** [comment] 2020-04-22 12:56
@charlesmchen-signal there is some of my friend that reported me the same issue (app crashes and does not open), but they do not get any crash log.. What should they do?

**Comment by OmarBasem** [comment] 2020-04-22 13:00
@charlesmchen-signal I have 10GB free storage. I am not experiencing problems on any other app except WhatsApp, which uses the Signal Protocol as well. I am guessing it could be something related to the Signal Protocol initialisations on some iOS devices.

**Comment by gir489** [comment] 2020-04-22 13:00
Not to think too far outside the box, but generally the people who “need privacy” are typically people running from something. Is it possible their phones are compromised with some kind of state sponsored malware that is preventing them from using signal?

**Comment by charlesmchen-signal** [comment] 2020-04-22 13:17
@OmarBasem Thanks for your reply.  Is there anything unusual about your device - is it jail broken, for example?

**Comment by OmarBasem** [comment] 2020-04-22 13:18
@charlesmchen-signal no nothing unusual. It is not jail broken.

**Comment by n0sign4l-cys4** [comment] 2020-04-22 18:51
@charlesmchen hi matthew, one of my friends told me that he hasn't got crash log, but if he pus in airplain mode mode his phone and tries t open the app he gets "impossible to very the app, to verify Signal for the first time on this iphone, you have to connect to app sotre. Connect to the internet and retry", wonder if anyone can reproduce this too.

**Comment by 20k-ultra** [comment] 2020-04-23 22:36
I unsubscribed from this but wanted to see how things were going so came back.

> Not to think too far outside the box, but generally the people who “need privacy” are typically people running from something. Is it possible their phones are compromised with some kind of state sponsored malware that is preventing them from using signal?
 
I think the users reporting this issue are in multiple countries so I highly doubt it's a state sponsored attack or any compromise on the device.

I also want to kindly disagree with your, I'll assume misunderstood, claim: 

> people who “need privacy” are typically people running from something

 I understand how you could think that but I'd just like to correct you that this is not true and this mentality shouldn't be propagated. 

disclaimer: I don't intend this response to be rude or condescending or detract the original issue. Thank you everyone for participating in this community.

**Comment by OmarBasem** [comment] 2020-05-17 17:38
@charlesmchen-signal so any updates on this?

**Comment by OmarBasem** [comment] 2020-08-05 08:49
So I have cloned the app and tried to debug the problem and found that the app is failing to create a directory "/transfer" due to not having permission:

`2020-08-05 12:41:03:892 Signal[2119:396824] 💛 [OWSFileSystem.m:263 +[OWSFileSystem ensureDirectoryExists:fileProtectionType:]]: Creating directory at: /transfer
2020-08-05 12:41:03:899 Signal[2119:396824] ❤️ [OWSFileSystem.m:271 +[OWSFileSystem ensureDirectoryExists:fileProtectionType:]]: Failed to create directory: /transfer, error: Error Domain=NSCocoaErrorDomain Code=513 "ERR513.DFV" UserInfo={NSFilePath=/transfer, NSUnderlyingError=0x2810511a0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
2020-08-05 12:41:03:903 Signal[2119:396824] ❤️ [AppDelegate.m:84 void uncaughtExceptionHandler(NSException *__strong)]: exception: Failed to create directory: /transfer, error: Error Domain=NSCocoaErrorDomain Code=513 "ERR513.DFV" UserInfo={NSFilePath=/transfer, NSUnderlyingError=0x2810511a0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
2020-08-05 12:41:03:904 Signal[2119:396824] ❤️ [AppDelegate.m:85 void uncaughtExceptionHandler(NSException *__strong)]: name: NSInternalInconsistencyException
2020-08-05 12:41:03:904 Signal[2119:396824] ❤️ [AppDelegate.m:86 void uncaughtExceptionHandler(NSException *__strong)]: reason: Failed to create directory: /transfer, error: Error Domain=NSCocoaErrorDomain Code=513 "ERR513.DFV" UserInfo={NSFilePath=/transfer, NSUnderlyingError=0x2810511a0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
2020-08-05 12:41:03:904 Signal[2119:396824] ❤️ [AppDelegate.m:87 void uncaughtExceptionHandler(NSException *__strong)]: userInfo: (null)
2020-08-05 12:41:03:959 Signal[2119:396824] ❤️ [AppDelegate.m:88 void uncaughtExceptionHandler(NSException *__strong)]: callStackSymbols: (
    0   CoreFoundation                      0x00000001bc47aa5c 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 1227356
    1   libobjc.A.dylib                     0x00000001bc1a1fa4 objc_exception_throw + 56
    2   CoreFoundation                      0x00000001bc37ce88 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 188040
    3   Foundation                          0x00000001bc7b26c4 503900AF-2ECD-329F-B742-C07C3E672BEB + 554692
    4   SignalServiceKit                    0x00000001074baeb0 +[OWSFileSystem ensureDirectoryExists:fileProtectionType:] + 3476
    5   SignalServiceKit                    0x00000001074ba0f0 +[OWSFileSystem ensureDirectoryExists:] + 80
    6   Signal                              0x000000010481db10 $s6Signal21DeviceTransferServiceC05resetC9DirectoryyyF + 2312
    7   Signal                              0x000000010481e2bc $s6Signal21DeviceTransferServiceC13launchCleanupSbyF + 516
    8   Signal                              0x000000010481e5dc $s6Signal21DeviceTransferServiceC13launchCleanupSbyFTo + 48
    9   Signal                              0x000000010433fc24 __57-[AppDelegate application:didFinishLaunchingWithOptions:]_block_invoke + 80
    10  SignalServiceKit                    0x0000000107758794 $sIyB_Ieg_TR + 16
    11  SignalServiceKit                    0x000000010773dacc $ss5Error_pIgzo_ytsAA_pIegrzo_TR + 24
    12  SignalServiceKit                    0x0000000107758874 $ss5Error_pIgzo_ytsAA_pIegrzo_TRTA.8 + 24
    13  SignalServiceKit                    0x0000000107756718 $s16SignalServiceKit5Bench5title15logIfLongerThan0F12InProduction5blockxSS_SdSbxyKXEtKlF + 240
    14  SignalServiceKit                    0x000000010775883c $s16SignalServiceKit12BenchManagerC5bench5title15logIfLongerThan0H12InProduction5blockySS_SdSbyyXEtFZ + 148
    15  SignalServiceKit                    0x000000010775893c $s16SignalServiceKit12BenchManagerC5bench5title15logIfLongerThan0H12InProduction5blockySS_SdSbyyXEtFZTo + 188
    16  Signal                              0x000000010433e958 -[AppDelegate application:didFinishLaunchingWithOptions:] + 1196
    17  UIKitCore                           0x00000001c04e4388 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 10462088
    18  UIKitCore                           0x00000001c04e6144 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 10469700
    19  UIKitCore                           0x00000001c04eb8d0 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 10492112
    20  UIKitCore                           0x00000001bfcb87c8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1894344
    21  UIKitCore                           0x00000001c014eb70 _UIScenePerformActionsWithLifecycleActionMask + 100
    22  UIKitCore                           0x00000001bfcb92b0 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1897136
    23  UIKitCore                           0x00000001bfcb8d08 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1895688
    24  UIKitCore                           0x00000001bfcb90dc 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1896668
    25  UIKitCore                           0x00000001bfcb8998 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1894808
    26  UIKitCore                           0x00000001bfcbce84 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1912452
    27  UIKitCore                           0x00000001c00803e0 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 5858272
    28  UIKitCore                           0x00000001c016815c _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
    29  UIKitCore                           0x00000001bfcbcbbc 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1911740
    30  UIKitCore                           0x00000001c0168058 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 100
    31  UIKitCore                           0x00000001bfcbca28 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 1911336
    32  UIKitCore                           0x00000001bfb2e880 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 280704
    33  UIKitCore                           0x00000001bfb2d3e8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 275432
    34  UIKitCore                           0x00000001bfb2e5b8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 279992
    35  UIKitCore                           0x00000001c04e9c88 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 10484872
    36  UIKitCore                           0x00000001c00a0dd8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 5991896
    37  FrontBoardServices                  0x00000001c159a7a0 CFAE1F5E-2396-3881-A68B-1B3285B64217 + 51104
    38  FrontBoardServices                  0x00000001c15bf838 CFAE1F5E-2396-3881-A68B-1B3285B64217 + 202808
    39  FrontBoardServices                  0x00000001c15a4f04 CFAE1F5E-2396-3881-A68B-1B3285B64217 + 93956
    40  FrontBoardServices                  0x00000001c15bf4f4 CFAE1F5E-2396-3881-A68B-1B3285B64217 + 201972
    41  libdispatch.dylib                   0x000000010bc82bd8 _dispatch_client_callout + 16
    42  libdispatch.dylib                   0x000000010bc85ffc _dispatch_block_invoke_direct + 232
    43  FrontBoardServices                  0x00000001c15e4418 CFAE1F5E-2396-3881-A68B-1B3285B64217 + 353304
    44  FrontBoardServices                  0x00000001c15e40e4 CFAE1F5E-2396-3881-A68B-1B3285B64217 + 352484
    45  FrontBoardServices                  0x00000001c15e460c CFAE1F5E-2396-3881-A68B-1B3285B64217 + 353804
    46  CoreFoundation                      0x00000001bc3f8a00 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 694784
    47  CoreFoundation                      0x00000001bc3f8958 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 694616
    48  CoreFoundation                      0x00000001bc3f80f0 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 692464
    49  CoreFoundation                      0x00000001bc3f323c 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 672316
    50  CoreFoundation                      0x00000001bc3f2adc CFRunLoopRunSpecific + 464
    51  GraphicsServices                    0x00000001c6378328 GSEventRunModal + 104
    52  UIKitCore                           0x00000001c04edae0 UIApplicationMain + 1936
    53  Signal                              0x00000001041da294 main + 132
    54  libdyld.dylib                       0x00000001bc27c360 2E3F4750-8B67-398B-8530-8417651B1718 + 4960
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by alexomics** [comment] 2020-09-28 16:26
I'm having the same problem as this initial issue. The signal app immediately crashes when opening or when using the share extension.

Device: iPhone 6S
iOS version: 14.0
Signal version: 3.17.5

**Comment by lp** [comment] 2020-12-15 15:36
Same here.  The signal app immediately crashes when opening.

Device: iPhone 6S
iOS version: 12.4.9
Signal version: 5.0.2

**Comment by Mihahn** [comment] 2020-12-15 18:16
> Same here. The signal app immediately crashes when opening.
> 
> Device: iPhone 6S
> iOS version: 12.4.9
> Signal version: 5.0.2

Can you send a crash log to the Signal team? You may find it in Settings -> Privacy -> Analytics & Improvements ->Analytics Data -> Signal.

**Comment by sbingram** [comment] 2021-01-09 18:58
I just moved my Signal over from an iPhone X to iPhone 12 today. The transfer went really well and it worked for two communications then just started crashing upon each start. Quitting and starting app failed to resolve the issue and restarting the phone also did not work. I have collected a crash log, but not sure where to send it?

**Comment by sbingram** [comment] 2021-01-17 17:52
I'd like to add one observation. When the app appears for a quick second before crashing, I can see the verify signal notification at the bottom. It appears to be filled in. I'm not sure if maybe the verification system is flaky or not, but thought that could be the cause of the crashing. I sent my crash log to matthew@signal.org since I saw that address previously on this page, but haven't heard back. Maybe the onslaught of new customers has taken a toll and it's all hands on deck right now, but if I need to send elsewhere, I'm happy to do so. In the meantime, the app is non-functional for me.

**Comment by gir489** [comment] 2021-01-17 17:54
Don't know why I still get copied on this ticket, I've unsubbed from it like twice, but anyway, I was getting crashes when Elon made his tweet, because the hivemind died and the app is worthless without it, but as of recent it seems fine now.

**Closed** 2021-01-28 06:23 UTC

**Comment by obdeijn** [comment] 2021-07-05 14:50
Why was this issue closed? Is it solved?

**Comment by sbingram** [comment] 2021-07-05 16:52
No, not solved. I sent a dump to Signal and never heard back. I gave up and
reset the app and haven't used it since because all of my conversations are
now missing.

**Comment by a-gvo** [comment] 2021-12-18 05:47
I’ve been having this exact issue ever since I downloaded the app months ago. I’ve gone through several iOS versions on my iPad. I’m currently on 15.1. Same exact behaviour. App freezes after some amount of time passes (with regular use). It never recovers. I have to uninstall and install again for it to start working, losing my entire message history in the process.
