### ISSUE TITLE
Immediate crash on startup (5.10)

### ISSUE THREAD

**Issue by AaronVanGeffen** [signalapp/Signal-iOS#4980] opened 2021-04-27 10:29 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating the Signal iOS app to v5.10.0.49, the app immediately crashes on launch. I only see the splash screen for a fraction of a second.

### Steps to reproduce
- Open the app
- See the splash screen for 0.2s
- Immediately get kicked back to springboard

**Actual result:** Crashes to springboard

**Expected result:** Doesn't crash and shows list of chats

### Device info

**Device**: iPhone 12 Mini

**iOS version**: 14.5 (but happened on 14.4.2 as well)

**Signal version:** 5.10.0.49

### Link to debug log

Unfortunately, Signal no longer opens at all, so I cannot enable the debug log. However, please find the latest crash report here: [Signal-2021-04-27-122343.ips.zip](https://github.com/signalapp/Signal-iOS/files/6383804/Signal-2021-04-27-122343.ips.zip)

**Comment by cityrolr** [comment] 2021-04-27 21:38
Can confirm this bug on iPhone 12 Pro with iOS 14.5 and previous one. I have handed in multiple crash reports via Apple as well.

**Comment by fridtjof** [comment] 2021-05-01 17:59
I'm experiencing the same issue since the update.

- iPhone 7
- iOS 14.5

**Comment by AaronVanGeffen** [comment] 2021-05-03 19:53
Unfortunately, upgrading to 5.11 has not resolved the issue for me. This is on iOS 14.5.1.

**Comment by snacks** [comment] 2021-05-05 18:30
I'm experiencing the same issue.

iPhone 7
iOS 14.5.1
signal v. 5.10

**Comment by fridtjof** [comment] 2021-05-06 17:58
Still happening on 5.11.1

**Comment by beret** [comment] 2021-05-12 01:59
Crash occurs immediately after upgrade from Signal 3.9.1 to Signal 5.11.1 on a fresh restore to iOS 14.4 - iPhone SE (Gen 1)
Persists across device restarts.
Just like the original report, crash is in `GRDB Storage.writer` with `Address size fault.`

```
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x000000019b77eaa8
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [1195]
Triggered by Thread:  7
```
```
Thread 15 name:  Dispatch queue: GRDB Storage.writer
```
```
Thread 15 crashed with ARM Thread State (64-bit):
    x0: 0x00000002838db560   x1: 0x000000018a6e4cb4   x2: 0x0000000000007103   x3: 0x0000000107d086a0
    x4: 0x0000000000000140   x5: 0x0000000107d086a0   x6: 0x0000000000000016   x7: 0x00000000000003f8
    x8: 0x00000002838db568   x9: 0x0000000200000003  x10: 0xfffffffe00000000  x11: 0x0000000000000000
   x12: 0x0000000000000003  x13: 0x00000000ab342a5c  x14: 0x00000000ab342a38  x15: 0x000000000000245a
   x16: 0x00000001cf1c79b8  x17: 0x0000000001000004  x18: 0x0000000000000000  x19: 0x00000001062fd824
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x000000000000002e  x23: 0x00000001062cd7f0
   x24: 0x00000002838db560  x25: 0x30000000000000a9  x26: 0x000000000000000b  x27: 0x0000000000000002
   x28: 0x0000017273384336   fp: 0x000000016dc29ec0   lr: 0x000000018a416aa8
    sp: 0x000000016dc29e40   pc: 0x000000018a416aa8 cpsr: 0x60000000
   esr: 0xf2000001  Address size fault

```
[Signal-2021-05-11-14.4.zip](https://github.com/signalapp/Signal-iOS/files/6462900/Signal-2021-05-11-14.4.zip)

**Comment by TobiasKaiser** [comment] 2021-05-16 16:31
I am experiencing the same issue with Signal 5.11.1 on iOS 14.5.1, iPhone 12 mini. I think the problem started after an automatic upgrade to Signal 5.11. When launched, the app crashes immediately and therefore is completely unusable.
I have also sent the ips debug file to Signal's support team and am hoping for a soon fix.

**Comment by cityrolr** [comment] 2021-05-16 17:13
After communicating with Signal 2 weeks ago on this issue, I think this issue won’t be fixed anytime soon. It seems to be an old bug related to transferring data from one device to another. The suggested solution was to re-install Signal incl. the loss of history.

**Comment by beret** [comment] 2021-05-16 18:29
Darn, that’s concerning. Especially since this seems like a pretty clear regression from 5.9 which I can confirm works without issue without any change to user data. I do see a recent closed issue #4963 with the database at launch, but that was not a crash, and was supposedly fixed in 5.9.

**Comment by TobiasKaiser** [comment] 2021-05-18 10:01
Thanks for the feedback. I have reinstalled Signal now. Though I have lost my messaging history, the app works now again at least.

**Comment by beret** [comment] 2021-06-30 01:35
Workaround Update:
Data migration from Signal 5.9 on an iOS device (A) to another iOS device (B) running Signal 5.9 is successful but does not resolve the issue. Any update to 5.10+ again results in crashes on B.

Migration also completes from device B (Signal downgraded back to 5.9) to device A running Signal 5.15 (Test Flight.) Signal 5.15 then immediately crashes on first launch, but the data is accessible on device A after it is again downgraded to 5.9.

The Test Flight workaround to use 5.9 will expire in 9 days.

**Comment by elahmo** [comment] 2021-07-04 14:02
This is still happening, any potential fixes for this?

[Signal-2021-03-15-020901.ips.zip](https://github.com/signalapp/Signal-iOS/files/6759991/Signal-2021-03-15-020901.ips.zip)

**Comment by beret** [comment] 2021-07-04 14:51
Based on my reading of the crash logs I posted above, it looks like this is likely something inside of group chat tables in the database, but there’s a number of commits changing those parts in 5.10.

So it’s definitely fixable but I have no idea if it’s being worked on. (I did also email the updated crash logs and debug (much more useful) logs to support last week.)

The test flight hack can at least buy you a few days of functionality until it expires again.

(Slightly less destructive than destroying all of your chats: while you’re in there you could try nuking group chats until the ones that are mishandled are removed? But that’s gross and not really a solution since there’s fundamentally nothing wrong with our databases… It’s just a fixable regression.)

**Comment by elahmo** [comment] 2021-07-04 16:51
In my case its not applicable, as the app crashes as soon it starts. This has happened a few months ago, requiring a reinstallation, and now it is happening again. This has never happened with other services I have been using for 5-6 years, so its quite a major bug preventing widespread adoption of Signal.

**Comment by beret** [comment] 2021-07-04 17:15
Yeah, I have those exact crashes on startup when I’m on 5.10 or newer. I’ve been working around it for the past few months by picking the older 5.9 version in the test flight beta program. (See above) But that expires in a couple days and then we’ll just be stuck using desktop signal unless we want to destroy years of data.

**Comment by beret** [comment] 2021-09-17 05:46
## Common signatures in crash logs:
Start of migration at launch:
`💛 [GRDBSchemaMigrator.swift:17 runSchemaMigrations()]: Using incrementalMigrator.`
`💛 [GRDBSchemaMigrator.swift:181 registerMigration(_:migrate:)]: Running migration: dataMigration_populateGroupMember`

`❤️ [SDSDeserialization.swift:21 required(_:name:)]: Missing required field: viewed.`
`❤️ [TSInteraction+SDS.swift:4133 grdbFetchOne(sql:arguments:transaction:)]: error: SDSError.missingRequiredField`
`[LAST TWO LINES REPEAT, MAY NOT BE FATAL?]`

When stacktrace is logged, about a second later:
`[SDSRecord.swift:68 sdsInsert(transaction:)]: Insert failed: SQLite error 19: UNIQUE constraint failed: model_TSGroupMember.uuidString, model_TSGroupMember.groupThreadId`

## Related commits in 5.10
bf660c85ce2f231be523418a1160f9f3e7712655 Adding `TSGroupMember` table populated by review of all past threads. Crash occurs during initial table population. 
db3e4417279696db7ab53c4e8eabda54433c543f Adding `viewed` field to `SignalServiceKit/src/Messages/Interactions/TSInteraction+SDS.swift` causing `Missing required field: viewed` during `dataMigration_populateGroupMember`

Unfortunately I don't have debug logs for others in thread, or a testing harness to safely work against my actual data, but this does appear to be a tractable issue scope considering full data access when on 5.9.

**Comment by beret** [comment] 2021-10-05 06:47
I’ve identified my crash in the `TSGroupMember` table handling.
( I don't know if this is the same crash others are seeing; but I was also able to repair and migrate my data to the latest releases.)

### Issue
My crash was that `TSGroupMember` was partially populated with ~20 entries, presumably from an aborted migration.

Signal crashes with the `UNIQUE` `uuidString` constraint mentioned above, rather than gracefully skipping or updating existing data, or dropping/cleaning the table and starting over. (The latter appears a reasonable option, less state to track, and `TSGroupMember` is a product of the larger interaction data.)

IDR exactly how my initial 5.9 > 5.10 migration happened, but I was using an iPhone SE Gen 1, and it was likely just high resource competition during the upgrade.

### Recovery
I did [recovery via a jailbroken phone](https://cight.co/backup-signal-ios-jailbreak/) (thanks @seb2point0!), used [AppStore++](https://cokepokes.github.io/depiction/appstoreplus.html) for arbitrary Signal testing upgrades/downgrades, copied off the DB and keychain key, inspected and tested queries against a decrypted copy, modified the encrypted sqliteDB with `sqlcipher` as below, and finally reinstalled `signal.sqlite` over SFTP/SSH.

```
UPDATE "main"."model_TSInteraction" SET "viewed"=0;
DROP TABLE "main"."model_TSGroupMember";
DELETE FROM "main"."grdb_migrations" WHERE "identifier"='addGroupMember';
.tables
.quit
```

Changes were manually dropping the `TSGroupMember` table, removing the `addGroupMember` migration action in the `grdb_migrations` table, and setting all `TSInteraction` `viewed: null` fields to `0` for good measure. There was a minor inconsistency there due to my failed 5.10+ upgrade (which added `viewed` and set `0`) since messages received after my downgrade back to 5.9 then had that unset as `null`.

#### Caveats  
`keychain_dumper -gn` is hit by [rate limiting on the Secure Enclave](https://github.com/ptoomey3/Keychain-Dumper/issues/68#issuecomment-894400287), so you should manually grant entitlements to only include the needed group(s): https://gist.github.com/beret/8f6347139974f824af1c8167530e9a7f (Or grant all, but scope your retrievals to `U68MSDN6DR.org.whispersystems.signal`  

Permissions: mobile:mobile 644 file/755 directory

For about one or two weeks I had slow message sends on launch, as on each launch Signal would apparently try to retrieve missing Interactions and would churn the CPU reprocessing the whole DB. It appears this mitigated itself after maybe those attempts all timed out. Some data (about the most recent month) was synced back from my desktop Signal client onto my phone. Older messages in that span remain desktop only. This DB has now completed round-trip migrations between iPhones without issue.

I disabled background updates for Signal and force-killed it in Springboard to minimize the risk of data inconsistency. Airplane mode may not hurt either. YMMV. Low risk since 5.9 is already blocked from the Signal network. 

FYI @Imperiopolis-Signal - Since this relates to bf660c85ce2f231be523418a1160f9f3e7712655

**Closed** 2022-01-30 09:04 UTC
Labels: wontfix
