### ISSUE TITLE
Photo upload is clunky and difficult

### ISSUE THREAD

**Issue by Tronetravel** [signalapp/Signal-iOS#3472] opened 2018-05-23 19:53 UTC
Currently photos must be uploaded one by one rather than the model of selecting several images pre upload. Further, photos once uploaded require a second confirmation to then be sent.

Both of these issues do not occur in Telegram/ iMessage etc.

Can Signal change these to make the App easier to use?

**Comment by michaelkirk-signal** [comment] 2018-05-23 19:58
dupe of #2890

**Closed by michaelkirk-signal** 2018-05-23 19:58 UTC
