### ISSUE TITLE
Attachments in Signal cannot be received or sent in iOS 13

### ISSUE THREAD

**Issue by Steakster** [signalapp/Signal-iOS#4224] opened 2019-07-15 04:27 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] This isn't a feature request or a discussion topic

----------------------------------------
Attachments sent to me cannot be downloaded
Attachments I try to send result in an error: ‘An SSSL error has occurred and a secure connection to the server cannot be made’

### Screenshots
![IMG_4069](https://user-images.githubusercontent.com/52904049/61597126-3eeebe80-ac47-11e9-8f7a-33c001e2e515.jpeg)

![IMG_4068](https://user-images.githubusercontent.com/52904049/61597066-6002df80-ac46-11e9-8d9e-3f10fb656a28.jpeg)

### Device info

**Device**: iPhone X

**iOS version**:13.0

**Signal version:** 2.40.3.2

### Link to debug log

https://debuglogs.org/6d4c1f5b02a65f944e0ae9fdd385456af49979355febcf2a6a7148201e9eee68.zip

**Comment by michaelkirk-signal** [comment] 2019-07-22 15:22
dupe of #4222

**Closed by michaelkirk-signal** 2019-07-22 15:22 UTC
