### ISSUE TITLE
Not sync sended message from desktop with iPhone client

### ISSUE THREAD

**Issue by deepLifer** [signalapp/Signal-iOS#4731] opened 2021-01-14 01:17 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Not syncing messages from desktop client and iPhone client

### Steps to reproduce
- Open desktop client
- Open iPhone client
- Link it
- Send message from desktop

**Actual result:** I don't see it on iPhone and receiver get it

**Expected result:** I see it on iPhone and receiver get it

But when I send message from iPhone, it correctly sync with desktop
When I receive a message, I see it on iPhone and desktop
I tried it on windows and macOS clients
but with android mobile client this bug not reproduced

### Device info
**Device**: iPhone XR
**iOS version**: 14.2
**Signal version:** 5.2.0.4

### Link to debug log
IOS 
https://debuglogs.org/fbafec5684d3b6698bd28a698be68d9b20a0b8ed184f3b7c62fcdf37167a224e.zip

desktop 
https://debuglogs.org/f19f582915a1bb69468f828a24df44d307886643dec64dfdaaace8c80681a157

**Comment by riclus** [comment] 2021-01-14 02:13
+1

**Comment by celinajean** [comment] 2021-01-14 09:34
Same Problem.

MacBookPro & Win10 Desktop: send text to Signal Iphone 12 Pro

Actual result: I don't see it on iPhone and receiver get it
Expected result: I see it on iPhone and receiver get it

Installed Signal app on Android, it works fine. It seems Iphone Signal App blocks everything from my Desktop App.

**Comment by Andigabsschon** [comment] 2021-01-14 09:47
+1

**Comment by raimonds1503** [comment] 2021-01-14 10:44
+1
MacBook Pro (macos 11.1) and iphone 11 Pro (ios 14.2)

Messages sent from desktop client does not appear on the phone. But messages sent from phone appear on the desktop app.

**Comment by carstenflokstra** [comment] 2021-01-14 10:58
Don't know if it is related. But it seems like the whole sync has some issues. I have synced my iPhone X (iOS 14.3) with my Macbook Pro (macOS 11.1). After setting up the sync, my messages are not downloaded on my Mac. Don't know if it is an underlying problem of the iOS app or the back-end. Messages sent from my Mac are showing up on my iPhone.

**Comment by akyryl** [comment] 2021-01-14 12:01
+1 MacPro (macos 11.1) iPhone 7 14.3

**Comment by zoomout** [comment] 2021-01-14 12:04
+1 
One party has MacPro (macos 11.1) iPhone 7 14.3 - messages sent from MacOS are not synced to iOS. The other party is on Android 11 + MacOS 10.15.6 can see all the messages on both devices.

**Comment by markaurwin** [comment] 2021-01-14 14:53
+1

**Comment by chapb** [comment] 2021-01-14 17:00
+1
Signal Desktop v1.39.5 and iPhone, Signal-iOS v5.2.0.4. 

I can see all messages (in and outbound) from my phone on Desktop, but can't see outbound messages from Desktop on phone.

**Comment by frogg** [comment] 2021-01-14 19:00
Having similar issues. Theres a also a thread in the Desktop client about that:
https://github.com/signalapp/Signal-Desktop/issues/2576

**Comment by AppiePau** [comment] 2021-01-15 13:19
Here are my two cents...which is a cross post from #4740 

I can attest the same problems described (Self note and sharing messages across devices). I noticed that my linked devices WILL receive message I type to myself and contacts using my phone, but not the other way. So all my linked devices show the sent message from my phone, but when I send them from my PC I get the error as shown above. Both sent to myself as well as to other contacts.

However, my linked iPad seems to work fine both ways. It only occurs on my linked PC and Macbook. 

Further more, this worked until I linked a second phone and tried to switch back to my old one. That mistake was on my side (before this time, all was working fine). After that I completely cleaned out my devices (uninstalling Signal, cleaning data folders) and reinstalling. Even deleting and reinitiating my account did not help.

I read somewhere that this might be timing issue due to different timeservers used on different devices. I have tried tried to let my PC with different NTP servers and then relinking the devices. No cigar.

**Comment by chapb** [comment] 2021-01-15 15:16
Yea, I've seen a couple issues open - one reporting that using the previous version of the desktop app to link devices before upgrading to the current version works.

- signalapp/Signal-Desktop#1499
- signalapp/Signal-Desktop#4852
- signalapp/Signal-Desktop#2576

Will wait for an update!

**Comment by csalvato** [comment] 2021-01-17 03:15
@chapb I'm looking for a way to download a previous version, install, sync, then upgrade to test your suggestion that this works.

I was unable to find a dmg to install any older versions.

Do you know of a way to do this? 🤔 

Thanks!

**Comment by AppiePau** [comment] 2021-01-17 07:11
@csalvato Officially, I'm afraid not. There is no official archive of previous versions. Perhaps for the better to prevent the revival of previously crushed bugs. My guess is to sit tight and wait it out until all service are fully restored. I know, easier said then done. Don't make mistake te reinstall everything, reset everything, hence losing all data.

So far services have already been (partially) restored (on my side) and the next app update should fix this issue: https://twitter.com/signalapp/status/1350631020756828160 Although this is just my guess, an assumption based on the Signal behavior of the past days and reading all the similar issue reports like this one.

**Comment by srivathsavan** [comment] 2021-01-17 08:10
J

**Comment by chapb** [comment] 2021-01-17 18:34
@csalvato from another thread signalapp/Signal-Desktop#4852 ; 

- [WIN] https://updates.signal.org/desktop/signal-desktop-win-1.39.4.exe
- [MacOS] https://updates.signal.org/desktop/signal-desktop-mac-1.39.4.dmg

**Comment by csalvato** [comment] 2021-01-17 23:50
Thanks @chapb !  Using those downloaders, clearing data, unlinking, relinking and then upgrading back to 1.39.5 resolved my issue.

Hopefully this gets resolved soon because it will make harder to get my friends to adopt signal.

**Comment by AppiePau** [comment] 2021-01-18 07:20
@csalvato Amazing, I did the same thing, works like a charm!

**Comment by hutstep** [comment] 2021-01-18 14:12
I can confirm, it works with the 1.39.4 version!
Tanks a lot @chapb @csalvato !

**Comment by moonclimber1** [comment] 2021-01-18 21:48
exactly same problem

**Comment by proggaras** [comment] 2021-01-19 19:39
Same for me: Mac OS 11.1 + iPhone 12

**Comment by chapb** [comment] 2021-01-19 20:10
> 
> 
> Thanks @chapb ! Using those downloaders, clearing data, unlinking, relinking and then upgrading back to 1.39.5 resolved my issue.
> 
> Hopefully this gets resolved soon because it will make harder to get my friends to adopt signal.

You're welcome! I was thinking the same thing. So far I've convinced most of my friends it'll be worth switching, even if we have to do this workaround for now.

**Comment by chapb** [comment] 2021-01-20 04:03
I didn't try the downgrade workaround myself - I left Signal Desktop at 1.39.5. Then, it prompted for an update to Signal Desktop 1.39.6, and with Signal iOS updated to 5.2.1.3, it solved the sync issue for me (and I believe the related Note to Self issue). No user action required in Signal Desktop for me. Happy to see it's fixed!

**Comment by raimonds1503** [comment] 2021-01-20 07:58
Seems to be fixed with latest updates on MacOS and iOS

**Closed** 2022-01-31 09:47 UTC
Labels: wontfix
