### ISSUE TITLE
Use the iphone when turning it around by 90 degrees

### ISSUE THREAD

**Issue by hsteinhammer** [signalapp/Signal-iOS#3999] opened 2018-11-07 17:07 UTC
I use the Signal messenger for some years now on an Android device. It always worked fine. Now I switched to iOS, I bought an iPhone 8.
I generally tend to use Smartphones, holding them in a transverse position. That has not been a problem with Android. Now, I can turn the iPhone, but Signal does not turn the screen, so I cannot type. This seems to be a bug. It should work like the Android version works. No?

**Comment by michaelkirk-signal** [comment] 2018-11-08 13:53
Dupe of https://github.com/signalapp/Signal-iOS/issues/937

We've made some progress on this recently, starting with the media views here: https://github.com/signalapp/Signal-iOS/pull/3973

**Closed by michaelkirk-signal** 2018-11-08 13:53 UTC
