### ISSUE TITLE
Update caused app not able to launch

### ISSUE THREAD

**Issue by wark88** [signalapp/Signal-iOS#4626] opened 2020-11-19 00:18 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
11-18-2020 update rendered app unable to launch. Dont know how an update for emojis would do that... ?? 

### Steps to reproduce
- tap app ivon
- splash screen
- crash

**Actual result:** crash

**Expected result:** useable app
### Screenshots

Hard to do with app not working..

### Device info

**Device**: iDevice 7plus

**iOS version**: 11.0.1 and no, i can not update.. 

**Signal version:**  3.22 - emoji support..

**Comment by Imperiopolis-Signal** [comment] 2020-11-19 09:57
Can you please provide a crash log so we can diagnose this problem? You can attach it here or email it to ios-beta@signal.org https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug

**Comment by john-NZ** [comment] 2020-11-20 03:34
I have experienced the same thing  on IOS14.1  

I can't send a crash log because the app won't start

**Comment by wark88** [comment] 2020-11-20 04:02
not seeing any recent crash files for signal in analysis .. newest one is 2019-09-09.... so ya.. just tried to start app like 5 times and it crashed every time..

**Comment by Imperiopolis-Signal** [comment] 2020-11-20 17:15
> I can't send a crash log because the app won't start

John, please follow the link I shard. To send crash logs, you don’t need the app to launch. You can find them in iOS Settings > Privacy > Analytics > Analytics Data.

**Comment by Imperiopolis-Signal** [comment] 2020-11-20 17:16
> not seeing any recent crash files for signal in analysis .. newest one is 2019-09-09.... so ya.. just tried to start app like 5 times and it crashed every time..

@wark88 can you check if there are any recent “jetsam” reports at the top of the list? It’s possible Signal isn’t crashing but instead that iOS is jettisoning it.

**Comment by john-NZ** [comment] 2020-11-20 20:08
OK, I found the logs...   I have a bunch of "jetsam" entries and a bunch of "signal entries.  I emailed the latest signal log to support@signal

**Comment by hardedarde** [comment] 2020-11-21 19:41
Hello, I have a similar problem with this update. My error seems to be 

`
Application Specific Information:
BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread
Abort Cause 27021735203177218

Thread 0 name:  Dispatch queue: YapDatabase-Write
Thread 0 Crashed:
0   libdispatch.dylib             	0x000000022bc4bf34 0x22bc3d000 + 61236
1   libdispatch.dylib             	0x000000022bc4bad8 0x22bc3d000 + 60120
2   libdispatch.dylib             	0x000000022bc4bad8 0x22bc3d000 + 60120
3   YapDatabase                   	0x0000000104a56f88 0x104a0c000 + 307080
4   SignalServiceKit              	0x0000000102553e44 0x1024a4000 + 720452
5   SignalServiceKit              	0x00000001025bd3cc 0x1024a4000 + 1151948
6   SignalServiceKit              	0x00000001025bce80 0x1024a4000 + 1150592
7   Foundation                    	0x000000022ccb333c 0x22cbb2000 + 1053500
8   Foundation                    	0x000000022ccb27f8 0x22cbb2000 + 1050616
9   Foundation                    	0x000000022cbc3418 0x22cbb2000 + 70680
10  SignalServiceKit              	0x0000000102558768 0x1024a4000 + 739176
11  YapDatabase                   	0x0000000104aac268 0x104a0c000 + 655976
12  YapDatabase                   	0x0000000104aabca0 0x104a0c000 + 654496
13  YapDatabase                   	0x0000000104a24464 0x104a0c000 + 99428
14  YapDatabase                   	0x0000000104a23fa4 0x104a0c000 + 98212
15  YapDatabase                   	0x0000000104a24c34 0x104a0c000 + 101428
16  YapDatabase                   	0x0000000104a24e68 0x104a0c000 + 101992
17  YapDatabase                   	0x0000000104abcab8 0x104a0c000 + 723640
18  YapDatabase                   	0x0000000104abbd40 0x104a0c000 + 720192
19  SignalServiceKit              	0x00000001025d2aec 0x1024a4000 + 1239788
20  SignalServiceKit              	0x00000001025b24b8 0x1024a4000 + 1107128
21  SignalMessaging               	0x00000001054eacfc 0x10541c000 + 847100
22  SignalMessaging               	0x00000001054c2f38 0x10541c000 + 683832
23  SignalMessaging               	0x00000001054ebb18 0x10541c000 + 850712
24  SignalMessaging               	0x00000001054ebbf8 0x10541c000 + 850936
25  libswiftObjectiveC.dylib      	0x000000025a109cb0 0x25a104000 + 23728
26  SignalMessaging               	0x00000001054ea5e4 0x10541c000 + 845284
27  SignalMessaging               	0x00000001054c2f38 0x10541c000 + 683832
28  SignalMessaging               	0x00000001054ebb18 0x10541c000 + 850712
29  libswiftObjectiveC.dylib      	0x000000025a109cb0 0x25a104000 + 23728
30  SignalMessaging               	0x00000001054e9d08 0x10541c000 + 843016
31  SignalMessaging               	0x000000010567310c 0x10541c000 + 2453772
32  YapDatabase                   	0x0000000104a572f4 0x104a0c000 + 307956
33  libdispatch.dylib             	0x000000022bc9d7d4 0x22bc3d000 + 395220
34  libdispatch.dylib             	0x000000022bc4bc1c 0x22bc3d000 + 60444
35  YapDatabase                   	0x0000000104a57244 0x104a0c000 + 307780
36  libdispatch.dylib             	0x000000022bc9d7d4 0x22bc3d000 + 395220
37  libdispatch.dylib             	0x000000022bc4bfe8 0x22bc3d000 + 61416
38  libdispatch.dylib             	0x000000022bc4baf4 0x22bc3d000 + 60148
39  YapDatabase                   	0x0000000104a57104 0x104a0c000 + 307460
40  SignalServiceKit              	0x0000000102555fd8 0x1024a4000 + 729048
41  SignalMessaging               	0x00000001054e98cc 0x10541c000 + 841932
42  SignalServiceKit              	0x000000010260a518 0x1024a4000 + 1467672
43  SignalMessaging               	0x00000001054e9a04 0x10541c000 + 842244
44  SignalMessaging               	0x000000010544c460 0x10541c000 + 197728
45  SignalMessaging               	0x0000000105496c2c 0x10541c000 + 502828
46  SignalServiceKit              	0x0000000102556a5c 0x1024a4000 + 731740
47  libdispatch.dylib             	0x000000022bc9ca38 0x22bc3d000 + 391736
48  libdispatch.dylib             	0x000000022bc9d7d4 0x22bc3d000 + 395220
49  libdispatch.dylib             	0x000000022bc4b008 0x22bc3d000 + 57352
50  CoreFoundation                	0x000000022c1f0b20 0x22c146000 + 699168
51  CoreFoundation                	0x000000022c1eba58 0x22c146000 + 678488
52  CoreFoundation                	0x000000022c1eafb4 0x22c146000 + 675764
53  GraphicsServices              	0x000000022e3ec79c 0x22e3e2000 + 42908
54  UIKitCore                     	0x0000000258a4cc38 0x258190000 + 9161784
55  Signal                        	0x00000001009827a8 0x10092c000 + 354216
56  libdyld.dylib                 	0x000000022bcae8e0 0x22bcad000 + 6368 `

**Comment by bb1984go** [comment] 2020-11-24 23:05
Hi, I'm suffering from the same issue. 

Signal 3.22
iPhone SE (1st gen)
iOS 11.1.1

The most recent Signal crash log is from the 21st November, but the problem happens every time to date. No recent Jetsam event logs. 

Any other suggestions? Possibly iOS 11 related?

**Comment by wark88** [comment] 2020-11-25 00:36
Someone above is having same issue on ios 14..

Cant wait till this is fixed and i can use signal again... :/

**Comment by Imperiopolis-Signal** [comment] 2020-11-25 01:01
We’re still awaiting any kind of crash report regarding this issue. Until we receive such, there’s very little we can do. You can get your crash reports to us most expediently by sending them to ios-beta@signal.org

**Comment by wark88** [comment] 2020-11-25 01:53
Signal/iOS is not generating crash reports when crashing it would seem.. any jetsum reports i have are from 2017..  is there a way to update app to correct the lack of reporting crashes??

**Comment by Imperiopolis-Signal** [comment] 2020-11-25 01:58
Generating crash reports is something we have no control over, it’s done by iOS.

**Comment by john-NZ** [comment] 2020-11-25 08:54
Hi I sent a crash report a few days ago, I haven't heard back yet....  file was called: Signal-2020-11-21-062035.ips

**Comment by bb1984go** [comment] 2020-11-25 21:38
Any idea when the next Signal update is due? Can't see any way forward with the current version when no relevant crash logs are being generated.

**Comment by wark88** [comment] 2020-11-25 23:52
Even a roll back to previous version would be helpful.. not really sure how an update only regarding emoji support would cause the app to not launch.. what else was changed? Cuz that obviously wasnt the only thing..

**Comment by bb1984go** [comment] 2020-11-26 20:07
> 
> Even a roll back to previous version would be helpful.. not really sure how an update only regarding emoji support would cause the app to not launch.. what else was changed? Cuz that obviously wasnt the only thing..
> 

What?!? A changelog that actually reflected the changes that had taken place? That would never catch on! :D

**Comment by Imperiopolis-Signal** [comment] 2020-11-28 00:31
> Hi I sent a crash report a few days ago, I haven't heard back yet.... file was called: Signal-2020-11-21-062035.ips

@john-NZ Unfortunately, there is something wrong with the crash report you sent in. It doesn't actually include any information about the crash so there's nothing we can do with it. I've never seen anything like this report from iOS before. If you can provide another report it might be helpful.

> Hello, I have a similar problem with this update. My error seems to be

@hardedarde your problem seems very different – it looks like you haven't run an up-to-date version of Signal in nearly a year, and it's crashing trying to run a major database migration. Given we have long since EOL'd support for apps prior to that migration, I'd say it's very unlikely you'll see a fix here. Your best bet is to reinstall a modern version of Signal and start fresh.

> Any idea when the next Signal update is due? Can't see any way forward with the current version when no relevant crash logs are being generated.

@bb1984go it sounds like you were seeing crash logs as recently as 11/21? Unless you send those logs to us there's not much we can do. Please send the logs to ios-beta@signal.org

**Comment by Imperiopolis-Signal** [comment] 2020-11-30 23:05
I finally received crash reports, and the root cause of the issue reported by @wark88 has been resolved in 3.22.1.1 (should be available in the app store in ~24 hours). The fix will also shortly be available to our TestFlight users in 3.23.0.1

Please note that this will be our last release of Signal that supports iOS 11 versions prior to 11.2, due to a bug in Unicode processing in early versions of iOS 11. All devices running these versions of iOS have an upgrade path available in which you can continue using Signal (whether or not you want to take that upgrade is up to you).

There were some other crash on launches surfaced in this thread (different to the originating iOS 11 crash). If you are still seeing those on newer iOS versions, please open a new bug to track them and send crash logs our way.

**Closed by Imperiopolis-Signal** 2020-11-30 23:05 UTC
