### ISSUE TITLE
iOS Signal Text Box not scrolling

### ISSUE THREAD

**Issue by AlexanderZuehr** [signalapp/Signal-iOS#5667] opened 2023-09-24 16:36 UTC
iPhone 13 mini
iOS: 17.0.1
Signal: 6.42.0.18

Hey, after i updated to iOS 17 i do have a problem with Signal. 
Before the update i was able to write messages with my contacts and regardless of the text length, the textbox scrolled automatically. 

Now if i write a text i dont see the line i am writing, if the text is larger than the textbox. It should scroll down to let me see the the line i am writing, but it isnt.

in the first screenshot you can see that the word app is already written in a new line, but i am not able to see it.
![IMG_0139](https://github.com/signalapp/Signal-iOS/assets/76497172/ce313d2d-70e5-424d-8fe5-6ef94efc3564)

In the second picture i needed to add 4 signs i chose ! and after that signal seemed to scroll down.

![IMG_0140](https://github.com/signalapp/Signal-iOS/assets/76497172/4062ab7f-4c40-4692-8034-06c983729996)

**Comment by Qhilm** [comment] 2023-09-25 06:58
I have the same issue. For me it only starts with the third line, the second line does not have this issue. (iPhone 12 mini)

The problem for me is only reproducible with gBoard actually, not with the native apple keyboard. And it's not 100% reproducible yet for me, it seems to require specific conditions which I have not identified. It is however quite frequent, I would say it happens 50% of the time I use the app.

iOS 17.0.1 and this issue started with iOS 17.0.0, I did not have this problem before. I see other rescaling/scrolling issues in iOS 17 in other apps though, so maybe there's an issue with iOS 17 on small screens.

**Comment by Miguel-Signal** [comment] 2023-09-25 15:50
Hi @AlexanderZuehr @Qhilm 

We are aware of the problem and we are currently looking for a solution. Although our engineers are working on a fix, unfortunately I can't give a specific schedule for resolution. You might see a fix in the release notes for future versions of Signal.

Thanks again for your help in reporting this!

**Comment by patjolata** [comment] 2023-09-29 15:15
The problem also occurs on iPhone 13 with iOS 17.0.2 - just as an additional information. Signal v. 6.43.0.10

**Comment by PattaFeuFeu** [comment] 2023-10-01 20:10
Same with iPhone 15,2 on iOS 17.0.1. Dynamic text is set to the centre position, display zoom set to “standard”

**Comment by zandchyl** [comment] 2023-10-20 19:12
iPhone 13 mini
iOS 17.1 RC
Signal 6.46.1

Textbox also Not scrolling properly for me.

**Comment by Miguel-Signal** [comment] 2023-10-24 20:32
Could anyone experiencing this issue try the following and let me know if it helps?

1. Restart your iPhone.
2. Check for Software Updates (iOS Settings app > General > Software Update).
3. Reset Keyboard Settings (iOS Settings App > General > Transfer or Reset > Reset > Reset Keyboard Dictionary).

**Comment by Qhilm** [comment] 2023-10-25 07:09
Just did it (although, I switched steps 2 and 3, I hope that's not a big deal). So far I cannot reproduce the issue anymore, but since it did not happen every time, it does not mean much yet. I will monitor it and report back.

**Comment by FernetMenta** [comment] 2023-10-26 09:17
> Could anyone experiencing this issue try the following and let me know if it helps?
> 
> 1. Restart your iPhone.
> 2. Check for Software Updates (iOS Settings app > General > Software Update).
> 3. Reset Keyboard Settings (iOS Settings App > General > Transfer or Reset > Reset > Reset Keyboard Dictionary).

Tried it but doesn't change anything here. iOS 17.1

**Comment by LeoniePhiline** [comment] 2023-10-27 20:43
I can confirm this issue on iOS 17 on iPhone Xs and iPhone 11 Pro Max.

**Comment by Miguel-Signal** [comment] 2023-10-30 12:54
@LeoniePhiline Could you also try a keyboard reset?

Reset Keyboard Settings (iOS Settings App > General > Transfer or Reset > Reset > Reset Keyboard Dictionary).

**Comment by Qhilm** [comment] 2023-10-30 14:38
> Just did it (although, I switched steps 2 and 3, I hope that's not a big deal). So far I cannot reproduce the issue anymore, but since it did not happen every time, it does not mean much yet. I will monitor it and report back.

It took a while for the issue to happen again but now it's back and happening regularly again.

**Comment by FernetMenta** [comment] 2023-10-30 16:01
> > Could anyone experiencing this issue try the following and let me know if it helps?
> > 
> > 1. Restart your iPhone.
> > 2. Check for Software Updates (iOS Settings app > General > Software Update).
> > 3. Reset Keyboard Settings (iOS Settings App > General > Transfer or Reset > Reset > Reset Keyboard Dictionary).
> 
> Tried it but doesn't change anything here. iOS 17.1
> 
> EDIT: hmm, maybe the reset was async. Now I can't reproduce it anymore.

The issue is back here too.

**Comment by emmitt** [comment] 2023-10-30 19:31
> Could anyone experiencing this issue try the following and let me know if it helps?
> 
> 1. Restart your iPhone.
> 2. Check for Software Updates (iOS Settings app > General > Software Update).
> 3. Reset Keyboard Settings (iOS Settings App > General > Transfer or Reset > Reset > Reset Keyboard Dictionary).

Hej,
unfortunately it doesn't help...

**Comment by kvaellning** [comment] 2023-11-16 05:52
Same here, issue is persistent. Even resetting didn’t help, unfortunately.

**Comment by liebmar** [comment] 2023-11-17 08:40
Same issue here (for months now), iOS 17, iPhone 14 ProMax. Pretty annoying, it is really a pain if you rely on signal. 

Nevertheless, thanks for your work. Signal is an amazing project and I will continue donating.

**Comment by vinzenzu** [comment] 2023-11-17 22:58
I have the same issue, with both the native keyboard, as well as with GBoard.

iPhone SE 2020
iOS 17.1.1 (issue exists since iOS 17 upgrade)
Signal 6.50.0.13

Thanks

**Comment by madamadami** [comment] 2023-11-19 11:31
Same here since months: iPhone 13, iOS 17.1.1, Signal 6.50.0.13

**Comment by Janikson9** [comment] 2023-11-25 14:14
There was a slight improvement in the course of the update.
However, the problem still occurs occasionally with some chats.
Especially if a picture was sent beforehand.

https://github.com/signalapp/Signal-iOS/assets/152014058/183ceba6-4929-4f38-a787-fb03d92f8b8b

**Comment by Qhilm** [comment] 2023-11-25 17:05
Workaround: if you long press space bar (on the apple native keyboard) and drag down, the last row will slowly appear. Or long-press the cursor and drag down, the last line will appear. Doesn't fix anything, but it helps me sometimes.

**Comment by Janikson9** [comment] 2023-11-25 17:23
> Workaround: if you long press space bar (on the apple native keyboard) and drag down, the last row will slowly appear. Or long-press the cursor and drag down, the last line will appear. Doesn't fix anything, but it helps me sometimes.

Thank you
I hope that the bug will be permanently fixed soon

**Comment by baurmatt** [comment] 2023-11-26 11:58
Experiencing the same issue. iPhone 13 with iOS 17.1.1 and Signal 6.50.1.0

**Comment by JeremiasThun** [comment] 2023-12-01 11:40
> Could anyone experiencing this issue try the following and let me know if it helps?
> 
> 1. Restart your iPhone.
> 2. Check for Software Updates (iOS Settings app > General > Software Update).
> 3. Reset Keyboard Settings (iOS Settings App > General > Transfer or Reset > Reset > Reset Keyboard Dictionary).

Installing the iOS Software Update for me actually was the trigger to GET this problem.

I had no issues with iOS 16. But as soon as I updated to 17, my Signal had the exact issue as described here. I’m living in hell now.

**Comment by Qhilm** [comment] 2023-12-01 13:53
> I had no issues with iOS 16. But as soon as I updated to 17, my Signal had the exact issue as described here. I’m living in hell now.

It is definitely triggered by iOS 17. Unclear if it really is an iOS 17 bug and Signal has to work around it (if possible) or if it's actually a Signal bug which was simply not visible in iOS 16.

Drag the cursor down and hold slowly reveals the last line. It's the best workaround I could figure out so far.

**Comment by Ja83La** [comment] 2023-12-05 21:34
May this be a problem with the German keyboard? 
Most screenshots revealing this bug have a German layout.

**Comment by madamadami** [comment] 2023-12-05 22:48
Picking up the suggestion, that the german keyboard may play a role in the issue is a good idea. I have a german keyboard on a iPhone 13, iOS 17.1.2.

**Comment by Qhilm** [comment] 2023-12-06 04:43
nah, I think it's due to the fact the biggest signal community in absolute numbers is located in germany ;)

I use gBoard in US layout and I still have the issue.

but I do mostly type in german.

**Comment by Miguel-Signal** [comment] 2023-12-06 15:23
Would anyone willing to try out the latest Signal Beta (version 6.52.0.8) install it and tell me if it fixes this issue? 

Follow steps from the support page here to join the iOS Beta: https://support.signal.org/hc/articles/360007318471

**Comment by JeremiasThun** [comment] 2023-12-06 15:33
It feels, like the bug occurs way less often and if it does, the scrolling keeps up way faster (the last typed word keeps invisible, until I type the 2 next characters).
But it isn't completely fixed...

![IMG_8328](https://github.com/signalapp/Signal-iOS/assets/32883765/18a644ac-4197-4be7-b1f8-81b490d4114a)
![IMG_8329](https://github.com/signalapp/Signal-iOS/assets/32883765/133d5a16-4135-4c8d-8d26-83d90920dab0)
![IMG_8330](https://github.com/signalapp/Signal-iOS/assets/32883765/9c6d38c5-c2a3-417d-8393-f334a4348ce5)
![IMG_8331](https://github.com/signalapp/Signal-iOS/assets/32883765/891eee19-3735-401c-addf-3f70cecad71f)
![IMG_8332](https://github.com/signalapp/Signal-iOS/assets/32883765/718571b6-043b-45c8-b874-ab15aa77a28a)

**Comment by Miguel-Signal** [comment] 2023-12-07 13:57
We've just released Beta version 6.53.0.5, and would appreciate some feedback on this version!

**Comment by Qhilm** [comment] 2023-12-11 14:21
been using it a couple of days, issue seems now solved for me.

**Comment by JeremiasThun** [comment] 2023-12-11 14:32
> been using it a couple of days, issue seems now solved for me.

i made same observation

**Comment by chschommer** [comment] 2023-12-13 19:26
Looks like the issue was fixed with latest update. I wonder where can I find the related PR? I would be interested in seeing the fix. I cannot see a PR/branch attached to this issue nor a related closed pull request.

**Closed** 2023-12-13 19:34 UTC
Labels: Acknowledged
