### ISSUE TITLE
Unable to transfer Signal account from my iPad to my new iPhone

### ISSUE THREAD

**Issue by anjan1212** [signalapp/Signal-iOS#5034] opened 2021-06-14 08:56 UTC
Hi, 

I had an iphone 11 pro max & an ipad pro 11in, both updated to the newest version of iOS.

I got a new iphone 12, and factory reset my iphone 11. However, I still have my full signal account running on my iPad pro 11in. 

I'm trying to transfer my chat history from my signal account on my ipad pro to my new iphone 12. 

However, when I try to make the transfer, I get an error message,

<img width="451" alt="CleanShot 2021-06-14 at 01 53 49@2x" src="https://user-images.githubusercontent.com/84593372/121866048-6d4e6a80-ccb3-11eb-8f17-ad3235077ca3.png">

"To transfer your account, you must scan with your iPhone"

What do I do?

**Comment by Dr-Big-Man** [comment] 2021-06-17 09:27
Just guessing here - could it be possible that you will need to enable camera access for Signal app in the configuration of the new iPhone? However, in that case I would expect corresponding explanation in the text of the error message. Anyway - maybe this helps...

**Comment by ncurrault** [comment] 2022-01-22 05:39
It looks like this is a duplicate of #4558

**Comment by NiklasBr** [comment] 2022-03-23 08:09
Signal needs to respond, it is still relevant.

**Closed** 2022-05-29 09:04 UTC
Labels: wontfix

**Comment by NiklasBr** [comment] 2022-05-30 08:51
@stale this is still relevant

**Comment by neuronalX** [comment] 2023-01-18 23:52
Yes it is still relevant. Please reopen the issue.

**Comment by NiklasBr** [comment] 2023-01-19 08:07
@stale is causing way too much spam & confusion and even the original maintainers recommends against using it: https://github.com/probot/probot.github.io/pull/376
