### ISSUE TITLE
Signal notifications not working on Apple iPhone by default

### ISSUE THREAD

**Issue by denisbider** [signalapp/Signal-iOS#4652] opened 2020-12-17 23:58 UTC
There must be some issue with Signal on iPhone that is at the very least a usability issue involving notifications. I have two separate acquaintances whom I convinced to use Signal who are using iPhones. For both of them, they do not receive notifications from Signal if the iPhone screen is off when I send them a message. They have to explicitly check for my messages (which they do with usually great delay).

For one of them, I tried to figure out the issue by looking at their iPhone and following the troubleshooting steps [found here](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications). All the settings appeared to be correct, and I was unable to figure out the cause.

For one of the acquaintances, the notifications work if they are using WhatsApp at the time I send them a message. There is no notification if their iPhone screen is off.

For the other acquaintance, their Apple Watch buzzes if I send them a message, but the iPhone does not make a sound and there is no notification visible on the iPhone.

At the very least, you guys have a major usability issue which is preventing adoption of Signal on iPhone. I cannot recruit people to Signal if this is how it behaves, and if it's so difficult for them to figure out why notifications don't work. This has to be understood and fixed if you want Signal to be adopted by iPhone users.

**Comment by wtangofoxtrot** [comment] 2021-01-09 20:58
+1 I have been having the exact same issue on my iPhone11 running iOs 14.2, upgrading to iOs 14.3 dint fix it. I know several other iOs users who also have the issue but then there are others for whom it works just fine. Tried to re-install the app from scratch but no change.

Issue:
- No Call (voice/video) notifications if the screen is locked 
- If the screen is unlocked I get a notification popup of an incoming call, no audio
- Usually wont know of a call till the call ends and I get a notification that i have a missed call

First seen: ios 14.0, happened as soon as I upgraded, was working fine before.

Debug logs: https://debuglogs.org/ce5b7900b1a8c87dcb557badcec5f62b74542bfc25d01de2390d45efeb37cca9.zip

**Comment by rRk-evolver** [comment] 2021-01-10 12:34
Facing the same issue in 7plus as well
Is there any way to resolve this

**Comment by denisbider** [comment] 2021-01-10 18:39
Is this an oversight or flaw in Signal? Have Signal developers looked into this?

If Signal developers can't find the cause, could this be intentional sabotage by Apple? They recently worked with Google and Amazon to sabotage Parler, so their ethics are known to be questionable, and Signal competes with their iMessage.

**Comment by DamianosS** [comment] 2021-01-13 19:42
Same situation here. 

> No Call (voice/video) notifications if the screen is locked
> If the screen is unlocked I get a notification popup of an incoming call, no audio

**Comment by sschuberth** [comment] 2021-01-16 10:17
Possible duplicate of: https://github.com/signalapp/Signal-iOS/issues/4499

**Comment by DamianosS** [comment] 2021-01-16 12:00
> Possible duplicate of: #4499
It seems that the issue might have the same origin, yes. 

Nevertheless, let me give a more detailed description:
- Last week five people installed Signal on iPhones and Android.
- Calling does not work as expected. The behavior is rather strange
- Calling leads either to immediately missed calls (95% of calls) or to "silent" calling with a small banner on the iPhones, but no ringtone
In general, calling (voice or video) doesn't work appropriately with Signal.

https://debuglogs.org/a43a5b0457491630d1216ad5d5396546b018d36a046873dc6c05919a135075b5.zip

**Comment by elbaulp** [comment] 2021-01-17 10:10
Same here but only for calls. I receive notifications (also with sound) for messages only, as does my girlfriend. But when making video calls if the phone is locked there is no notification nor sound. To get a notification with sound signal must be opened.  

Both iphones are a 7. But i have the same problem for android users.

**Comment by wtangofoxtrot** [comment] 2021-01-31 17:05
Is this on the devs radar ? With so many people switching to signal recently I have several family members now complaining that they never receive a notification when they are called via video or voice. I have the same issue and I usually have to keep my laptop around me and running as it notifies me if someone calls.

**Comment by sschuberth** [comment] 2021-01-31 17:17
Given how long-standing this issue is (I've experienced it way before this issue was filed), I doubt that the devs have it on their radar; otherwise I guess it would have been fixed, given how badly it affects the user experience. My family members have meanwhile switched to another solution because of this.

**Comment by MatejKovacic** [comment] 2021-02-01 09:00
I also have a similar problem (described it in #4852), however it seems there is general problem with calls.

When calling from iPhone, Android or desktop version, I sometimes do not get "ringing" on the other side ("Ringing" text does not appear on a contact I have been calling). However, if I try to call again after a couple of seconds, Signal says it is ringing on the other side (but sometimes it is actually not!).

Another option is, that I first send a message (for instance "I will call you"), and then I call - in that case Signal says it is ringing on the other side (and again, sometimes it is actually not!).

So it seems there is some signalling problem. It looks like by sending message first or trying to establish call, which is then missed (and the person on the other side gets notification about missed call) opens some kind of a channel between the devices and after that, the other device is ready to accept the call data.

Anyway, calling and notifications have been working perfectly in the past, but in a last month I and my contacts are experiencing more and more problems with this. For me, calling is not even possible anymore, which is very bad for user experience.

Can we get at least some response from the developers?

**Comment by denisbider** [comment] 2021-02-01 18:33
With notifications not working, Signal is basically not fit for purpose outside of closed groups that don't use affected devices. Signal cannot be a replacement for WhatsApp if this is not fixed, but maybe some other app (Telegram?) could be.

**Comment by MatejKovacic** [comment] 2021-02-01 20:37
Sorry for being offtopic, but Telegram is not an app which could be trusted for high security. Anyway, it is also possible that the problem is Apple, because in the past calls and notifications in signal were working just fine.

**Comment by artelse** [comment] 2021-02-07 10:50
This needs to be fixed, I cannot communicate with a friend because he never gets the notifications and had to have the app open. Signal devs, please fix this.

**Comment by MatejKovacic** [comment] 2021-02-07 20:01
It seems that this problem is somewhat related to Signal database. I have got reports that reinstalling Signal solves the problem, but in that case I loose all my history.

**Comment by wtangofoxtrot** [comment] 2021-02-08 00:31
> It seems that this problem is somewhat related to Signal database. I have got reports that reinstalling Signal solves the problem, but in that case I loose all my history.

Ive tried that and it had not effect. Been living with this issue for 3-4 months now. I enabled vibrate on calls in iOs so atlast I get some indication when someone is calling on signal but its sad how many people I know are impacted and are back on whatsapp/facetime now because signal wont work reliably.

**Comment by rnewman** [comment] 2021-02-10 23:44
In the last week or so my Signal iOS install, iPhone X, iOS 14.3, is in the same state: I don't receive messages when the app is not in the foreground. Switching to Signal causes all queued messages to be received.

Signal desktop isn't running. I've toggled Bluetooth (and have no Apple Watch), Airplane Mode, have toggled every notification setting, Background App Refresh is turned on, phone has been rebooted, a Signal update has been installed, and I have re-registered for push notifications multiple times.

That operation succeeds:

```
2021/02/10 18:33:27:776  💛 [PushRegistrationManager.swift:59 requestPushTokens()]: 
2021/02/10 18:33:27:777  💛 [PushRegistrationManager.swift:141 registerUserNotificationSettings()]: registering user notification settings
2021/02/10 18:33:27:796  💛 [PushRegistrationManager.swift:177 registerForVanillaPushToken()]: 
2021/02/10 18:33:27:802  💛 [AppDelegate.m:404 -[AppDelegate application:didRegisterForRemoteNotificationsWithDeviceToken:]]: registered vanilla push token
2021/02/10 18:33:27:802  💛 [PushRegistrationManager.swift:157 isSusceptibleToFailedPushRegistration]: has backgroundRefreshStatus != .denied, not susceptible to push registration failure
2021/02/10 18:33:27:802  💛 [PushRegistrationManager.swift:220 registerForVanillaPushToken()]: successfully registered for vanilla push notifications
2021/02/10 18:33:27:804  💛 [PushRegistrationManager.swift:229 registerForVoipPushToken()]: 
2021/02/10 18:33:27:804  💛 [PushRegistrationManager.swift:264 registerForVoipPushToken()]: using pre-registered voIP token
2021/02/10 18:33:27:804  💛 [PushRegistrationManager.swift:269 registerForVoipPushToken()]: successfully registered for voip push notifications
2021/02/10 18:33:27:805  💛 [SyncPushTokensJob.swift:40 run()]: finished: requesting push tokens
2021/02/10 18:33:27:807  🧡 [SyncPushTokensJob.swift:61 run()]: uploading tokens to account servers. pushToken: [ READACTED df...34 ], voipToken: [ READACTED 39...5f ]
2021/02/10 18:33:27:808  💛 [TSNetworkManager.m:399 -[TSNetworkManager makeRequestSync:completionQueue:success:failure:]]: Making Non-UD request: { PUT: v1/accounts/apn }
2021/02/10 18:33:28:494  💛 [TSNetworkManager.m:417 -[TSNetworkManager makeRequestSync:completionQueue:success:failure:]_block_invoke]: Non-UD request succeeded : { PUT: v1/accounts/apn }
2021/02/10 18:33:28:495  🧡 [SyncPushTokensJob.swift:95 recordPushTokensLocally(pushToken:voipToken:)]: Recording push tokens locally. pushToken: [ READACTED df...34 ], voipToken: [ READACTED 39...5f ]
2021/02/10 18:33:28:497  💛 [SyncPushTokensJob.swift:68 run()]: completed successfully.
```

but I still don't receive messages until I open the app.

**Comment by houseboy** [comment] 2021-02-23 19:35
I was only able to fix this by deleting Signal from my iPhone, rebooting, and then reinstalling and registering again. 

Before I did this, I followed the [instructions here](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#ios_restore) to transfer my message history to another iOS device, and then transferred the messages back to my phone afterward. You can transfer to another iPhone or to an iPad, the button to register the iPad is slightly obscured, follow [these instructions](https://support.signal.org/hc/en-us/articles/360008216551-Installing-Signal#install_ios) to register the **iPad as a Separate Device**. 

I started out reading the [instructions](https://support.signal.org/hc/en-us/articles/360007062172-Signal-Permissions-OS-Notification-Settings#ios_permissions) and [guides](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#ios_notifications_troubleshooting) for troubleshooting notification issues in the Support documents but I was not able to resolve the issue.

**Comment by lynix** [comment] 2021-03-05 07:43
Same issue here on iOS 14.4 (Signal 5.5.0.18), stopped working without an iOS or app update.

**Comment by DenysVuika** [comment] 2021-03-17 14:44
Having same problem with iOS 14.4.1 and Signal 5.7.0.19

**Comment by robel-yemane** [comment] 2021-03-23 21:44
+1 ! Is anyone from signal going to look at/address this issue?

**Comment by laurentr** [comment] 2021-04-16 15:29
+1 my friend isn't even showing delivery receipts unless they open Signal.

**Comment by DenysVuika** [comment] 2021-04-16 16:20
I solved this problem by re-installing Signal for iOS from scratch

**Comment by sschuberth** [comment] 2021-04-18 07:21
I was looking for an alternative to re-installing Signal to fix this, and what seems to have worked for me is to go to Signal's "Settings" -> "Notifications" and choose to "Re-register Push Notifications".

**Comment by MatejKovacic** [comment] 2021-04-18 08:23
For me, it is not working (iOS 14.4.2, Signal 5.8.2.0).

**Comment by rnewman** [comment] 2021-05-03 15:39
I transferred messages to a new iPhone, uninstalled, reinstalled, and then transferred back, and surprisingly it did not resolve the issue. I will try again with some more reboots.

**Comment by dfritsch1989** [comment] 2021-05-08 21:39
> I was looking for an alternative to re-installing Signal to fix this, and what seems to have worked for me is to go to Signal's "Settings" -> "Notifications" and choose to "Re-register Push Notifications".

This has not worked for me so far. I have all notifications open on the device, reregistered push, uninstall, reinstall, deleted the app from my computer, and some other things but so far no luck. Just seems to have come out of the blue as an issue

**Comment by jtigger** [comment] 2021-05-16 17:31
I too have been experiencing these symptoms: not receiving notifications for new messages.

Uninstalling and reinstalling the app on my iOS device fixed it.

**Comment by MatejKovacic** [comment] 2021-05-16 18:11
And how you make a backup of all conversations in that case?

**Comment by jtigger** [comment] 2021-05-17 13:50
> And how you make a backup of all conversations in that case?

I had a desktop client linked. I decided that — for my purposes — having that one backup was sufficient.
I uninstalled, reinstalled, and relinked to the desktop client. The message history was preserved on the desktop client

**Comment by seniorm0ment** [comment] 2021-05-17 15:10
I've had some family state they have issues receiving notifications to their Apple Watch, unsure if it's related, I can't really give much more info about device or os model, but I did fine another user on the subreddit mention the same issue

**Comment by MatejKovacic** [comment] 2021-05-18 11:28
Guys, this issue is a real stopper for us, who are experiencing it. Unfortunately, I have the feeling, that Signal developers are not really looking into this issue. I mean, it is fine, they are developing new features, especially crypto currency support, but this issue need their attention.

I propose we start replying to Signal official tweets and to M0xie tweets with links to this issue to get their attention and to get some kind of solution.

What do you think?

**Comment by artelse** [comment] 2021-05-18 11:35
Making this issue more public might indeed help. I have at least one colleague that is affected by this problem and it is really annoying. If the influx of Whatsapp refugees will be convinced to stay, this has to be fixed asap.

**Comment by garywheeler69** [comment] 2021-05-18 11:40
Ruu hi

**Comment by MatejKovacic** [comment] 2021-06-30 15:56
This is just un-be-f*-ing-beliveable!

The only f*-ing solution was to delete Signal account on iPhone. And then of course to link Signal Desktop with iPhone again.

And guess f*-ing what?

All messages on iPhone were deleted (OK, this was expected), but also all f*-ing messages on Signal Desktop were deleted too. All my f*-ing history.

I guess, this kind of issues are not so important. Way more important is to add some stupid crypto currency features (and I am not the onyl one saying they are stupid - Bruce Schneier has the same opinion).

This is just unbelievable. I contatced tech support months ago, no reply for several months, then some bullshit I should re-register push notifications (like I am stupid), I explained them I did this, but this was no solution, and now no voice from them for several months.

Way to go M0xie, way to go.

Sorry, but I am really mad and you (developers) should be able to understand why...

**Comment by seniorm0ment** [comment] 2021-06-30 16:04
You have to make backups.

**Comment by MatejKovacic** [comment] 2021-06-30 16:25
What the ***?

How the f* can I make backup on iPhone???

Luckily, I have made a backup of .config/Signal directory... but guess what? Signal Desktop does not allow exporting messages or backuping messages!!! At all!

Now, what is happening now is really interesting.

First thing - iPhone still does not show notifications. So the problem not even persists, it is worse now because my history is f*-ing gone!

Next problem. Did I mention that Signal Desktop deleted all my history after I linked it with iPhone? Did I?

Well, the past messages are not shown, but the size of the directory `.config/Signal` is still around 4Gb. So this f*ker destroyed my history but did not freed my disk space!

Next thing... I got a message from a friend... history of our chat is gone on his device (iPhone) too!

But on the other hand - another friend told me that she still have a history of chat with me, but now there are two contacts of mine on her device (Android). Like two threads - old chat and new chat.

Totally inconsistent behavior!!! 

But OK, maybe we will get a new sticker pack or something!

P. S. Why Signal on iPhone has been asking for PIN??? I have read somewhere that this PIN is used for backup, which is automatically created. Where for Christ's sake, where is it???

**Comment by MatejKovacic** [comment] 2021-06-30 16:41
P. S. 2... a friend of mine is in one of the post Soviet countries. Which is blocking Signal. On iPhone you can enable censorship circumvention... but not on Android. There is censorship circumvention enabled "automatically".

Which means, if you register a phone number from censored country, circumvention is enabled automatically. But if you have a number from normal country and there go to country that does censorship... guess what - you just cannot enable censorship circumvention manually, and automatically it won't be enabled, because you obviously are not in country doing censorship... because you do not have the phone number from their country.

See, this is unbeatable logic. Trying to be user friendly, because users are stupid, right. And they do not need "too much" options. But in reality, you cannot normally use Signal. Because solving these problems is not important. Much more important is to have a new pack of stickers!

**Comment by MatejKovacic** [comment] 2021-06-30 16:55
So... Now I have deleted the app on iPhone, and registered again.

And now notifications are finally working!

Great solution, really. Do I get a new pack of stickers now??

But my history is gone. Unless I unzip the previously archived Signal Desktop directory in `.config/Signal`. Then I can see the chat history, but Signal Desktop is not linked to iPhone. So I guess there is a solution...

Users can install virtual machine and copy Signal Desktop directory there... and voila! Now we have a history (in virtual machine) and current messages (in host machine).

And what if the problem with notification on iPhone appears again?

No problem at all. Developers should't bother about this. Users can install another virtual machine. And then another, and another. It is a simple solution.


Just add some new sticker pack please. And throw a couple of whitepapers about crypto payments in Signal. Because you see, the purpose of signal is not to enable secure communication. Because it that would be so, notifications would work, backuping and restoring messages would work and censorship circumvention would work.

The purpose is to have new shiny stickers and go on fantasy on crypto payments. Because this is the real revolution. New stickers to shut down international spying and undemocratic regimes...

**Comment by jtigger** [comment] 2021-07-01 03:34
Whew! For a second there, I thought you were going to demand a full refund.

**Comment by denisbider** [comment] 2021-07-01 21:06
> Whew! For a second there, I thought you were going to demand a full refund.

This complete disregard for sustained problems experienced by users is a perennial problem of open source. This is why open source only ends up thriving after it's co-opted by a larger, usually psychopathic and manipulative organization.

If you want to make a good product, make a business out of it, and find a way for it to be sustainable. When users are paying you, you have a greater motivation to polish your product, *and* greater resources to achieve that.

Then, most crucially: do not sell out to Facebook for $1 billion.

My experience over the last year is that Signal appears to be going nowhere, really fast. I question whether people who develop it even still believe in its promise, or if they want the world to be controlled by corporations that censor "harmful content", i.e. content that obstructs their plans for global enslavement.

**Comment by seniorm0ment** [comment] 2021-07-02 01:25
The issue is properly prioritizing certain stuff over others.
Things take time either way, and whike I understand and respext the things Signal and the community do, Signal's core developers seem to care more about adding major features before fixing the sustained debatably major issues experienced by many users. New features are only so good if the core services function well and properly. Otherwise users will just leave.
Not speaking specifically about the iOS issue, but even things like SMS/MMS issues and notifications issues seem to be 2 other major issues that have been experienced by users for over 5 years now on and off.

The lack of communication on this issues is also a major problem from Signal in my opinion. While I don't expext 24/7 replies from a project this large, just some messages on and off that can help users progress in bugtesting, ideas to try, if it's even being worked on or not currently.

**Comment by denisbider** [comment] 2021-07-03 04:20
> The issue is properly prioritizing certain stuff over others.

Yes.

Money is how we incentivize people to set aside work that is inspiring and fun, and instead do work that is tedious and necessary.

When no money is involved, it turns out no one does the work that is tedious and necessary.

For open source projects to do work that is tedious and necessary, typically what needs to happen is that some corporation comes in and pays someone to do it, at the cost of subverting the project for their own vision, which is generally something to do with world domination and malice.

**Comment by johncronan** [comment] 2021-08-20 03:50
This issue is really important. I've experienced it with people I know, and it's had a negative effect on our communication. So many others here are saying the same.

I don't have much to contribute, as far as bug report details. A reinstall may fix it, but I think the problem can resurface after a while. The other reports on here that are probably the same issue are, as already pointed out, #4499, and also #4852.

People with older devices shouldn't be left in the lurch. If there's a resource issue here, how about going for a grant to fund the work? And other similar usability/testing work aimed at ensuring wide compatibility, say - on the basis that it's an equity issue, and an environmental one as well.

This issue is, by now, the top one in the whole database by number of thumbs-up reactions, when you exclude feature requests. @Imperiopolis-Signal, is this on your radar? Can we get this acted upon in some way?

**Comment by Imperiopolis-Signal** [comment] 2021-08-20 05:58
We’re aware of the issue and unfortunately believe it’s a bug on Apple’s end regarding some changes they required us to make in preparation for iOS 15 support. Apple is actively working with us to resolve this and it’s definitely our top priority.

**Comment by johncronan** [comment] 2021-08-20 14:23
That's great news! Thanks for the update. I hope Apple comes through with what you need.

**Comment by ryh-cc** [comment] 2021-08-20 14:27
Finally!!! Thanks @Imperiopolis-Signal . All that was needed was tagging someone from signal :D

**Comment by YomsGH** [comment] 2021-09-14 12:15
Hi,
@Imperiopolis-Signal could you please slightly elaborate on that issue? There's one thing that puzzles me a bit. Push notifications provided by iOS should be a mechanism shared by any app using this services. But this push notification issue only seems to affect Signal, not WhatsApp iOS for instance. So what is there to Signal that makes this issue specific to Signal only?

Thanks a lot,

**Comment by eymenkurdoglu** [comment] 2021-09-24 11:55
Can the details of the iOS misbehavior/bug be shared here? If it's already tracked elsewhere, can someone post a link? Thanks!

**Comment by DuncanHills** [comment] 2021-10-17 21:04
This is still a major issue, a few folks I know have stopped using Signal because of it already. I'm also wondering what the nature of the issue is or if there is any tracking issue for it.

**Comment by NSempsrott** [comment] 2021-11-03 02:12
I would also appreciate if there could be some sort of update on this. I enjoy signal, but would like to know if I need to switch to something else, at least until it’s fixed. Can’t have none of my messages showing notifications for months more.

**Comment by JamesTBG** [comment] 2021-11-18 12:15
Only some days left, till i cancel Signal. For being a top priority there is no communication about the status of this issue. I missed messages several hours ago. Its simply not useful. Btw Whatsapp snd Wickr does work again.

**Comment by seniorm0ment** [comment] 2022-01-23 10:18
Relevant

**Comment by MatejKovacic** [comment] 2022-01-23 11:16
This is absolutely still relevant.

Besides, it is outrageous that it is not solved yet.

**Comment by robel-yemane** [comment] 2022-01-23 12:15
Relevant!

**Comment by denisbider** [comment] 2022-01-24 07:46
Everyone to whom I recommended Signal, who is using an Apple device, has already given up on Signal because of this issue. Or they open Signal, maybe, once a month, to see a pile of messages.

It appears this issue is having the desired effect, if this is to sabotage Signal and limit who would use it.

**Comment by grankko** [comment] 2022-01-27 10:36
> We’re aware of the issue and unfortunately believe it’s a bug on Apple’s end regarding some changes they required us to make in preparation for iOS 15 support. Apple is actively working with us to resolve this and it’s definitely our top priority.

Are there any news to share on this @Imperiopolis-Signal ? Looks like it's getting worse on iOS 15 for myself and most other iOS users I know

**Comment by jywarren** [comment] 2022-02-06 16:02
Hi, this is affecting a lot of at risk folks communicating in precarious circumstances; I really hope that it is soon to be fixed, as people's lives may be at risk if they cannot find a secure channel. Thank you for your hard work.

**Comment by knigma** [comment] 2022-02-07 10:14
+1

I'm seeing this issue a lot now on IOS 15.3.

**Comment by JamesTBG** [comment] 2022-02-07 16:07
All messengers which had this problem to release of ios15 are working again. Signal does not and since there is no valid backupfunction, i cannot reset my phone.
I tried everything (except phonewipe). No solution :(

**Comment by MatejKovacic** [comment] 2022-02-07 18:59
Is there any journalist who could write something about this to get their attention?

Maybe someone from Cellebrite... :)

**Comment by jywarren** [comment] 2022-02-07 23:02
Re: prioritizing this, I wonder if signal devs are really aware? I feel they would take action of they knew the severity of the issue but a big repo like this has a ton of issues and notifications. 

For what it's worth I tweeted this succinctly here, feel free to boost in case it helps:

https://twitter.com/jywarren/status/1490356241197113351

**Comment by seniorm0ment** [comment] 2022-02-08 10:26
Idk the Signal devs seem too focused on adding useless features nobody has asked for such as Mobilecoin, instead of addressing major bugs that many users have had issues with for years such as this one, and the issues with sms not always delivering which has multiple issues open naturally.
It's a shame.

**Comment by artelse** [comment] 2022-02-08 10:30
> Is there any journalist who could write something about this to get their attention?
> 
> Maybe someone from Cellebrite... :)

Make it more public might help indeed!

**Comment by denisbider** [comment] 2022-02-10 19:52
I can add also: Apple is part of the Sith Empire (so is Google), so the blocking of Signal notifications may be on purpose, and it might not be possible to do anything about it (except not use a phone that's trying to kill you, and I'm not exaggerating).

**Comment by JamesTBG** [comment] 2022-02-12 08:26
Take off you aluminium foil. Bought a iphone yesterday and transfered data from my old one. Now its working. No hidden agenda ...

**Comment by denisbider** [comment] 2022-02-12 18:02
Yeah, @JamesTBG, the censorship and deplatforming are totally for your own good. All information that is prevented from reaching you is ONLY so that your pretty little mind is safe and not exposed to distractions. Carry on, this does not lead to genocide in any way, shape or form. :)

Moron.

**Comment by T4cC0re** [comment] 2022-03-30 19:47
Seems to be a dupe of #5072

**Comment by DanielNovak** [comment] 2022-04-30 17:35
I tried everything including reinstalling Signal on my iPhone 12 Pro (latest iOS) and the notifications never make a sound and never wake up the display. I have a paired Apple Watch and it doesn't show the Signal notifications. Unlocking the display on the iPhone will make the notification appear. iMessage, Slack and other apps work just fine and deliver the notifications to the Apple Watch. I went through all possible settings and I consider myself a pro user and I can't get it to work. It used to work in the past.

**Comment by MatejKovacic** [comment] 2022-07-31 09:21
No activity, but also not solved yet.

Wonders of Signal development at it's best.

**Comment by DanielNovak** [comment] 2022-08-07 19:50
Update on my previous post here - resetting the apple watch will fix the notification issue only temporarily and the issue will come back. I am again getting no notifications on my Apple Watch - and they are now only displayed on the iPhone. Several other users are recently reporting the issue in a Reddit [thread](https://www.reddit.com/r/signal/comments/v227hj/no_notifications_on_apple_watch_since_early_may/).

**Comment by gierakMikolaj** [comment] 2022-10-03 11:58
⚠️⚠️⚠️⚠️⚠️
Missed calls happen both on iPhone and Android devices as well as missed notifications! 

It is so preposterous that such an essential feature is completely ignored. It is the building block of a messenger app and it is a shame that an app initially released in 2014 still cannot overcome it...

**Comment by T4cC0re** [comment] 2022-10-03 12:41
To add another datapoint: When transferring one iPhone to another (in my case from iPhone 12 Pro on iOS 16 to iPhone 14 Pro Max on iOS 16.0.1) the issue with missing notifications is **NOT** resolved.  
I'm confident this is something borked in Signals app data. But unless you're willing to lose all messages you can't reset this.

**Comment by MatejKovacic** [comment] 2023-01-01 15:46
I agree that this issue should be closed, because we have a viable solution. Instead of iPhone, we can use Android, and the problem is solved.

Thanks to the developers for their effort and time investment into this issue.

**Comment by jimio-signal** [comment] 2023-03-08 18:03
dropping my note from #5148 on here too:

hey all! we’ve made some improvements to notification reliability recently, and I’m wondering if the folks that were having problems in this thread could update to the latest version from the appstore, launch the app, and see if it puts you back in business 😎

if not, you might also try manually navigating to _Settings / Notifications / Re-register Push Notifications_

but, we’d love to see some updated [debug logs ](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#ios_debug)from y’all if the problems persist. thanks! 🙏

**Closed** 2023-03-10 21:53 UTC
