### ISSUE TITLE
no notifications anymore

### ISSUE THREAD

**Issue by jovh** [signalapp/Signal-iOS#5280] opened 2022-03-01 17:58 UTC
hi - me and mu friend aren t receiving no more notifications when a message comes in... we need to open the app to know whether there are new messages

**Comment by theschweitz** [comment] 2022-03-08 20:18
any update on this? Experiencing the same issue. they pushed an update that still hasn't fixed it.

**Comment by jovh** [comment] 2022-03-08 20:35
i ve sent an email on support.signal.com - it seems that notifications work with wifi but not with 4g - even if data is enabled in the settings

**Comment by T4cC0re** [comment] 2022-03-30 19:45
Seems to be a dupe of #5072

**Closed** 2022-06-05 22:21 UTC
Labels: wontfix
