### ISSUE TITLE
Cloning Issue

### ISSUE THREAD

**Issue by ZaynaxiOSDev** [signalapp/Signal-iOS#5520] opened 2023-01-04 10:47 UTC
I was trying to clone the project using the terminal. Seems like some files are missing over here.

<img width="1025" alt="Screenshot 2023-01-04 at 3 53 55 PM" src="https://user-images.githubusercontent.com/89276510/210538007-ed8a6c4e-ea85-47ce-9571-8d6fcb71a6d0.png">

While trying to make dependencies, found this error:

<img width="1016" alt="Screenshot 2023-01-04 at 3 54 49 PM" src="https://user-images.githubusercontent.com/89276510/210538733-59b6d63f-6b08-4222-830d-b2a93d591fba.png">

Seems like there is an issue with the pod. So I tried this: 

<img width="1319" alt="Screenshot 2023-01-04 at 3 55 56 PM" src="https://user-images.githubusercontent.com/89276510/210538878-2a8529fb-6c02-411d-9789-8bed3b1b04f9.png">

**Comment by u32i64** [comment] 2023-01-04 19:51
I think the reason for this is that the https://github.com/signalapp/Signal-Pods repository has not been updated yet to correspond to the latest version pushed to this repository, likely because the version in this repository hasn't been released (even in beta) yet.

See [this post in Signal Community](https://community.signalusers.org/t/fetched-in-submodule-path-pods-but-it-did-not-contain-c9e3d6e/35904/2) for a similar situation that occurred in the past. (Note that not everything written there may apply now, particularly regarding `release/...` branches, and e.g. the main branch is now called `main`.)

You may be able to resolve this by switching to the latest 6.6.x.y(-beta) version instead via a tag, then running `make dependencies`.

---

It seems like this may be a duplicate of your previously created issue, #5517?

**Comment by u32i64** [comment] 2023-01-05 13:55
Someone tried cloning and building again and it appears to work now (which makes sense as https://github.com/signalapp/Signal-Pods was updated recently).

So you can try again with the latest version now.

**Comment by EvanHahn-Signal** [comment] 2023-01-05 20:00
I believe this is should be fixed! Closing.

**Closed by EvanHahn-Signal** 2023-01-05 20:00 UTC
