### ISSUE TITLE
PIN creation failed

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-iOS#5196] opened 2021-11-16 17:44 UTC
delete

**Comment by thegranddesign** [comment] 2021-11-17 05:01
Duplicate of #4468 

Please post there with any additional information.

**Comment by thegranddesign** [comment] 2021-11-17 05:04
Pinging recent committers: @michelle-signal @Imperiopolis-Signal this vital component has apparently been broken for _months._  How has this not been moved to the "critical to fix" list?  This prevents _anyone_ with a PIN block from restoring their account without resetting it.

**Comment by thegranddesign** [comment] 2021-11-17 05:06
BTW I'm ready, willing, and able to send any additional information necessary to help diagnose the issue if it's not clear from what has already been posted.

**Closed** 2022-01-30 06:55 UTC
Labels: wontfix
