### ISSUE TITLE
iPadOS share sheet « send » button missing in landscape 

### ISSUE THREAD

**Issue by tutis** [signalapp/Signal-iOS#4435] opened 2020-04-13 08:57 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the share sheet to signal from any app with an iPad running iPad OS 13 in landscape mode the UI is broken and the send button unavailable 

### Steps to reproduce
-  open any webpage in Safari (or any other iPadOS app)
- turn ipad to landscape 
- open share sheet to Signal

**Actual result:** No send button is available, message cannot be sent

**Expected result:** send button should be available, as when the ipad is turned in portrait mode

### Screenshots

![IMG_0726](https://user-images.githubusercontent.com/5681030/79107660-19758800-7d75-11ea-8573-a9c808049ea7.jpeg)

### Device info

**Device**: iPad Pro 9.7

**iOS version**: 13.4.1

**Signal version:** 3.7.1.0

**Comment by XxBlackHatxX** [comment] 2020-04-20 04:30
I’ve been having this issue on my iPad Pro 2018 for a while as well. It doesn’t matter if it is landscape or portrait. Bluetooth keyboard or virtual. Mine never shows the send button or the text field. This even happens on my iPhone sometimes.

**Comment by ventz** [comment] 2020-04-21 18:15
I am very surprised and saddened at how long this has been an issue, and how many github issue tickets/support emails there have been around it.

It seems like a very significant/critical app problem that really should be prioritized in some way over "miscellaneous" and "fun features".

Here are a few more screenshots showing the problem in landscape mode (the way most users use ipads):

![IMG_0006](https://user-images.githubusercontent.com/901168/79898854-ecab1b80-83d9-11ea-8f15-3e7f89d59998.jpg)

and

![IMG_0003](https://user-images.githubusercontent.com/901168/79898849-eb79ee80-83d9-11ea-979f-1ee4a69ccc6c.jpg)



vs, here is a "working" version of it in portrait mode:

![IMG_0004](https://user-images.githubusercontent.com/901168/79898953-0e0c0780-83da-11ea-9d66-807993f518e2.PNG)


ping @Imperiopolis-Signal @charlesmchen-signal @michaelkirk-signal

**Comment by ventz** [comment] 2020-04-21 18:26
A list of other threads:

https://github.com/signalapp/Signal-iOS/issues/4392
and
https://github.com/signalapp/Signal-iOS/issues/4345
and
https://github.com/signalapp/Signal-iOS/issues/1086


Old threads:
https://github.com/signalapp/Signal-iOS/issues/302
and
https://github.com/signalapp/Signal-iOS/issues/937
and
https://github.com/signalapp/Signal-iOS/issues/696
and
https://github.com/signalapp/Signal-iOS/issues/1362
and a few "tracker" threads like:
https://github.com/signalapp/Signal-iOS/issues/539
and
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-2-35-release/5883

**Comment by 211217613** [comment] 2020-04-21 19:42
also here https://community.signalusers.org/t/ios-share-sheet/13071/4

**Comment by XxBlackHatxX** [comment] 2020-04-22 01:19
> I would like to think that the devs are busy triaging high priority issues and adding much needed functionality.

Like changing the app’s color to a slightly different shade of blue. Not will features like adding a VC button like on android or fixing the calls that that it doesn’t turn off speaker when switching between video and audio only. Security should be top priority but we need a month spent on providing polish. Because it makes using the app unpleasant.

**Comment by guger** [comment] 2020-04-26 16:30
I'm facing the same issue: iPad Pro 12.9, iOS 13.4.1.

**Comment by 211217613** [comment] 2020-04-28 03:43
So I just experienced this in a different app.  I have trello app on my iPad and I save websites to specific boards. When opening the share sheet for Trello I got the same problem.

Meaning... this might be an iOS problem.

**Comment by XxBlackHatxX** [comment] 2020-04-28 03:47
> So I just experienced this in a different app. I have trello app on my iPad and I save websites to specific boards. When opening the share sheet for Trello I got the same problem.
> 
> Meaning... this might be an iOS problem.

If that is the case then everyone should report the bug to apple via the feedback assistant app or [website](https://feedbackassistant.apple.com/).

**Comment by ventz** [comment] 2020-04-28 06:19
It could be that the app needs to be updated for the changes in UI/framework for ios/ipad 11, 12, 13+. But that said, this is still something that most apps don’t have as a problem, so I would not point the finger at apple in this case.

**Comment by tutis** [comment] 2020-04-28 07:37
It would be great if one of the devs could reply on this thread, or maybe even just assign this for review (currently showing as unassigned). UI bugs should be easier to fix than underlying crypto implementation, but I suspect fixing UI bugs doesn’t carry the same prestige...

**Comment by cacaosteve** [comment] 2020-05-04 22:26
Does it help if you rotate the iPad or let it lock and then unlock it?

**Comment by XxBlackHatxX** [comment] 2020-05-04 22:28
> Does it help if you rotate the iPad or let it lock and then unlock it? I am trying to debug it but oftentimes I get an unrelated error when I rerun the application Fatal error: [KeyBackupService.swift:371 decrypt(keyType:encryptedData:)]: failed to decrypt data: file

Not when I have tried before.

**Comment by 211217613** [comment] 2020-05-05 15:18
> Does it help if you rotate the iPad or let it lock and then unlock it? I am trying to debug it but oftentimes I get an unrelated error when I rerun the application Fatal error: [KeyBackupService.swift:371 decrypt(keyType:encryptedData:)]: failed to decrypt data: file

Yea, rotating fixes it for me. I have seen this happen on other apps on my iPad mini too. 

I usually have the split keyboard setup. So I'm not sure if this happens on other keyboard layouts.

**Comment by guger** [comment] 2020-05-05 15:23
> Does it help if you rotate the iPad or let it lock and then unlock it? I am trying to debug it but oftentimes I get an unrelated error when I rerun the application Fatal error: [KeyBackupService.swift:371 decrypt(keyType:encryptedData:)]: failed to decrypt data: file

Yeah, after rotating the message bar and the send button are shown!

**Comment by ventz** [comment] 2020-05-08 02:12
Just to clarify and so that there's no confusion:

1.) landscape -> portrait = "Send" button shows up *in* portrait (but not landscape)

vs

2.) portrait -> landscape _OR_ keeping in landscape (which most iPad users do, especially in the past year or so with keyboards) =  NO "Send" button. **<-- This is the problem**

You can see this in the screenshots I posted: https://github.com/signalapp/Signal-iOS/issues/4435#issuecomment-617329268

**Comment by 211217613** [comment] 2020-05-08 20:08
> Just to clarify and so that there's no confusion:
> 
> 1.) landscape -> portrait = "Send" button shows up _in_ portrait (but not landscape)
> 
> vs
> 
> 2.) portrait -> landscape _OR_ keeping in landscape (which most iPad users do, especially in the past year or so with keyboards) = NO "Send" button. **<-- This is the problem**
> 
> You can see this in the screenshots I posted: [#4435 (comment)](https://github.com/signalapp/Signal-iOS/issues/4435#issuecomment-617329268)

I might have remembered seeing it in portrait mode too. But I'm almost always in landscape mode. So I can verify that #2 is the issue.

**Comment by Dovizu** [comment] 2020-05-30 18:19
Can confirm this is an issue, basically prevents me from using Signal to share stuff. Very annoying.

**Comment by denver-s** [comment] 2020-05-30 18:22
Same on iPhone 8 plus 

![image](https://user-images.githubusercontent.com/31325316/83336368-27df1b00-a2b3-11ea-9aaf-6d7fa9675a3e.png)

Using Signal 3.9.0.14

**Comment by u32i64** [comment] 2020-05-30 18:31
Related/same issue: https://github.com/signalapp/Signal-iOS/issues/4171.

**Comment by ventz** [comment] 2020-05-31 02:25
@Dovizu @211217613 @denver-s @u32i64 Please thumb up original poster’s issue — hopefully this will eventually gain enough “traction/attention” that someone will give a crap.

It’s especially insulting seeing app update messages from Signal that say things like “wheels of progress never stop turning”, while basic things like this are broken.

**Comment by Dovizu** [comment] 2020-05-31 02:56
Yea in general I find the lack of interaction with the Signal team in the forum and the lack of transparency regarding what’s on the roadmap quite disappointing. 

This basic function is broken for many versions now, I don’t even see any acknowledgment that it’s being worked on.

**Comment by ventz** [comment] 2020-05-31 03:04
@Dovizu Yes - completely agree.

**Comment by Dovizu** [comment] 2020-06-02 03:58
3.10.0.6 beta testing just came out, the Send button is still missing on iPad. 
Can anybody working at Signal comment on what the priority is to fix this?

**Comment by Imperiopolis-Signal** [comment] 2020-06-02 04:17
We're aware of the issue, but it ultimately comes down to a bug in iOS. We've been working on ways to workaround Apple's bug, but I don't know when we'll have something for you. For now, rotate your device to portrait if you want to share something.

**Comment by ventz** [comment] 2020-06-02 04:21
@Imperiopolis-Signal Nora - thank you for the information. 

With a keyboard case/official keyboard, it can be quite frustrating. This is definitely not a “once in a while” feature but a “many multiple times per day” thing. Hopefully a solution can be found soon.

**Comment by Imperiopolis-Signal** [comment] 2020-06-02 04:24
As a daily user of an iPad with a magic keyboard, I understand your frustration. We're definitely working on it, it's just not as easy a fix as it may seem on the surface.

**Comment by Dovizu** [comment] 2020-06-02 04:49
Thank you for taking the time out to respond. I hope this sees a fix soon from Apple.

**Comment by Mihahn** [comment] 2020-06-26 21:51
Still not fixed in iOS 14.0 (b1).

Good job Apple...

**Comment by jackcavanaugh** [comment] 2020-07-30 20:33
+1 on this issue (iPad Pro, iPadOS). Came to report and found this existing submission

**Comment by bac** [comment] 2020-08-13 19:27
> Does it help if you rotate the iPad or let it lock and then unlock it?

Sometimes rotating to portrait will help.

Other times rotating to portrait will delete any text I’ve added.

**Comment by IsaiahJTurner** [comment] 2020-08-31 22:51
Can the send button simply be moved to the top?

**Comment by 211217613** [comment] 2020-09-04 20:13
> Still not fixed in iOS 14.0 (b1).
> 
> Good job Apple...

I think we might have to live with this for years unfortunately, unless iOS exposes APIs that lets you modify the share sheet.

**Comment by Dovizu** [comment] 2020-09-04 20:45
I just find it difficult to believe that Signal cannot get this fixed when no other messenger apps have this problem...
Facebook Messenger/Telegram, all have share sheet windows that work just fine...

These other apps have the "Send" button as a toolbar item at the top right, so the question is why can't Signal also just do that as a workaround.

**Comment by XxBlackHatxX** [comment] 2020-09-04 23:07
> I just find it difficult to believe that Signal cannot get this fixed when no other messenger apps have this problem...
> Facebook Messenger/Telegram, all have share sheet windows that work just fine...
> 
> These other apps have the "Send" button as a toolbar item at the top right, so the question is why can't Signal also just do that as a workaround.

Simply they have a small team and are more focused on the Android app then the iOS app and new features. Hopefully they will spend time doing a complete overhaul on the app so that everything will work. I’m hoping since Mac Catalysts makes turning an iPad app into a Mac app easy they will be more inclined to put more time into the iOS versions of the app so that everyone can benefit.

**Comment by guger** [comment] 2020-09-14 06:58
It works now. Why is this issue not closed?

**Comment by ventz** [comment] 2020-09-14 22:59
@guger Just updated to the latest client on the ipad pro -- while I can see the button, when sharing an image and adding some text, the button itself is not doing anything...

**Comment by Dovizu** [comment] 2020-09-15 00:33
@guger not working on mine either, how does yours work?

**Comment by guger** [comment] 2020-09-15 06:43
It's working for me, but it still has some bugs ...

![image](https://user-images.githubusercontent.com/16765393/93175135-749a1500-f72f-11ea-9aad-d754af1f0c5a.jpeg)

**Comment by Dovizu** [comment] 2020-09-15 15:26
@guger that’s strange, I see that you have a 12.9in iPad Pro, wonder if that makes a difference...

**Comment by ventz** [comment] 2020-12-08 16:21
This is again now broken in the latest version...

**Comment by XxBlackHatxX** [comment] 2020-12-08 17:07
@ventz I understand your frustration since I am a keyboard iPad user. But they’ve already said that it’s gonna be a while before it is fixed. It’s just not a priority to them. For now just use portrait orientation when using the share sheet.

**Comment by ventz** [comment] 2020-12-09 00:11
@XxBlackHatxX It was working until this past (or the previous) version. It's just frustrating for something as large/significant as signal not to work one such a mainstream platform. At this point ignoring the iPad (or Apple watch) is like ignoring Android users...

**Comment by Imperiopolis-Signal** [comment] 2020-12-09 00:52
We're not ignoring this issue, and it has not been fixed – if it was working for a bit it was just luck. As has been mentioned in this thread several times already, this is a bug in iOS, not a bug in the Signal app. We could work around it before Apple fixes it by entirely redesigning our sharing experience, but iPad users make up less than 1% of Signal users so no, it's not super high on our list of priorities, especially when there's such an easy workaround –  turn your iPad to portrait for a second to share. As I also mentioned, I'm someone who uses Signal on an iPad pro with a keyboard every day, I understand the pain of this issue. It's just not a straightforward fix.

**Comment by Dovizu** [comment] 2020-12-09 02:49
Are there any findings on product advocacy from different types of
users? For example, maybe some users are more vocal/influential that
bring in more user growth. Just curious. 

On December 9, 2020, Mihahn <notifications@github.com> wrote:
> We're not ignoring this issue, and it has not been fixed – if it was
> working for a bit it was just luck. As has been mentioned in this
> thread several times already, this is a bug in iOS, not a bug in the

> Signal app. We could work around it before Apple fixes it by entirely

> redesigning our sharing experience, but iPad users make up less than

> 1% of Signal users so no, it's not super high on our list of
> priorities, especially when there's such an easy workaround – turn
> your iPad to portrait for a second to share. As I also mentioned, I'm

> someone who uses Signal on an iPad pro with a keyboard every day, I
> understand the pain of this issue. It's just not a straightforward
> fix.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/signalapp/Signal-iOS/issues/4435#issuecomment-
741347233>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAZORK5HSNTDYCB5PIAEV33ST3C67ANCNFSM4MG2EQFQ>.

**Comment by ventz** [comment] 2020-12-09 03:51
@Imperiopolis-Signal As a fellow iPad user, I am sure you also understand that this is not ideal, to say the least, As you probably know already, many users utilize their iPads/iPads Pros with keyboards as their primary (personal and/or work) devices for 12-15+ hours per day, and share hundreds of times as Signal is used similar to platforms like Slack/MS Teams. (Clearly on some level this is also Signal's goal with the recent features and additions, like group chat/mentions/etc). For an app to require turning the device around (temporary is one thing, but it's been >12+ months) would be about the equivalent of saying "every time you want to hit enter on your computer, unlock your monitor, turn it 90 degrees, hit enter, and re-lock your monitor...sure it "works", but it's also a bit insane. It's difficult to understand why this is only an issue for Signal's UI implementation...no one is saying that core/significant functionality should be back burnered to fix a sharing feature, but seeing Signal iOS/iPad releases with things like "added reaction support for new emojis" while hearing that a much more significant feature (which is currently an impacting bug) will take some time is just frustrating. Obviously this is a free app, a free service, and we are discussing this on github and not due to a 250K/year support contract, but on some level at some point this feature has to make it to some "to-do" list with some priority on it that is higher than emojis, pinning conversations, and other such features.

**Comment by Imperiopolis-Signal** [comment] 2020-12-09 04:25
> at some point this feature has to make it to some "to-do" list with some priority on it that is higher than emojis, pinning conversations, and other such features.

All of the things you're listing are things that took us a few hours to do, they're not where the vast majority of our time is or has been invested. As with all software projects, there's always a lot happening under the hood you don't immediately see. We've spent weeks attempting to fix this sharing issue – it's not like we've put no time into it. If there was a straightforward fix, it would already be fixed. Unfortunately, there is a bug in Apple's software that makes this *very* hard to fix and at some point the time investment becomes not worthwhile for the scale of the bug. We're a small team of 3 people, and we have to move on and work on more important things. We'll certainly circle back to this in the future, unless Apple fixes it on their end first, but we can't really provide any promise on when that will be.

All that said, Signal is open source. Anyone can try and fix this and open a PR if you think we're not giving it enough priority – we'd gladly accept such a fix.

**Comment by ventz** [comment] 2020-12-09 04:33
> We're a small team of 3 people

WOW...

**Comment by XxBlackHatxX** [comment] 2020-12-09 04:44
We appreciate all that Nora and the rest of the team do. I will say this again it’s worth submitting a feedback issue to Apple. via the feedback assistant app on beta or [their website](https://feedbackassistant.apple.com/)

**Comment by ventz** [comment] 2020-12-09 05:07
@XxBlackHatxX Sadly, while the intention (re:feed back to Apple) is good, I can definitely tell you that it will not accomplish anything.

We have dedicated on-site Apple engineers for support due to the large hardware deployments, and for things like instant kernel panic+reboot when plugging in a 5K display to *thousands* of systems -- nothing significant has been done.If this really is a "bug" (and I suspect it's more of an "improvement" per Apple's view) -- it would still not even register on their roadmap.

**Comment by Imperiopolis-Signal** [comment] 2021-01-13 07:56
We've found a workaround for this issue and it is now resolved in our recently released 5.2 beta. If you’re interested in participating, join the beta group [here](https://support.signal.org/hc/en-us/articles/360007318471-).

b60ffd38a42825ea33aefd5f247b9c84e0234a21

**Closed by Imperiopolis-Signal** 2021-01-13 07:56 UTC

**Comment by ventz** [comment] 2021-01-13 23:21
![IMG_63F5BE1EE4A9-1](https://user-images.githubusercontent.com/901168/104521949-f0b44480-55cb-11eb-943a-ebaf1997e24c.jpeg)

Looks like the app update from today lists it (last item). Sadly, after updating/restarting the app - it looks like it's still not working :( 
(Test from Reddit article -> formats msg, tapping blue share arrow/"plane" bottom right does not execute)

**Comment by sanketgarade** [comment] 2021-01-14 00:16
Thanks! It works for me on an iPad Air 4. Here is a snap of a note I sent to myself to test it.

![image](https://user-images.githubusercontent.com/74632379/104527856-1a5f8100-5649-11eb-9881-05b7fa283920.jpeg).

**Comment by Dovizu** [comment] 2021-01-14 05:50
Wonderful! Works like a charm for me now!

**Comment by ventz** [comment] 2021-01-14 18:06
Looks like v5.2 works *after* a reboot!!
