### ISSUE TITLE
Feature Request: Extend selection of times for disappearing messages

### ISSUE THREAD

**Issue by mjklemm** [signalapp/Signal-iOS#5268] opened 2022-02-16 07:28 UTC
The list of options for picking a custom expiration time for disappearing messages only has seconds, minutes, hours, days, and weeks.  It would be good to also have years to pick.  That would greatly simplify purging very old messages from chats.

It would even be nice to have more than 1, 2, 3, and 4 as numeric selector.

This feature request might apply to all clients.

**Comment by Cerberus0** [comment] 2022-02-17 07:40
Hi @mjklemm,

Welcome to the Signal iOS issue tracker. Please use the provided [issue template](https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/ISSUE_TEMPLATE/bug_report.md) when submitting new issues. If you feel like you are unable to make an idea fit within the confines of the template, that might be a sign that you are about to submit something that isn't a bug. 

Note that this issue tracker is [only meant for bug reports](https://github.com/signalapp/Signal-iOS/blob/master/CONTRIBUTING.md#issues). Bugs should only be reported for existing functionality that does not work as intended. All other discussions/questions/requests belong on the [Signal Community forum](https://community.signalusers.org/), which you can easily join with your existing GitHub account. Please close this GitHub issue and submit your feature request there:

* https://community.signalusers.org/c/feature-requests/17

Thanks!

**Comment by SigniOS** [comment] 2022-02-18 02:02
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by fingahoverit** [comment] 2022-04-01 07:29
this feature request also in this previous issue : https://github.com/signalapp/Signal-iOS/issues/5251

**Closed** 2022-06-07 12:44 UTC
Labels: wontfix
