### ISSUE TITLE
Signal app taking a big bite of battery in the name of ‘Background Activity’

### ISSUE THREAD

**Issue by iHarryme** [signalapp/Signal-iOS#4486] opened 2020-06-21 07:10 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal app taking a big bite of battery in the name of ‘Background Activity’

**Actual result:** Signal is taking a chuck of battery on the name of ‘Background Activity’

**Expected result:** When I close the app I expect it not to run or run and take only small portion of the battery!

### My story
I turned off Background refresh for the app, yet it’s running and my battery health reduced to 93% from 98%! I contacted Apple support and they told it will still run, as it’s a messaging app it checks for new messages or calls. In my case I use Signal on iPhone and Mac. When I am using on Mac I don’t need it to run on iPhone and vise versa. However on Mac we can quit the app and it won’t run, not the same case with iOS. Apple support told that the only way is to uninstall the app on iPhone while using on Mac. However if you turn off WIFI, it won’t run to take a bite of your battery. If you want other internet apps to run, you gotta use mobile data and turn off data for Signal in Cellular settings.

### Screenshots

![7126FCDF-88DD-4F08-B0ED-70C372DE3319](https://user-images.githubusercontent.com/45716271/85218756-eaa21080-b3ba-11ea-9a78-17a811d6094a.png)
![EB417221-05A1-4E7B-BE74-03DFE076CA1C](https://user-images.githubusercontent.com/45716271/85218760-f097f180-b3ba-11ea-8aaf-df743fc8d257.png)
![A4E45CB6-11B0-4363-AEF3-E8288ED7FE9D](https://user-images.githubusercontent.com/45716271/85218761-f1c91e80-b3ba-11ea-89fd-06e917bdcaef.png)

### Device info

**Device**: iPhone 11

**iOS version**: 13.5.1

**Signal version:** 3.10.5.3

### Link to debug log

https://debuglogs.org/0dc1b1b604d76cff9941b698b5291efaa32b25873c4c04c2dc4d73ef6d3c5231.zip

**Comment by Imperiopolis-Signal** [comment] 2020-06-29 23:49
I believe this was a dupe of #4471. Please re-open if this is an isolated issue still occurring in 3.12

**Closed by Imperiopolis-Signal** 2020-06-29 23:49 UTC
