### ISSUE TITLE
Voice message send from pixel 3 plays 2x the normal speed

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-iOS#4184] opened 2019-04-30 09:59 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Voice messages from pixel 3 plays double the speed. If you send back the exact same message than it plays normal on pixel 3.

### Device info

**Device**: iPhone 7

**iOS version**: latest

**Signal version:** latest

### Link to debug log

https://github.com/signalapp/Signal-Android/issues/8543

https://debuglogs.org/5526e0c3fbc1190dcbc094f4a71ba2b2bf4c5bc68b3c93dbbbb760eba5ccfd86.zip

**Comment by michaelkirk-signal** [comment] 2019-04-30 16:36
Dupe of https://github.com/signalapp/Signal-iOS/issues/3029, which we believe is a Pixel/Android bug.

**Closed by michaelkirk-signal** 2019-04-30 16:36 UTC
