### ISSUE TITLE
Unable to see what I am typing [iPhone 7]

### ISSUE THREAD

**Issue by sargupta** [signalapp/Signal-iOS#4698] opened 2021-01-11 05:34 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can not see what I am typing while texting someone in Signal

### Steps to reproduce
- Open Signal app in iPhone 7 
- Try to write a Message to someone in your contact.
- 
**Actual result:** I keep seeing my keyboard rather than what I am typing. 

**Expected result:** I should be able to see and read what I am texting whenever I type something. 

### Screenshots
In the attached file, though I have typed something but can't see it. 
![IMG_85B7923E9D35-1](https://user-images.githubusercontent.com/28517335/104149476-4df99b80-53fc-11eb-90e4-98fa8902faa6.jpeg)
![IMG_0135](https://user-images.githubusercontent.com/28517335/104149591-c4969900-53fc-11eb-81d9-aa056daa6925.jpg)

### Device info

**Device**: iPhone 7

**iOS version**: 14.3

**Signal version:** 5.0.3

**Comment by Genis-Sage** [comment] 2021-01-11 09:46
hey @sargupta 

i guess this is a duplicate of #4672

also relevant:
#4632 and #4640

**Comment by Imperiopolis-Signal** [comment] 2021-01-11 16:52
Please update to 5.1 which we released yesterday. This issue is resolved.

**Closed by Imperiopolis-Signal** 2021-01-11 16:52 UTC
