### ISSUE TITLE
Unresponsive UI adding Photo from Photostream

### ISSUE THREAD

**Issue by HenkiedeHenkie** [signalapp/Signal-iOS#2980] opened 2018-02-05 17:43 UTC
- [ X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When Signal has no permission to pick photos from the Photostream and in the iOS settings the permission to Photos is set to "never" adding a photo in a conversation is still possible. However, instead of notifying the user that permission is needed, the app shows the photostream but tapping a photo results in no action at all. This is bad UX, as the user doesn't know what is happening, isn't able to add a photo and doesn't know that this is caused by the fact that the permission to Photos has to be set to "Read and Write" in the iOS settings of the app.

### Steps to reproduce
- Go to iOS Settings
- Tap Signal to access the specific Signal Settings
- Set permission to Photos to "Never"
- Go to Signal
- Open a conversation / start a new one
- Tap the attachment icon
- Choose Photos
- Go to a photo of your liking and press it
- Nothing happens...

**Actual result:** Nothing, just bad UX
**Expected result:** Correct behaviour should be that the user is prompted that Signal has no access to the photo stream and should allow the user to set this permission

### Device info

**Device**: iPhone 5S
**iOS version**: 11.2.4
**Signal version:** 2.19.5.0

**Comment by michaelkirk** [comment] 2018-02-05 18:05
Dupe of https://github.com/signalapp/Signal-iOS/issues/2895 which will ship in the upcoming 2.20 release.

**Closed by michaelkirk** 2018-02-05 18:05 UTC
