### ISSUE TITLE
Unable to share large images

### ISSUE THREAD

**Issue by wtangofoxtrot** [signalapp/Signal-iOS#4929] opened 2021-03-28 19:02 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Recently the ability to share large images such as RAW or large JPEGs stopped working. This is due to a new file limit restriction to sharing file sover a certain size (i cannot hsare images greater than 10mb)

### Steps to reproduce
- share a large image from photos or any other app

**Actual result:** 
- If adding the image from the signal app a preview will not be generated and the send will fail with a file too large error
- If sharing from another app the signal share will appear to crash immediately upon sharing and will take you back to the iOs share popup.

**Expected result:** Its 2021 and signal should not be restricting sharing of photos. Every dedicated APSC/Mirrorless/DSLR takes photos which are greater than 10mb and now signal cannot be used to share this media forcing users to rely on less secure methods like sms/whatsapp.

### Screenshots

![IMG_3631](https://user-images.githubusercontent.com/15003248/112764384-22c72700-8fbd-11eb-9b27-e37c0e5e8d18.PNG)

### Device info

**Device**: iPhone 11

**iOS version**: 14.4.1

**Signal version:** 5.8.0.22

**Comment by kriston13** [comment] 2021-04-06 12:14
Agreed, this is a problem. Didn't Signal used to do automatic compression of images? What happened to that?

**Comment by myspaghetti** [comment] 2021-04-08 11:21
Bug reproduced on the following device with [the following linked image (10.4MB JPEG)](https://www.flickr.com/photos/siyamalan/14764686438/sizes/o/)

### Device info

Device: iPhone 12 mini  
iOS version: 14.4.2  
Signal version: 5.8.0.22  
Debug log: [org.whispersystems.signal.shareextension 2021-04-08--10-58-01-110.txt](https://github.com/signalapp/Signal-iOS/files/6278129/org.whispersystems.signal.shareextension.2021-04-08--10-58-01-110.txt)
```
2021/04/08 10:58:02:986  🧡 [NSData+Image.m:707 -[NSData(Image) imageMetadataWithPath:mimeType:]]: Oversize image.
```

I consider this a bug and not a feature request since the "Attachment too large" message appears and disappears too quickly to read, though there are many existing feature requests for having the option to send unmodified JPEG, PNG, or RAW files that would solve this bug.

**Comment by nqnx** [comment] 2021-05-04 08:43
This is an incredible frustrating issue. Often nowadays Pictures are 12 megapixels and those cannot be sent at all with Signal. Very unhandy and makes people fall back to other messengers.

**Comment by wtangofoxtrot** [comment] 2021-05-07 01:03
Still no traction on this issue, I cant use the ios app anymore to share any photos.

**Comment by kriston13** [comment] 2021-05-07 01:37
likewise.  Between this bug, and the lack of live location, I’m getting some cranky friends wanting me to move back to WhatsApp.  

> Still no traction on this issue, I cant use the ios app anymore to share any photos.

**Comment by wtangofoxtrot** [comment] 2021-05-25 17:09
The current workaround is very convoluted, you have to download the files to photos and then use the photo picker in the signal chat to select the file/s. Only then does the share work. 

This has made signal pretty much unusable as a family chat app at this point, i guess imessage is the way to go if privacy and usability is a requirement  :(

**Comment by epvuc** [comment] 2021-05-25 19:06
> The current workaround is very convoluted, you have to download the files to photos and then use the photo picker in the signal chat to select the file/s. Only then does the share work.
> 
> This has made signal pretty much unusable as a family chat app at this point, i guess imessage is the way to go if privacy and usability is a requirement :(

This doesn't work generally, just within a certain size range, I think. It does have the benefit that you see the "Image too large" warning for very slightly longer, so that it doesn't appear to just be an app crash.

On the other hand this kind of appears to be an intentional choice on the part of Signal so I am wondering if pursuing through a channel intended for bug reports may not be fruitful.

**Comment by mailinglists35** [comment] 2021-06-23 10:35
what a crap app Signal has become. feel free to delete my remark, but you will not change the reality by deleting it.

**Comment by mailinglists35** [comment] 2021-06-23 10:42
> The current workaround is very convoluted, you have to download the files to photos and then use the photo picker in the signal chat to select the file/s. Only then does the share work. 
> 


this doesn't work for me.

**Comment by martinbarlow** [comment] 2021-06-30 17:26
hi i think it was fixed in new version!

works now for me anyway.

![9B27370E-D038-4E3E-8239-12F137225CD5](https://user-images.githubusercontent.com/2373240/124005191-14801100-d9d9-11eb-8347-5a0f13957579.jpeg)

**Closed** 2022-01-30 14:46 UTC
Labels: wontfix
