### ISSUE TITLE
Accessibility bug on Singal for iOS app version version 3.7.1 and conversations 

### ISSUE THREAD

**Issue by santiagoblue7** [signalapp/Signal-iOS#4431] opened 2020-04-11 02:47 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
On Signal for iOS, version 3.7.1, I am experiencing an accessibility issue with conversations and the VoiceOver screen reader accessibility functionality on iOS. VoiceOver will read the actual content of messages on conversations, however, it will not read who the message is from, whether it's from the sender, or receiver(s) as this also applies to group conversations. 
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

Step 1: Turn on VoiceOver by going to settings, accessibility, VoiceOver, and toggling it to on. A basic description of VoiceOver gestures is shown on this screen as well.
Step 2: Using VoiceOver gestures, open the Signal application.
Step 3: Open an existing conversation, with either a group or another individual.
Step 4: Flick around the conversation screen using VoiceOver gestures. 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
You'll notice that VoiceOver will read out the content of messages; however, it will not notify the user whether messages are from the sender, or receiver(s).   For example: (Hi!) (Hi! How are you?) 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
VoiceOver should notify the user who the messages are from, along with the content of the messages, for example, (Person 1: Hi!.) (Person 2: Hi! How are you?) instead of the existing behavior, example, (Hi!) (Hi! How are you?) 
### Device info

**Device**: iPhone X

**iOS version**: 13.4.1

**Signal version:** 3.7.1

### Link to debug log

https://debuglogs.org/1a1616137237746797221812c14150b565beb1f1c850629e592b0895b469cffb.zip

**Comment by MarcoZehe** [comment] 2020-12-16 12:53
I cannot reproduce this. In the latest version, in both group and one-on-one conversations, VoiceOver reads either "you" if it's from yourself, or the other person's name or phone number (if the person is not in your contacts).

**Comment by clementb49** [comment] 2021-01-10 12:59
I have also the bug. My device is an Iphone 12 pro with the signal app version 5.0.3.0.

**Comment by Andre9642** [comment] 2021-01-13 08:38
@MarcoZehe Are you using the beta version? Currently I am unable to reproduce the issue with the beta version (5.1.0.30). I ran into the issue with the app store version about a week ago (version 5.0.3). So seems to be fixed in 5.1 (released 3 days ago).

**Comment by MarcoZehe** [comment] 2021-01-13 09:15
@Andre9642  As I said, I could not reproduce the issue. In the beta of 5.1.0, though, this has all changed dramatically, and regardless of the message type, each message now has 3 or 4 swipe stops instead of one. So this needs to be re-done anyway, to make it more efficient. But that should probably go into a new bug. See also [this thread on the unofficial support forum](https://community.signalusers.org/t/accessibility-improvements/19259?u=marcozehe).

**Closed** 2022-01-31 08:46 UTC
Labels: wontfix
