### ISSUE TITLE
Bug in volume of a video call

### ISSUE THREAD

**Issue by davisnando** [signalapp/Signal-iOS#4922] opened 2021-03-18 19:37 UTC
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When video calling the speaker volume is low even when it's maxed out. This is because it's in calling mode. You can see this because when I try to increase my volume the call icon is shown.  When I mute myself and then unmute myself it will go to speaker mode and the volume of the call is lots and lots louder and when trying to increase my volume i can see that its now in media mode. So in my case this is know fixed when doing that.  

### Steps to reproduce
- Create a video call with someone
- Audio volume is not loud and is in calling mode
- Mute and unmute yourself
- Audio volume is louder and is in media mode 

**Actual result:** When starting a video call its in calling mode(audio). You need to mute and unmute yourself to get the expected result.
**Expected result:** Go to media mode(audio) when videocalling

I hope I explained it enough. If not just reply on this thread with the question and I will try to answer it

### Device info

**Device**: iPhone XS

**iOS version**: 14.4

**Signal version:** 5.7.0.19

**Comment by 211217613** [comment] 2021-03-27 01:17
I think you are describing the same issue I'm seeing. It's not that the call volume is low, it's that during the video call the speaker is not activated. I also don't have the option to toggle the speaker on or off or manipulate the audio output during a video call.

I haven't tried the mute and unmute your self option but I'll try it out and see if that works.

**Comment by joshaidan** [comment] 2021-04-27 16:24
I'm experiencing the same issue on iOS. Muting and un-muting the microphone seems to correct it. (The speaker starts working once the mic is muted).

**Comment by frfritz** [comment] 2021-05-03 09:38
Same Issue for me on iOS 14.4.2 on an iPhone SE

**Comment by wtangofoxtrot** [comment] 2021-05-07 01:06
This looks like a duplicate of https://github.com/signalapp/Signal-iOS/issues/4909, please confirm and close to reduce noise here.

**Closed** 2021-05-07 03:25 UTC

**Comment by NickDinges** [comment] 2021-05-26 09:46
I have the same problem on Windows 10 Pro x64 - 21H1 with all patches installed using Signal 5.3.0. I use a Blue Yeti X. The sound is not loud enough on video calls, but If I use Youtube it has 5 times the volume than in the video call.
