### ISSUE TITLE
‘Phantom’ notification badge on app icon

### ISSUE THREAD

**Issue by AusWab** [signalapp/Signal-iOS#4560] opened 2020-09-17 16:37 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Notification badge on app icon with no new messages

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![5AF61BF0-A21C-4A85-BC73-9CDDDE9745DA](https://user-images.githubusercontent.com/65003762/93500721-605f3f00-f90c-11ea-9ace-c216876fd25a.jpeg)

### Device info

**Device**: iPhone 11 Pro

**iOS version**: iOS 13.7

**Signal version:** 3.17.1.1

**Comment by dantler** [comment] 2020-10-02 20:44
Is this a duplicate of #4526 ?

**Closed** 2022-01-31 13:48 UTC
Labels: wontfix
