### ISSUE TITLE
Broken links when at the end of a message requiring the 'see more' click

### ISSUE THREAD

**Issue by lewisoconnor** [signalapp/Signal-iOS#5340] opened 2022-05-04 19:33 UTC
If a link is placed at the end of a message and is cut off (needing to click 'see more'), clicking it will fail as only the partial URL is loaded. 

For example:

Www.googl**SEE MORE**

Will only load 'www.googl' in the browser instead of the expected www.Google.com.

**Comment by evnik** [comment] 2022-05-20 05:28
This seems to be fixed in 1689aec8c6897d947f933f158c9d5a129ff9e62c and the fix is available in 5.38 version of the app

**Comment by evnik** [comment] 2022-05-20 05:41
BTW, this looks like a duplicate of #4394

**Comment by max-signal** [comment] 2022-06-04 00:08
Yep, this should be fixed by 1689aec8c6897d947f933f158c9d5a129ff9e62c. Please reopen the issue if you’re still seeing it in the latest version of the app.

**Closed by max-signal** 2022-06-04 00:08 UTC
