### ISSUE TITLE
volume buttons no longer usable to make a photo in recent singal

### ISSUE THREAD

**Issue by arekm** [signalapp/Signal-iOS#4181] opened 2019-04-25 06:59 UTC
- [x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

signal for ios 2.39.0.5 (and version before)

Describe here the issue that you are experiencing.

### Steps to reproduce
- open signal, discussion with someone
- try to send a photo, enter into photo mode
- press volume buttons on side of iphone to make a photo

**Actual result:** 

Volume changes up/down depending on pressed button.

**Expected result:** 

Photo should be taken instead. That worked in earlier versions of signal.

### Device info
**Device**: iphone xs

**iOS version**: 12.2

**Signal version:** 2.39.0.5

btw. idevice XY thing and ios version should be also reported in signal "About" to make easier proper bug reporting. Have no idea where proper "idevice xyz" is in ios.

**Comment by u32i64** [comment] 2019-04-25 11:55
> btw. idevice XY thing and ios version should be also reported in signal "About" to make easier proper bug reporting. Have no idea where proper "idevice xyz" is in ios.

I don't think so. Why would you need every app showing your device name in their settings?

This information is easily found in **`Settings` > `General` > `About` > `Model Name`, `Model Number`**.

If the About UI has version and model numbers separate on the top of the list (which I think landed in iOS 12.2), you can also tap `Model Number` to see it in another format (you can also do this to `Software Version` to see build number :wink:).

**Comment by arekm** [comment] 2019-04-25 12:04
Ok, then add that path to github issue template :)

**Comment by ethylmorphine** [comment] 2019-04-25 17:10
iPhone 7, iOS 12.2, Signal 2.39.0.5.
I can confirm this issue.

![Image](https://i.imgur.com/8ISRGtF.jpg)

**Comment by ethylmorphine** [comment] 2019-04-26 02:53
UPD: volume buttons have no action at all in camera mode on Signal 2.39.0.6.

**Comment by denver-s** [comment] 2019-06-06 11:47
This has been fixed in version 2.40

**Comment by michaelkirk-signal** [comment] 2019-06-12 15:36
This is fixed in the latest beta by @Imperiopolis-Signal 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Closed by michaelkirk-signal** 2019-06-12 15:36 UTC

**Comment by maartenhunink** [comment] 2020-08-18 12:07
It seems like this issue has returned. Currently it's not possible to use the volume buttons to take a photo. @michaelkirk-signal could this issue be re-opened?

**Comment by Imperiopolis-Signal** [comment] 2020-08-18 14:53
Interesting, I’m seeing the same here. For context, can you please share your iOS version? I’m suspecting this is something Apple broke in iOS 13.6

**Comment by maartenhunink** [comment] 2020-08-18 15:06
I'm on iOS 13.6.

It might have been broken before 13.6 already since I've been actively using Signal for a couple of months now but I've never been able to use the volume buttons to take photos. So potentially somewhere in iOS 13?

**Comment by nimarb** [comment] 2020-08-18 15:51
For me it works as expected on iOS 13.5, Signal 3.14.1.2, iPhone X.
