### ISSUE TITLE
Verification sms/call

### ISSUE THREAD

**Issue by Ritmjunk** [signalapp/Signal-iOS#3929] opened 2018-09-30 20:03 UTC
Bug description

Not receiving a verification sms and/or verification call.

Steps to reproduce

install the latest signal app from the App Store
fill in Country code: +32 (Belgium) + my phone number
click on register
Actual result: Not receiving a verification sms or call

Expected result: receive a verification sms or call

Screenshots

Device info

Device: iPhone X

iOS version: 12.1

Signal version: 2.29.3

**Comment by five-c-d** [comment] 2018-10-02 23:32
Possibly related?  https://github.com/signalapp/Signal-Android/issues/8148#issuecomment-426463464 , enduser with carrier OrangeBelgium had sent STOP reply to an (**un**related-to-signalapp) SMS from a Benelux service provider named CM Telecom, and this action had the side-effect of *also* preventing the enduser from receiving the SMS-or-robocall from signalapp servers.  Not sure why exactly this was happening... and may not be related to your situation, but figured it was worth mentioning.

**Comment by Ritmjunk** [comment] 2018-10-03 10:06
Maybe, I really don't know. I received a verification sms from other apps (Telegram & Line) that I tested. 
I do know that this provider Orange has sometimes a lot of problems. Several weeks ago we could not call a particular Belgian  provider from Orange...apparently someone did a manipulation in a config setting that prevented us from calling to that provider....

So maybe, someone messed it up again 😉
Everything is working fine know and I appreciate the fast response from you guys. Thanks a lot. 

Michaël

**Comment by five-c-d** [comment] 2018-10-03 11:12
Michaël, when you say "Everything is working fine" ... does that mean you DID finally receive your SMS confirmation-code, and you WERE able to install signalapp?  Or do you still need help getting it working?

**Comment by Ritmjunk** [comment] 2018-10-03 12:51
Everything works now:

Received the confirmation sms. 
Never had an issue to install the app.

**Comment by bumbleblue** [comment] 2018-10-22 18:13
Latest iOS version. Text message is working, but calls don't happen at all in the verification step. That's really unfortunate because I rely on the call for my set-up!

**Comment by synchon** [comment] 2018-10-30 13:23
Trying to register from India (and using Airtel) without success. I am not sure if the problem is with the carrier as I was using Signal on the same network, a few months back. The problem persists on the Android version too.

**Comment by abjbhat** [comment] 2018-10-31 03:34
I'm having this issue as well. Carrier is Airtel in India. No SMS or call received. Running iOS 12.1 and the latest Signal app.

**Comment by Notatechdud3** [comment] 2018-11-01 19:48
> Trying to register from India (and using Airtel) without success. I am not sure if the problem is with the carrier as I was using Signal on the same network, a few months back. The problem persists on the Android version too.

Hello Synchon

I made a topic at Signalusers: maybe you can throw in a debuglog so we can find a solution for other people?

https://community.signalusers.org/t/registering-in-india-airtel/4684

**Comment by abjbhat** [comment] 2018-11-02 00:59
@Notatechdud3 : 

Definitely not a carrier specific problem. A friend of mine tried it out in a different part of the country with a different carrier (I don't recall which one). No call or SMS received.

I should add that I am able to receive the verification calls, except that the phone call is made a few hours after the initial request. The delay is not predictable. I woke up yesterday to find 6-8 missed calls from a US number during the night. One was made while I was awake. However, by that time the code was not accepted by the Signal app.

**Comment by five-c-d** [comment] 2018-11-02 11:33
> You can get a debuglog by: signal > settings > advanced > submit debug log

My understanding is that you must Enable Debug Log as well, prior to submitting, in some cases at least (within the same submenu).  However, my understanding is ALSO that one cannot **get** into the settings menu during the registration phase, at least on signal4android... not sure about signal4ios.  

Signal4android has a newly-added feature (cf <a href="https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/RegistrationActivity.java">debugTapCounter</a>) where you can <a href="https://github.com/signalapp/Signal-Android/issues/7980#issuecomment-426762400">tap eight times on the floating phone-icon action button</a> in the middle of the screen during registration, and it will generate a debuglog.  Not sure that feature-request has been added to signal4ios yet?  

There is a special mode, entered when signal4ios fails to fully launch when being opened, <a href="https://github.com/signalapp/Signal-iOS/blob/master/Signal/src/AppDelegate.m#L379">per this code</a>, but I am not aware that there is a way said feature can be invoked 'manually' on purpose (rather than when an actual launch-failure occurs).  

This old 2014/2015/2016 signal4ios issue-report suggests there is a place on the filesystem where the debuglog exists, assuming it has been enabled at some earlier point: https://github.com/signalapp/Signal-iOS/issues/39  ...is there a way to access that file directly, if it exists, or does that require jailbreaking the iPhone in question?

**Comment by abjbhat** [comment] 2018-11-03 00:49
@Notatechdud3 

You asked about the delay ... I made a request at 15:00 (GMT+5:30) on 2-Nov. Two calls came for verification at 02:19 and 02:20 (GM+5:30) on 3-Nov.

As regards the debug log, I can't get to them as I'm not signed in yet. 

Hope that helps.

**Comment by synchon** [comment] 2018-11-03 07:18
The delay for me is roughly around 5-6 hrs. And yes, multiple calls as stated by @abjbhat, is true for me too.

**Comment by Notatechdud3** [comment] 2018-11-04 18:37
@abjbhat, @synchon 

Both of you only made **1** request for a call and eventually got **2**?

Could you tell me from what phone number the call was coming from?

**Comment by abjbhat** [comment] 2018-11-05 13:32
@Notatechdud3 

Here are the numbers I got the call from. Times are in GMT+5:30
1 call: +1 (919) 590-3874‬ 15:06 2018-Nov-04
2 calls: ‭+1 (425) 276-6197‬ 02:20, 02:19 2018-Nov-02

**Comment by Notatechdud3** [comment] 2018-11-05 17:36
@abjbhat, thanks. 

Did you try to create the debuglog as @five-c-d posted?

**Comment by five-c-d** [comment] 2018-11-06 18:39
signal4ios does not have a way to capture debuglogs during the registration-phase yet, as I understand it, so abjbhat cannot get the debuglog without swapping his simcard temporarily into an android-device or similar kind of quasi-workaround.  

@michaelkirk , from signal4android reviews on playStore in past week about 7% of the comments are about problems registering, up from <1% just a few weeks ago.  See list of recent conf-code complaints here == https://community.signalusers.org/t/registering-in-india-airtel/4684/10 , presumably this is a pain-point for iPhone endusers as well such as abjbhat and synchon (above).

**Comment by synchon** [comment] 2018-11-07 10:31
@Notatechdud3 These are the numbers I got calls from:
1. +1 (425) 276-6197
2. +1 (385) 626-7271

**Comment by Notatechdud3** [comment] 2018-11-08 19:35
@synchon, according to https://community.signalusers.org/t/registering-in-india-airtel/4684/14, most to all issues with India should be fixed. Could you try again and let us know please?

**Comment by synchon** [comment] 2018-11-08 19:40
@Notatechdud3 works perfectly now! Thank you! :)

**Comment by Notatechdud3** [comment] 2018-11-09 09:21
@bumbleblue, could you give us more details please?

- What is your country code?
- Who is your provider?
- How long has this issue been ongoing? 
- Is there a specific reason you need the robocall and not the text message?

**Comment by bumbleblue** [comment] 2018-11-09 09:32
Happy to!
>     * What is your country code?
+49
>     * Is there a specific reason you need the robocall and not the text message?
I'm setting up Signal for my second device which does not use a SIM. I'm using a landline/VOIP phone for that. Following instructions [here](https://theintercept.com/2017/09/28/signal-tutorial-second-phone-number/).
>     * Who is your provider?
Easybell/VOIP
>     * How long has this issue been ongoing?
It was glitchy for two days, and on the third day it magically worked!

Hope this helps!

**Comment by abjbhat** [comment] 2018-11-09 12:45
@Notatechdud3 : 

Looks like the problem is now fixed. I got the verification SMS, as did my friend. 

Thanks!

**Comment by Notatechdud3** [comment] 2018-11-09 13:18
We can close this issue now, because all problems of users have been resolved. Unless I am mistaken?

**Closed** 2018-11-09 20:54 UTC
