### ISSUE TITLE
iOS not playing animated stickers (APNG)

### ISSUE THREAD

**Issue by slichan** [signalapp/Signal-iOS#4782] opened 2021-01-16 18:08 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am uploading animate stickers onto Signal from the Desktop app. The stickers move on both Desktop and Android, but it doesn't move on my iPhone XS at all. 

### Steps to reproduce
- Use the built in function for creating a sticker pack on Desktop App
- Upload it and installed it on Desktop
- Linked Desktop to iPhone

**Actual result:** The sticker is static and won't move on the iPhone
https://user-images.githubusercontent.com/11430950/104819480-a48f1d00-57e2-11eb-8355-9ba1eae6b287.mp4

**Expected result:** It should be moving 
https://user-images.githubusercontent.com/11430950/104819483-a527b380-57e2-11eb-83cc-909137156a9c.mp4

### Device info

**Device**: iPhoneXS

**iOS version**: 14.3

**Signal version:** 1.39.5 (Desktop), Also tried with 1.39.4 (desktop), iPhone version 5.2.0.4

### Link to debug log

https://debuglogs.org/4272304b77450dd4c2dd7614f8e428710c24e01b6f0f2ca4bd4d0657a761df34.zip

**Comment by romainricard** [comment] 2021-06-21 17:11
Can you share the pack? It could be a duplicate of https://github.com/signalapp/Signal-iOS/issues/4611

**Closed** 2022-01-30 15:46 UTC
Labels: wontfix
