### ISSUE TITLE
Sending Messages to Yourself Creates Duplicates

### ISSUE THREAD

**Issue by khashyarkh** [signalapp/Signal-iOS#3378] opened 2018-05-03 23:00 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Sending messages to yourself creates double messages. if u want to use this conversation for archiving, or sharing files between desktop it would be problematic.

### Steps to reproduce
- Send yourself a message (from Desktop or iOS)

**Actual result:** Double Messages, Attachments
**Expected result:** Get No Reply Back
### Screenshots
![signal-2018-05-04-032715](https://user-images.githubusercontent.com/34171942/39606563-4292dc6a-4f4b-11e8-9fb9-d829e36e750b.png)

### Device info

**Device**: iPad 2
**iOS version**: 9.3.5
**Signal version:** 2.24.1

**Comment by michaelkirk-signal** [comment] 2018-05-03 23:59
That's as intended.

dupe of https://github.com/signalapp/Signal-iOS/issues/573

**Closed by michaelkirk-signal** 2018-05-03 23:59 UTC
