### ISSUE TITLE
SSL Error on iOS13

### ISSUE THREAD

**Issue by hunttom** [signalapp/Signal-iOS#4231] opened 2019-07-29 21:05 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In IOS13, Signal has SSL issue. Exact error: "An SSL error has occurred and a secure connection to the server cannot be made."

### Steps to reproduce
- Try to send media other than text.

**Actual result:** 
Anything not text doesn't upload, instead getting an red "!" and when clicked, provides the previously mentioned error and the ability to delete or resend the message. Error is repeated when clicking "resent." This does not impact text or linked devices.

**Expected result:** Media is sent same as text.

### Screenshots

![singalerror](https://user-images.githubusercontent.com/20104558/62082560-fc1e7f00-b222-11e9-9f75-3ad8e490ca09.png)

### Device info

**Device**: iPhone 8

**iOS version**: 13.0

**Signal version:** 2.40.3.2

### Link to debug log

https://debuglogs.org/724b720c9753a65802f3228340c36f6818a0b6bf685c7a4c36e2e9e44f4527aa.zip

**Comment by 211217613** [comment] 2019-07-30 16:42
duplicate of #4224

**Closed** 2019-07-30 17:57 UTC
