### ISSUE TITLE
multi-line saved draft doesn't fit in text area.

### ISSUE THREAD

**Issue by michaelkirk** [signalapp/Signal-iOS#1185] opened 2016-05-16 20:33 UTC
### Bug description

As you type multi-line messages, the text field grows to fit them. However, when you leave the draft unsent, and come back to it later, the text field is not scaled to fit the multi-line saved draft.
### Steps to reproduce
- Open thread foo
- Type a two line message. "This is a multi line message.". Don't send it. Return to inbox.
- Go back to thread foo

**Actual result:** - Text field is only one line, shows "This is a multi line"
**Expected result:** Text field is two line, shows "This is a multi line _message_."
### Screenshots

Authoring the text properly shows multi line draft:
![image](https://cloud.githubusercontent.com/assets/217057/15302892/1c5b5340-1b6a-11e6-81cf-0840ab950851.png)

Going to inbox, then returning to thread does not expand to show second line.
![image](https://cloud.githubusercontent.com/assets/217057/15302927/46012648-1b6a-11e6-9ceb-8ed8b256fe52.png)

When opened from a notification:
![image](https://cloud.githubusercontent.com/assets/217057/15303002/909e9eb0-1b6a-11e6-9642-accc1f5a9a1b.png)
### Device info

**Device**: iPhone 5
**Signal version:** 2.2 (current appstore)

**Comment by big-r81** [comment] 2016-05-17 08:24
Hi,

this bug and bug #1179 are mostly the same.
Did some investigation at the weekend. We have to load the drafted message in the viewDidAppear function (or later after to call to the super method). Than the inputTollbar is automaticly resized correct. 

This is because the observers of the super class are registered in this method. A better experience  would be to register the observers in the viewWillAppear super method, but than we have to change the JSQMessageViewController library.

**Comment by michaelkirk-signal** [comment] 2019-01-02 20:49
The original issue was fixed long ago, but a recently regression is fixed in 2.33.0.10

**Closed by michaelkirk-signal** 2019-01-02 20:49 UTC
Labels: bug
