### ISSUE TITLE
iOS Video-Calls - no Speaker option

### ISSUE THREAD

**Issue by wuedan** [signalapp/Signal-iOS#4909] opened 2021-03-07 06:57 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Incoming Signal Video-Call answered. No way of enabling Speaker Output.

### Steps to reproduce
- Receive Signal Video Call
- Accept from the Lockscreen in the native iOS CallScreen.
- Select the "Signal" Icon to open Signal and to start the actual Video Stream

**Actual result:** 
Audio is playing from the earpiece and is hard to hear since you are holding the phone away from you to see the video

**Expected result:** 
Audio should default to speaker for video calls - at least there should be an option to change audio output.

### Device info
**Device**: iPhone 12 Pro Max

**iOS version**: 14.4

**Signal version:** 5.6.0.14

**Comment by Rajaikumar-iOSDev** [comment] 2021-03-13 07:19
I checked the behaviour in android, and the android app uses the built-in speaker by default for audio output  in video calls. But in iOS built-in earpiece is used as default audio output. 

**Is this the intended behaviour for iOS?**

I can work on this to change the default audio output to the speaker. 

Can someone assign me this issue, so that we could save dev time?

**Comment by wuedan** [comment] 2021-03-13 07:24
Thank you for looking into this, really appreciated!

On a Video-Call you typically don't hold your phone to your ear, because then your call-partner would only see your ear instead of your face, so IMHO it should be defaulted to the speaker on iOS, too.
It would also be great to show the button to switch audio interface in the video-call screen, next to the hang-up, switch camera, mute switches on the bottom of the screen.

**Comment by wuedan** [comment] 2021-03-18 16:31
I found a workaround until this is fixed.
When the iOS Call Screen comes up, pick up the call and from there turn on the speaker.
Only now, click on the Signal icon to go to your actual video-call. This is currently the only option to enable the loudspeaker. Once you are in Signal I did not find a way to go back to the iOS Call Screen to enable the speaker.

**Comment by 211217613** [comment] 2021-03-27 01:20
maybe similar to #4922

**Comment by wtangofoxtrot** [comment] 2021-03-27 19:01
Experiencing this issue all the time on iOS, is anyone going to look at this ? It’s almost been a month now.

**Comment by NickDinges** [comment] 2021-05-26 09:49
I have the same problem on Windows 10 Pro x64 - 21H1 with all patches installed using Signal 5.3.0. I use a Blue Yeti X. The sound is not loud enough on video calls, but If I use Youtube it has 5 times the volume than in the video call.

**Comment by cawauk** [comment] 2021-06-27 21:06
Same problem on IOS with video calls.

Workaround: once video call is answered, turn off video to switch to voice call, this makes the loudspeaker button appear bottom left, click loudspeaker to route call to speaker, then turn video back on to switch back to video call.

**Comment by timinterweb** [comment] 2021-08-04 07:30
Another workaround for iPhone is:
- Answer the call
- Swipe up/down and open control center
- In the music panel, there should be an source icon (round circles with triangle at bottom)
- Click this and switch to iPhone speaker

**Comment by jjohns71** [comment] 2021-08-04 12:50
> 
> 
> Another workaround for iPhone is:
> 
>     * Answer the call
> 
>     * Swipe up/down and open control center
> 
>     * In the music panel, there should be an source icon (round circles with triangle at bottom)
> 
>     * Click this and switch to iPhone speaker

This is a pretty great workaround you found but at the same time this bug is still a pretty awful user experience when 99.99% of users will NEVER find this workaround and just give up on the product. 😕

**Comment by timinterweb** [comment] 2021-08-04 15:32
> > Another workaround for iPhone is:
> > ```
> > * Answer the call
> > 
> > * Swipe up/down and open control center
> > 
> > * In the music panel, there should be an source icon (round circles with triangle at bottom)
> > 
> > * Click this and switch to iPhone speaker
> > ```
> 
> This is a pretty great workaround you found but at the same time this bug is still a pretty awful user experience when 99.99% of users will NEVER find this workaround and just give up on the product. 😕

Totally agree of course. Anecdotal, but I have two friends who have switched away from Signal because of it. I think it's quite a major 'bug'.

**Comment by peter1rhodes** [comment] 2021-08-14 09:14
This is certainly still an issue. I use Android but a friend and my parents use Signal on iOS, and they all have the same issue. When I video call them, they can't hear me because my voice is coming through the earpiece, not the loudspeaker. They have no Loudspeaker button or way to change that. It seems that muting and unmuting themselves might work, but it's really putting them off the app.

**Comment by w3sip** [comment] 2021-08-29 14:26
This is a pretty bad UI oversight. Surprised it doesn't get more attention.

**Comment by kevenwyld** [comment] 2021-09-07 21:59
Every single signal call I make (multiple times daily) with an IOS user begins with the following exchange:

Me: "Hi <recipient>"
Recipient: "I can't hear you, can you call me back on the regular phone"
Me: "Just mute and unmute"
Me: ... waits
Me: "can you hear me better now?"
Recipient: "oh, that's much better, wow"

At this point I'd say that I've experienced this on probably 20 different receiving devices but I use Android so I have not experienced it first hand other than the exchange I quoted above.  In my case basically all these users are older and or non-technical so they won't be reporting issues to signal either with the app or on github.  I'd imagine it's similar for most with parents/relatives/children/etc.  I realize that signal doesn't collect metrics to determine how extensive these issues are, but this one in particular is quite widespread and needs some attention.

**Comment by foss-** [comment] 2022-01-23 10:18
Last time I checked this was still relevant and should probably not be tagged as wontfix.

**Comment by timinterweb** [comment] 2022-01-24 07:59
Please fix this it's been waay too long. Ruining the app for me and I can't recommend it to anyone.

**Comment by fkusche** [comment] 2022-01-26 11:26
Interesting... I did not experience this behaviour for a few (2 or 3?) months now. For me, it is fixed. My phone is iOS and the other end is Android.

**Comment by foss-** [comment] 2022-01-26 13:10
@fkusche you are right. I just called a person to test this, their device in locked mode. they accepted the video call and we had an audio connection as expected via speaker from the start of the call. This was from iOS 15.2.1 to iOS 15.2.1.

**Closed** 2022-04-03 14:57 UTC
Labels: wontfix
