### ISSUE TITLE
Delay when entering (long) conversations since the update to 3.1

### ISSUE THREAD

**Issue by patjolata** [signalapp/Signal-iOS#4348] opened 2019-12-20 17:20 UTC
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

Since the update to v. 3.1.0.20 there is this delay again while entering especially longer conversations. It seems to me that the longer the conversation the longer the delay. I already mentioned it in the community:

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-ios-3-1-release/10624/42?u=patjolata

The issue seems to be very similar to the delay we had in opening conversations after the update to v. 3.0:

https://github.com/signalapp/Signal-iOS/issues/4323

Steps to reproduce
- Open Signal
- Tap on a conversation to enter it

Actual result: Conversations are opened with a delay.

Expected result: No delay, just the smooth animation.

Device info
Device: iPhone SE

iOS version: 13.3

Signal version: 3.1.0.20

Link to debug log
https://debuglogs.org/943636712c9e884cd6580aa48c4f8e5ed1b43695c153151f39a53072fdbde360.zip

**Comment by richlv** [comment] 2019-12-30 09:19
This might be solved in #4347.

**Comment by sjilo** [comment] 2019-12-30 18:35
Still experiencing this in 3.1.1.

**Comment by patjolata** [comment] 2019-12-31 00:05
Started a new debug log and will upload it tomorrow

**Comment by patjolata** [comment] 2020-01-02 09:41
Took me longer than I thought, but here it is:
https://debuglogs.org/cc95ce1adb3c25c87ab8848da6414c39143cf61b2591fdce90c86462ae7e2326.zip

**Comment by Nerd2k** [comment] 2020-01-03 14:53
> This might be solved in #4347.

Unfortunately, it isn't.

**Comment by Nerd2k** [comment] 2020-01-03 14:57
> Still experiencing this in 3.1.1.

I can confirm that.

Opening times seem to be correlated with the length of the conversations.
However, I have to say that opening conversations takes abnormally long in Signal in general, i.e. not only long conversations take long to open - the performance of opening conversations is poor in general at the moment.

**Comment by michaelkirk-signal** [comment] 2020-01-07 00:03
We've made some further improvements to conversation loading in the current beta (3.2.0). 

Would any of you be willing to try and report back if your situation is at all improved?

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Comment by sjilo** [comment] 2020-01-07 12:47
There is still a considerable delay in 3.2.0.6, there isn't any perceived improvement for me.

**Comment by michaelkirk-signal** [comment] 2020-01-07 16:59
@sjilo some questions to help us track this down:

1. Is the slowness present in all conversations equally, or are there certain conversations that seem to be much worse?

2. when you do experience slowness, is it only the first time you enter the conversation after launching Signal, or is it more or less equally as slow when you back out of a conversation and re-enter?

3. Does the slowness primarily appear when you have a lot of unread messages in the thread? Or is it more or less equally as slow when you enter a conversation with no unread messages?

**Comment by sjilo** [comment] 2020-01-07 18:55
1. They all seem to open after an equal amount of time.
2. Same in both situations.
3. Unread messages do add to the load time, but there is a baseline delay either way.

**Comment by patjolata** [comment] 2020-01-07 21:04
@michaelkirk-signal 

Concerning your question: I find it difficult to say if there are any perceivable changes. I'm really not sure, but maybe my debug log will help you.

Device: iPhone (iPhone8,4)
iOS Version: 13.3 (17C54)
Signal Version: 3.2.0.6 
Log URL: https://debuglogs.org/93afbb7eb181e1f28d88d5cbbd575405cafcb6027249054022a021442d460aa0.zip

**Comment by patjolata** [comment] 2020-01-12 14:44
The issue is still existing in the newest Signal Version.

Device: iPhone (iPhone8,4)
iOS Version: 13.3 (17C54)
Signal Version: 3.2.0.10 
Log URL: https://debuglogs.org/73c43d37c7bc1b6ca123aeceecd7ccb20402a9c83b9396e7e02dc80892edb810.zip

**Comment by rcnza** [comment] 2020-01-23 08:17
Version 2.45.2 is still available in testflight (for 9 more days).  Is it possible to go back to this version, or will that break the db structure?  I need to be able to go back to version 2 so I can continue using Signal.  The delays in v3 are causing me to switch everyone with long conversation history to iMessage.

**Comment by patjolata** [comment] 2020-01-23 10:59
@rcnza No, you won't be able to go back because with the alpha 2.46 and later the final release of 3.0 the db structure changed. It's mentioned here for example:

https://community.signalusers.org/t/alpha-testers-needed-for-a-new-version-of-signal-ios/10024

**Comment by charlesmchen-signal** [comment] 2020-01-23 13:38
@patjolata @rcnza Please try v3.3.0 which is available on TF.

**Comment by patjolata** [comment] 2020-01-24 11:11
@michaelkirk-signal @charlesmchen 

The issue still persists in v. 3.3.0. Here my debug log:
https://debuglogs.org/dac54182900f6e6db4c1439fb91db6d5807fb2d036c31945a6e7377586f0a68e.zip

**Comment by patjolata** [comment] 2020-01-27 16:15
@michaelkirk-signal @charlesmchen-signal 

I hope that I'm not overdoing it, but even with the newest version I still have the impression that there is a delay while opening a conversation. I don't in (Apple's) Messages app. Just installed v. 3.3.0.5 and it is still there.

Here is the debug log:
https://debuglogs.org/e526c486a1de7779b16fb70f2d0f4342e7eca197fa4480410591542a00e02590.zip

**Comment by Nerd2k** [comment] 2020-01-27 18:59
I can confirm the delay in the latest public version: 3.2.1
There is a lag of about typically 1.5s - 2s until conversations open. Longer convos take a bit longer than shorter ones. I don't have that kind of lag in other messenger apps either.

**Comment by rcnza** [comment] 2020-02-07 11:49
The delay is still there in 3.4.0.7, however it does feel shorter than before.  The delay is the longest when opening a very long conversation the first time after opening signal.  Thereafter switching between conversations are the quickest it has been since the release of v3.  Still, waiting for 2 - 3 seconds to open a chat is asking a lot.

**Comment by patjolata** [comment] 2020-02-09 15:38
@charlesmchen-signal @michaelkirk-signal 

Yes, the lag is still there. But I also think it is a little bit better now. Her my newest debug log:

https://debuglogs.org/468e5b8209794881c6f27916cfdddfb818dd38f761e7a6bcea1c58573b9c6952.zip

**Comment by rcnza** [comment] 2020-02-10 05:38
Testing v 3.4.3.1: Massive improvement, the delay is a Lot shorter.  It is still proportional to the conversation length.  Long conversations take less time to open than very long conversations.  The delay that is left is manageable.
Congrats guys!

**Comment by patjolata** [comment] 2020-02-10 21:56
@rcnza I actually don't 'feel' any improvement ... 

@michaelkirk-signal @charlesmchen-signal I've got the newest debug log for v. 3.4.3.1 here:

https://debuglogs.org/3c3b95fd22bd24cdd24dc681ef6bdd1ff4a82d56ddc745df05dba04b9fb3884f.zip

**Comment by Nerd2k** [comment] 2020-02-13 14:56
I can confirm that the delay is still there, no change for me whatsoever, still around 1.5s to open a conversation. It doesn't seem to be dependent on the conversation length for me though, all conversations seem to open with equal delay.

**Comment by sjilo** [comment] 2020-03-04 09:32
Nothing has changed yet, opening photos, adding attachments and typing are laggy as well.

**Comment by Nerd2k** [comment] 2020-03-05 12:03
I can confirm that the overall performance is pretty low. For example scrolling through a conversation is really stuttery for me. Telegram for example works silky smooth on the same device. What are they doing different?

**Comment by arenzana** [comment] 2020-07-06 17:23
Same situation for me. iPhone 11 Pro. 3.12.3.4. On a long conversation everything is sluggish: opening conversation, opening camera, scrolling, even typing, rotating orientation and app unlocking.

**Comment by rcnza** [comment] 2020-07-07 06:23
@arenzana I have been through this a few times and after every update wishing and hoping this gets resolved, sometimes even thinking there are improvements only to be proofed wrong.  It started to become an issue after they switched the db connection to swift native and to a new db format.

The only solution is to regularly delete long conversations completely or to use disappearing messages to prevent the conversation from getting too long.  Unfortunately you will loose all images that are important to you if you have not saved them to ios photos.

Beware, deleting a long conversation may take several attempts during which your phone will heat up like crazy.  It almost looks as if they delete every message seperately, and not with a DELETE * FROM query.  So do this during breakfast and keep some eggs close by to bake on your phone.

Since v3, this app can not be used for long conversations at all.  I have no hope that this will ever be resolved at all.  Sadly, there are only 2 permanent solutions: 1) keep conversation history short or 2) use another service

**Comment by Nerd2k** [comment] 2020-07-11 19:53
> @arenzana I have been through this a few times and after every update wishing and hoping this gets resolved, sometimes even thinking there are improvements only to be proofed wrong. It started to become an issue after they switched the db connection to swift native and to a new db format.

> Since v3, this app can not be used for long conversations at all. I have no hope that this will ever be resolved at all.

I can 100% confirm all the sluggishness! Since 1-2 weeks it even got wayyy worse. I don't remember the exact version string, but it was when they first introduced the feature that the app now remembers the scroll position in the conversations. Opening a long conversation now takes about 10s. Excuse me, but this is ridiculous. Take Telegram for example. I don't know what they do differently, but that app is running blazingly fast and everything runs buttery smooth. For privacy reasons I much prefer Signal obviously though.

Please devs (@charlesmchen-signal) can you address this issue? Or at least explain why you won't/can't address this?

**Comment by the-x-at** [comment] 2020-07-16 13:27
- Phone: iPhone 5s

- iOS: 12.4.6 (sorry!)

- Signal: 3.13.1.0 (beta testing)

Just wanted to add my 2 cents here. I am updating Signal regularly through the beta testing program. Up to this version I experienced extreme delays when opening conversations with thousands of messages and over a hundred pictures stored. Fewer than five messages are generally new. I have opened this "offending" conversation five times consecutively, without any other activities in between. The opening times are 33, 30, 16, 10, and 10 seconds, respectively.
Deleting messages is _not_ an option. Please dedicate time to solving this issue, as it affects the very core of Signal and potentially frustrates a large user base.

**Comment by benlevy0** [comment] 2020-07-24 23:14
Just to chime in: using an iPhone X, I consistently see ~1 second delays when opening very short conversations and ~2.5 second delays when opening long conversations. This is unacceptable and, given that this is clearly a widespread problem and not just a niche bug, I hope the devs are looking into it. 

I'm only weighing in now because I've been expecting it to be fixed "soon" for quite some time now.

**Comment by gual** [comment] 2020-07-31 22:48
Is there any news on this? This has become a major issue, I've to wait 10 seconds at least to talk to my family and we don't even now if this is going to be fixed.

**Comment by musha68k** [comment] 2020-08-01 15:15
> Is there any news on this? This has become a major issue, I've to wait 10 seconds at least to talk to my family and we don't even know if this is going to be fixed.

Same here. Because of this issue my friends just pinged me on a new group they created, on Threema...

FWIW performance is a feature - an important UX angle especially for people used to iOS. That said the Android version apparently doesn't seem to suffer from this. 

iPhone X, iPhone SE @ iOS 13.5.1

**Comment by musha68k** [comment] 2020-08-01 15:20
My objective-c / swift is rusty but how can we help? Does anyone have an idea what might be the culprit? If even short conversations show delays for some?

**Comment by hpincket** [comment] 2020-08-08 21:49
> I don't remember the exact version string, but it was when they first introduced the feature that the app now remembers the scroll position in the conversations.

I recall the same.

> I consistently see ~1 second delays when opening very short conversations and ~2.5 second delays when opening long conversations.

I see similar delays.


Is there any insight into why this might be happening? I haven't had time to sit down and profile it but if anyone has any hunches that would be helpful to know in advance.

**Comment by CarlosANovo** [comment] 2020-08-10 18:49
I've been experiencing delays for a long time, ~5 seconds to open a large conversation, but sometimes it takes ~10 or even 20 seconds (and it is very inconsistent, even when opening the same conversation over and over). It's the only messaging app where I find this behavior, and I imagine that many iOS users might switch to another app thanks to this issue.

I'm not an iOS developer, so I can't really help with coding, but I have a few suggestions: 
* **Feedback** - I think it would improve the user experience if at least we could see something happening (even if very slowly). Perhaps a **loading screen** (conversation "opens" to a loading animation). Anything would be better that being stuck on the conversation list for 10 seconds with no feedback, and no way to stop the loading process.
* **Making the scroll position feature optional** - There should be a way to disable this feature for the ones (like me) who never use it, especially if it is causing delay. There should be a toggle switch in the settings and a warning (like "Enabling this may cause significant delay when entering long conversations").
* **Caching** - If the delay is caused by some sort of database access, the most recent messages (or the ones around the saved scroll position) should be cached in a fast access "memory"; when entering the conversation, new/recent messages would load first (faster) and others would load as the user scrolls (even if with some delay).

I'm not sure if any of these suggestions are possible, or if they would solve the problem, but they might be worth a try.  
(these are not feature requests, since their only purpose would be to solve this long lasting issue)

**Comment by Imperiopolis-Signal** [comment] 2020-08-15 23:41
Please try out version 3.14 (in TestFlight beta right now) – we hope this has made a big dent in at least some of the worst case ~10s+ opening times.

**Comment by rcnza** [comment] 2020-08-16 10:42
For me, the time needed to switch between conversations seem to be more consistent, but still extremely slow.  Switching back to shorter conversations that has already loaded takes around 1.5 seconds.  Switching to long conversations that contains a lot of media takes around 2.5 seconds.  
Going from an active conversation to the conversation list and directly back to the same conversation takes the same amount of time as switching from another conversation, almost as if nothing is cached with the previous view deleted and recreated (not sure if this is what happens, but its how it is experienced).
I'm sure these times doesn't sound like much, but when talking to your boss and your family at the same time, all the time, this makes a difference.
The type and model of iPhone does not seem to make any difference _at all_.  This is an issue with this app, not an issue experienced with any of the other apps on the other phones.  In my group the same issue is experienced on a 6+, se and an x.
This was not an issue on v 2.x  I started experiencing it immediately after updating to 3.0x with the only temporary improvement happening when I delete all the conversations completely.

**Comment by Imperiopolis-Signal** [comment] 2020-08-16 18:22
Yep, we’re definitely aware it’s still a problem, but glad to hear that 3.14 at least gets it to a consistent level of slowness.

**Comment by gual** [comment] 2020-08-17 02:44
> Please try out version 3.14 (in TestFlight beta right now) – we hope this has made a big dent in at least some of the worst case ~10s+ opening times.

It’s great to know that this isn’t being ignored. How can I get a code for test flight? I can beta test

**Comment by the-x-at** [comment] 2020-08-18 12:58
* Phone: iPhone 5s
* iOS: 12.4.6
* Signal: 3.14.0.34 (beta testing)

Yes, I see an improvement here. With this version of Signal, it takes initially 14 seconds to open my longest conversation in Signal (see my post on Jul 16th), and every successive re-opening of that thread takes roughly 7 seconds, even if interspersed by opening other (lengthier and shorter) threads.
@Imperiopolis-Signal I am glad you are looking into this.

**Comment by Imperiopolis-Signal** [comment] 2020-08-20 21:41
Please try out the latest build on TestFlight, 3.15.0.16, we believe this has taken a big cut out of the load times. It's still not perfect, but should be much better!

**Comment by Nerd2k** [comment] 2020-08-20 22:20
I'm not a TestFlight user so I can't try it out. However, I just wanted to say a warm thank you to you devs! <3 I'm really happy that this is issue is actively tried to be solved. Keep up the good work :)

**Comment by gual** [comment] 2020-08-20 22:22
> Please try out the latest build on TestFlight, 3.15.0.16, we believe this has taken a big cut out of the load times. It's still not perfect, but should be much better!

It's so much better. It's usable again. Thanks for the team effort!

**Comment by rcnza** [comment] 2020-08-21 06:05
Yes! Thanks.  This is sooooo much better. Thanks!

**Comment by arenzana** [comment] 2020-08-21 06:16
Thank you! 3.15.0.6 is a dramatic improvement over previous versions.

**Comment by the-x-at** [comment] 2020-08-21 08:19
Fully agree. My evil thread™ (see posts above) now opens within 3 seconds the first time, and on successive trials it opens within 1.5 to at max 2 seconds. This is a vast improvement over the previous releases of Signal where at the worst I was waiting 40 seconds (even the screen locker kicked in during waiting). Good work, big thanks to the developer(s) behind this!

**Comment by denver-s** [comment] 2020-09-03 17:08
I am using 3.16.0.10 beta and I do not experience this bug anymore.

**Comment by Nerd2k** [comment] 2020-09-03 22:30
> I am using 3.16.0.10 beta and I do not experience this bug anymore.

How big is the delay in terms of seconds for you?
For me it is still around 1s of delay. While this is definitely usable it's still not super snappy instant (like it is e.g. in the Telegram app).

**Comment by benlevy0** [comment] 2020-09-07 12:22
> For me it is still around 1s of delay. While this is definitely usable it's still not super snappy instant (like it is e.g. in the Telegram app).

Same here. Useable but noticeably slower than every other messaging app I use.

**Comment by the-x-at** [comment] 2022-01-24 15:57
After a fix has been announced by @Imperiopolis 1.5 years ago, I have been using Signal continuously and did not experience issues related to this topic any more. Nobody else posted in here since then, so issue can be closed.

**Comment by Nerd2k** [comment] 2022-01-24 18:52
> After a fix has been announced by @Imperiopolis 1.5 years ago, I have been using Signal continuously and did not experience issues related to this topic any more. Nobody else posted in here since then, so issue can be closed.

I can confirm this 👍

**Closed** 2022-01-24 18:57 UTC
