### ISSUE TITLE
No way to import backup generated by Signal-Android

### ISSUE THREAD

**Issue by ag-uw** [signalapp/Signal-iOS#3221] opened 2018-04-03 03:49 UTC
- [X] I have searched open and closed issues for duplicates

(Similar to #2542 but specifically regarding the new format in v4.17.5)

----------------------------------------

Signal-Android added encrypted backup to files in v4.17.5.

There is no way to import that backup file in Signal-iOS (or generate a similar file).

Is this something that is planned?

**Comment by leonardoporpora** [comment] 2018-04-03 21:03
Yes I think it’s in roadmap

**Comment by michaelkirk-signal** [comment] 2018-04-04 14:48
dupe of #2542 please use the forum for discussion.

**Closed by michaelkirk-signal** 2018-04-04 14:48 UTC
