### ISSUE TITLE
Trying to contribute.

### ISSUE THREAD

**Issue by sindhugudivada** [signalapp/Signal-iOS#4254] opened 2019-08-29 23:05 UTC
Just wondering if we need to know Objective C to be able to contribute. Asking if knowing Swift would be okay. Also I need some help on finding some issues/features to work on. I

**Comment by michaelkirk-signal** [comment] 2019-08-29 23:22
Hi @sindhugudivada! 

We've found that Github isn't the best place for developer support or feature requests, which is why we reserve GitHub only for bug reporting. Other communication we do over at the community forums: https://community.signalusers.org

And to answer your question, you don't necessarily need to know ObjC to contribute. We have plenty of Swift code and prefer it for new features. 

Usually the most valuable contribution we get isn't a bunch of code, but rather someone who took the time to really understand an issue. For example, finding a good reproduction for a bug, narrowing in on its source, and then writing the two line fix to address the issue is ideal.

I'm going to close this issue, but hopefully see you on the [forums]https://community.signalusers.org)!

**Closed by michaelkirk-signal** 2019-08-29 23:22 UTC
