### ISSUE TITLE
Cannot change my profile photo/ introduce my name

### ISSUE THREAD

**Issue by joshcanto** [signalapp/Signal-iOS#4343] opened 2019-12-19 00:11 UTC
I have this bug, the app don’t let me change anything, I’m on iOS 13.2.3. 

Signal v3.0.6.0
iPhone 7 Plus.

Only show me this message 
![409F86D8-4DBD-42CA-9376-BF17C551171F](https://user-images.githubusercontent.com/37526901/71133843-46e06980-21b9-11ea-998b-5f89f062e3a8.jpeg)

**Comment by michaelkirk-signal** [comment] 2019-12-19 00:16
Can you please include a debug log?

**Comment by Mihahn** [comment] 2020-12-11 17:27
Can't reproduce, is this still an issue? If not, please close it.

**Closed** 2021-02-01 10:49 UTC
