### ISSUE TITLE
Image viewer layout broken in multitasking

### ISSUE THREAD

**Issue by stkhapugin** [signalapp/Signal-iOS#4456] opened 2020-05-21 09:50 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Viewing an image while Signal is not full screen shows broken layout

### Steps to reproduce
- Open signal in split view or slide-over
- Click on an image in a chat to open the viewer

**Actual result:** The image is shown in the middle of the screen and is cut off

**Expected result:** The image is laid out correctly in a smaller window, like it would be in full screen.

### Screenshots
Say hello to my cat, Photon.
![IMG_0171](https://user-images.githubusercontent.com/6065334/82546738-e46d0a00-9b58-11ea-9a73-50ff1083557d.jpeg)

### Device info

**Device**: iPad Pro 11"

**iOS version**: 13.4

**Signal version:** 3.8.3.5 (app store)

### Link to debug log
n/a

**Comment by Cerberus0** [comment] 2020-06-03 15:51
Duplicate of https://github.com/signalapp/Signal-iOS/issues/4439

**Comment by Cerberus0** [comment] 2020-06-06 15:40
@stkhapugin: Could you update to version 3.10 and confirm that this issue is now fixed?

**Closed** 2022-01-31 14:48 UTC
Labels: wontfix
