### ISSUE TITLE
Transfer Account screen not appearing on old device when transferring to new

### ISSUE THREAD

**Issue by afinno** [signalapp/Signal-iOS#4623] opened 2020-11-13 08:27 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When attempting to transfer an account from an old iPhone to new iPhone, the old iPhone fails to prompt the user with the "Transfer Account" screen as shown in the knowledge base.

### Steps to reproduce
- Ensure both old and new phones are on the same wifi network with bluetooth enabled
- On the new phone open the freshly installed Signal app
- Proceed through the prompts until you reach the QR Code to be scanned by the old phone
- Open Signal on the old phone
- Wait for "Transfer Account" prompt

**Actual result:** Signal on the old phone is unchanged and no "Transfer Account" prompt is displayed. It functions as normal and seems unaware of any transfer process being initiated.

**Expected result:** Signal on the old phone will display the "Transfer Account" prompt and the user can proceed to transfer their account from the old phone to the new phone.

### Device info

Old Phone
**Device**: iPhone 6s (64GB)
**iOS version**: 14.2
**Signal version:** 3.21.2

New Phone
**Device**: iPhone 12 Mini (256GB)
**iOS version**: 14.2
**Signal version:** 3.21.2

### Logs
~~On the new phone, when tapping 8 times on the QR Code screen, "Could not find any logs." is reported.~~
Latest attempt got this: https://debuglogs.org/36b31e5b385aa1cf7f4627b5d7b8e20ed929747eae8cc00a6e15db0216cb0c8d.zip

### Suspicions
Following the setup process on the new phone to the "Get the message" page where the local network permissions are enabled, when pressing "Enable Permissions" the user is taken directly to the phone number page without iOS actually prompting the user to allow local network permissions. It can be confirmed when checking in `Settings > Signal` and `Settings > Privacy > Local Network` that local network permissions are not enabled (or visible) for Signal on the new phone. This setting cannot initially be set by the user either.

So it can be assumed that for some reason when pressing "Enable Permissions" iOS is not sent the request for that permission by Signal. This could explain why both phones cannot talk to each other.

**Comment by afinno** [comment] 2020-11-13 08:38
Update: I reinstalled Signal in the new phone and now when pressing "Enable Permissions" it iOS prompts for access to "Contacts" and "Notifications" but not "Local Network". I don't think there is a way for me to manually enable this. I believe apps need to first make the request for access.

**Comment by afinno** [comment] 2020-11-13 11:16
Actually looking at the code, it doesn't look like Local Network permission are requested on Enable Permissions view:

https://github.com/signalapp/Signal-iOS/blob/98b3da420ef64c885d2fc4739dc66caaedda734c/Signal/src/ViewControllers/Registration/OnboardingPermissionsViewController.swift

**Comment by heilerich** [comment] 2020-11-13 12:25
I can confirm that this is a problem. The new phone isn't asking for permission and asks the user instead to grant the permission manually in the settings. But iOS doesn't allow us to grant the permission manually when the app has not yet tried to access the local network. This is completely blocking the transfer feature on iOS right now :(
<details>
<summary>This is how it looks like on a fresh install</summary>
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1824236/99071841-32684500-25b3-11eb-9fac-2a0e34403db2.png">
</details>
<details>
<summary>This is how it looks like on a phone where signal is already installed for some time</summary>
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1824236/99071885-457b1500-25b3-11eb-8a03-af1388d50ab2.png">
</details>

**Comment by mskg** [comment] 2020-11-13 12:43
I can confirm this.

**Comment by mrubioroy** [comment] 2020-11-13 12:55
Confirm

**Comment by neisha** [comment] 2020-11-13 12:59
I have hit this problem too

**Comment by mrubioroy** [comment] 2020-11-13 13:05
And now I'm apparently banned from asking an SMS code because I tried too much...

This is blocking

**Comment by mskg** [comment] 2020-11-13 13:07
> And now I'm apparently banned from asking an SMS code because I tried too much...
> 
> 
> 
> This is blocking

Be patient, that SMS auth opens up again after a couple of minutes (15-30 for me). Still the other problem remains.

**Comment by fynnay** [comment] 2020-11-13 13:10
I have this problem too.

- Updated both phones to iOS 14.2
- SIM card is still in old phone. I have been receiving confirmation SMS on that one until now
- On the old phone (that is registered) in _Settings > Signal_ there is now a "Local Network" option, which is turned on.
- In the new phone's Signal settings there is no "Local Network" option.
- Now also getting the "You've tried too often. Wait a minute to try again"
- Hope this is a simple bug fix :crossed_fingers:

**Comment by koch2** [comment] 2020-11-13 14:39
I can confirm this problem!

**Comment by mideoye** [comment] 2020-11-13 15:15
I am also experiencing this issue

**Comment by roddi** [comment] 2020-11-13 15:21
I can also confirm the problem. Both phones on 14.2

**Comment by jonaswisplinghoff** [comment] 2020-11-13 15:53
Same issue here. Bad timing for everyone getting their new iPhones today 😕

**Comment by Rupert-RR** [comment] 2020-11-13 15:56
Exactly the same problem here, presumably because there is no request for local network access on the new device.

**Comment by Imperiopolis-Signal** [comment] 2020-11-13 17:19
Hi, a fix for this is on the way, but if you’d like to transfer to your new phone sooner please download the latest beta version of Signal from TestFlight https://testflight.apple.com/join/8FHtd1Jq

The beta build is stable, and you can safely install the AppStore version over it after transferring if you do not wish to remain in the beta group.

**Comment by roddi** [comment] 2020-11-13 18:41
Hey!

Thank You very much!

I can confirm that the TestFlight version 3.22.0.3 actually solved the problem for me. 

Best Roddi

**Comment by Imperiopolis-Signal** [comment] 2020-11-13 19:16
Great news, I'm glad to hear it's working for you both. The AppStore version with the fix should also be rolling out shortly. For anyone who is waiting, the build to look for is 3.21.3

**Comment by koch2** [comment] 2020-11-13 19:20
The beta worked for me too! Thanks a lot!

**Comment by afinno** [comment] 2020-11-13 22:46
@Imperiopolis-Signal Thanks for jumping on this so quickly. You guys are gold!

I think I'll hold out for the AppStore version if it will be out soon.

**Comment by irieger** [comment] 2020-11-13 22:55
> The beta build is stable, and you can safely install the AppStore version over it after transferring if you do not wish to remain in the beta group.

If we had a way to backup this migration wouldn't feel that risky. Also it would be so much easier if Signal on iOS would just support the same file format it uses on Android to create/restore backups. I really fear the migration as I just saw that part of the migration is the automatic deletion of the old history. No way to redo the transfer for any reason. Also a backup file would work if the phone has to go for a repair or so. Signal is the number one reason I didn't get my broken (screen and battery) old phone fixed as there was no way to backup.

I love Signal and I'm happy for all your work but the whole effort of doing an additional transfer protocol instead of using the way Android supports which would also allow cross migration is just bad and the missing backup hurts so much.

**Comment by afinno** [comment] 2020-11-13 23:59
> I love Signal and I'm happy for all your work but the whole effort of doing an additional transfer protocol instead of using the way Android supports which would also allow cross migration is just bad and the missing backup hurts so much.

I tend to agree. That said, the Signal team must have some reasoning behind this architecture decision. Maybe it has already been discussed elsewhere, if so perhaps someone could provide a link.

**Comment by Imperiopolis-Signal** [comment] 2020-11-14 00:37
> I love Signal and I'm happy for all your work but the whole effort of doing an additional transfer protocol instead of using the way Android supports which would also allow cross migration is just bad and the missing backup hurts so much.

We've spoken about this at length in various forums, but a file based backup is not something typical iOS users understand. It's also significantly more complicated to implement and maintain (because anyone could try and restore a backup made from any version of Signal). It has been a nightmare to support for our Android team, even on a platform where file management is something people are familiar with. That said, we realize the transfer is also an imperfect solution, but it's at least something compared to the years of nothing while we work on the right solution. The future for moving your data between devices in Signal likely looks like a choice between direct peer-to-peer transfer or restoration from some form of secure network storage.

> I really fear the migration as I just saw that part of the migration is the automatic deletion of the old history. No way to redo the transfer for any reason.

The migration *very* carefully verifies that the transfer has been 100% successful before erasing any data on your old device. A manifest of every file to be transferred along with the checksum for that file is sent to the new device. The new device verifies that it has received every file that was intended to be transferred, that the checksum on every file exactly matches, and that all the files are properly moved into place and the database is decryptable. Only after all of these things are true does it tell your old device it's safe to erase itself. If anything is amiss, the transfer will fail and the data will remain on the old device. Also, you don't need to take my word for it. If you want to verify this verification logic yourself, take a look at https://github.com/signalapp/Signal-iOS/blob/02d6dcd1a3328b7cd16cd5036c37f82fd3bd4fcd/Signal/src/util/Device%20Transfer/DeviceTransferService%2BRestore.swift#L24

**Comment by Imperiopolis-Signal** [comment] 2020-11-14 00:38
Also, all that said, if you want to discuss the backup system further please join us on our [community forum](https://community.signalusers.org/t/ios-backup-keeping-message-history-when-switching-phones). We reserve github issues for discussion of bugs.

**Comment by PaulKierstead** [comment] 2020-11-14 00:49
I too had this problem, and the Beta solved. It wasn't clear (to me) that even though the source device had the permission, it also had to be updated to the beta, but once I read here actually carefully, and one "couldn't communicate", it transferred fine. Awesome feature! I've bumped through a couple of phone changes with signal and this is much much nicer!

**Comment by neisha** [comment] 2020-11-14 01:45
Beta worked for me, thanks for getting a fix out so quickly!

**Comment by afinno** [comment] 2020-11-14 01:55
@Imperiopolis-Signal Thanks for explaining the architecture decision. Makes sense. I figured there must be some good reasons.

Also, any idea on when the AppStore version with this fix will roll out? Are we talking hours or days?

Just want to manage my own expectations :)

**Comment by Imperiopolis-Signal** [comment] 2020-11-14 02:25
The AppStore release was just approved by Apple and is rolling out now. 3.21.3 is the release to look for. I'm going to close this issue now that it's available in the app store.

**Closed by Imperiopolis-Signal** 2020-11-14 02:25 UTC

**Comment by afinno** [comment] 2020-11-14 03:36
Installed and transferring. Thanks again for the quick response.

Related, if people are getting over heating issues, this was my solution:
![GOPR0029](https://user-images.githubusercontent.com/1435570/99138707-a32c6180-2686-11eb-967e-159b1ccd1635.jpg)

**Comment by fynnay** [comment] 2020-11-14 10:44
Wow, that was fast. Excellent work!! 👏
