### ISSUE TITLE
Unable to share image to Signal app in landscape mode

### ISSUE THREAD

**Issue by toothbrush** [signalapp/Signal-iOS#4630] opened 2020-11-23 02:14 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

I'm developing an iOS game (latest Swift and XCode, native app), it can generate PNG images and offer to the user to share them, via a `UIActivityViewController`.  This works well for apps like Mail, Messages, WhatsApp.  The issue we're having is that it appears Signal's UI doesn't work in landscape mode.

Our app is configured to only support landscape orientation (the game view is wide, portrait wouldn't make sense), and my suspicion is that this is what's causing the bug. We have tried this on iPhone, no idea if iPad is affected, we have no device to test with.

### Steps to reproduce

- Create an iOS app in Xcode ([see my minimal repro here](https://github.com/toothbrush/landscape-ios-bug)), and set it up to have only one possible *landscape* device orientation, e.g., "Landscape Left".
- Have the app spawn a `UIActivityViewController` "share sheet", with a single PNG image.
- While still in landscape mode, click "Signal" in the share sheet, to share to a Signal contact by tapping their name.
- You are sent to message composing and sending view, but it is pretty much unresponsive.

**Actual result:** At this point, you see Signal in landscape mode, offering to fill in a message, along with a preview of the image you're trying to share.  However, tapping the blue "Share" right-arrow button doesn't do anything (seemingly unresponsive) and tapping in the message box does not bring up the on-screen keyboard.  Subsequently the user is also unable to "escape" from this view, aside from double-tapping the home button and killing the app that is trying to share to Signal (EDIT: it appears i _can_ click the Cancel button successfully).

Note that this is not a problem with other apps such as Messages, Mail, etc.

**Expected result:** Signal presents the sharing dialog, and you are able to compose a message and press send, after which control should be returned to the app trying to share an image.

### Screenshots

I don't have a useful screenshot, but there's a minimal example in this repository: https://github.com/toothbrush/landscape-ios-bug.  If you launch the example app in landscape mode (as the project is configured to only support landscape-left), you encounter the issue.  The example app successfully shares the image to other apps, though.

However, the issue doesn't present when you add 

```xml
<string>UIInterfaceOrientationPortrait</string>
```

into the `UISupportedInterfaceOrientations` key of the `Info.plist` and run the app in portrait mode.  Sharing to Signal works fine, and subsequently you're dropped back into the app that initiated the share.

### Device info

**Device**: iPhone 6s Plus

**Xcode version**: 12.2 beta 4

**iOS version**: 14.1

**Signal version:** 3.21.3.0

**Comment by Imperiopolis-Signal** [comment] 2020-11-23 16:56
This is a dupe of #4435 and a bug in iOS. There's unfortunately no straightforward work around for us to fix this in Signal, other than completely redesigning our sharing experience. So far, we've been hoping Apple would resolve it (they have acknowledged the bug on their end), but it doesn't seem to be high priority for them.

**Closed by Imperiopolis-Signal** 2020-11-23 16:56 UTC

**Comment by Imperiopolis-Signal** [comment] 2020-11-23 17:00
Note, since it sounds like you're a developer, the issue in iOS is two fold;
1) the entire bottom half of the screen is not interact-able for no apparent reason
2) calling 'becomeFirstResponder' has no result and does not present a keyboard even though the view *does* become the first responder

Changing to portrait and then back to landscape is the only known resolution for the issue, but is obviously not always a possibility.

**Comment by toothbrush** [comment] 2020-11-23 22:21
Oh my, i'm sorry, i really did try to look for existing issues! Didn't look very well i guess! 😅

Thank you for clarifying and pointing me to the main bug thread, and thanks for your excellent work always!
