### ISSUE TITLE
Uable to transfer from iPhone 5s to another iPhone

### ISSUE THREAD

**Issue by ykne** [signalapp/Signal-iOS#4547] opened 2020-09-08 19:08 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Uable to transfer from iPhone 5s to any other iPhone.
Transferring from iPhone 7 to iPhone 5s more or less works as designed.

### Steps to reproduce
https://community.signalusers.org/t/signal-blog-ios-device-transfer/14889/11

### Device info

**Device**: iPhone 5s

**iOS version**: 12.4.8

**Signal version:** 3.16.0.13

### Link to debug log
Please see above community message for debug logs.

**Comment by michelle-signal** [comment] 2020-09-09 23:48
Thanks for the info! With some twiddling, I was able to reproduce locally and I have an idea for a fix.

#### Workaround
In the list of conversations, tap your avatar in the top left. Then, tap the account banner at the top. Then, set an avatar on your account. It can be literally anything. Once you do this, you should be able to get through the transfer flow without issue.

#### What's happening
During device transfer, we send some of the files saved on the old device to the new device. Some of these files are stored in a directory called ProfileAvatars. If the transfer flow can't find this directory, it fails with an error.

There are (at least) two things that'll create this directory:
- Explicitly setting a profile avatar. This is why the workaround fixes the issue
- After app launch, we submit a low priority task to be run to do some filesystem preparation. It's non-blocking and not critical, so it gets submitted at background QoS.

Background QoS hints to the OS that the operation is the lowest priority and that other tasks like drawing the UI should take precedence. On a newer devices, CPUs are usually fast enough that they can find time to run background work. But your iPhone 5s is a fairly old device. I'm not sure how long you've been registered and using your 5s before you tried the transfer flow but I'm guessing that the background work just hasn't had a chance to run yet.

#### Ideas for a fix
I think our best bet for a fix is just to avoid failing device transfer if a directory doesn't exist. We should just treat it as an empty directory. I'll look into making this change in the near future.

**Comment by ykne** [comment] 2020-09-10 00:59
Workaround did work, thank you very much.
Question: Is it possible to utilize transfer feature from Signal v3.16 on iOS v10.3.3? I happen to have a need to transfer from but that phone runs many apps no longer available beyond iOS v10.x.

**Comment by michelle-signal** [comment] 2020-09-10 01:23
Signal no longer supports iOS 10. We dropped support a while back (before I joined). I'm not quite sure what the last supported version number was but it was definitely prior to Signal 3.16.

Your best bet would be to update your iOS 10 device if possible. If that isn't (or can't) work, then you might be out of luck. Though if you provide some additional details on version numbers I can double check for you.

Could you provide the device (e.g. iPhone 5s), OS version and Signal version of both the sending and receiving device?

**Comment by ykne** [comment] 2020-09-10 01:29
I apologize, Signal actual installed version is v3.9.1.1. From transfer instructions:

Requirements

    Make sure both devices have
        iOS 12.4 or later
        Signal version 3.9.1 or later
        Wi-Fi enabled
        Bluetooth enabled

Signal version is satisfied but iOS is not. Please confirm that transfer will fail unless iOS is updated to a supported version.
Thank you.

**Comment by michelle-signal** [comment] 2020-09-10 01:47
Yes, the support docs list iOS 12.4 as a requirement. So I would not expect a device transfer from iOS 10 to succeed.

Beyond that, I'm looking through the code and there's nothing that jumps out that requires iOS 12.4. I could be missing something but there's a chance transferring from iOS 10 might just work. I don't have an iOS 10 device to test with, so I'm not going to be able to test this for you. I guess, feel free to try it. If it works great! If not, you might be out of luck.

@Imperiopolis-Signal might have more input here since she worked on a bunch of the device transfer work.

**Comment by michelle-signal** [comment] 2020-09-11 04:26
This issue should be fixed in the most recent TestFlight beta: 3.17.0.15.

**Closed by michelle-signal** 2020-09-11 04:26 UTC
