### ISSUE TITLE
able to search text inside a specific chat

### ISSUE THREAD

**Issue by mailinglists35** [signalapp/Signal-iOS#3135] opened 2018-03-15 07:23 UTC
similar to #3134, I find it difficult to find something I discussed in the past.

A search field would be helpful at the top of the window

thank you

**Comment by NinebitX** [comment] 2018-03-22 07:25
Dupe of https://github.com/signalapp/Signal-iOS/issues/646

**Comment by michaelkirk-signal** [comment] 2020-01-07 00:57
This is fixed in the latest beta. 

For instructions on how to join the beta:
https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-

**Closed by michaelkirk-signal** 2020-01-07 00:57 UTC
