### ISSUE TITLE
App crashes when trying to view a conversation where a message was deleted from notifications screen

### ISSUE THREAD

**Issue by phx** [signalapp/Signal-iOS#3297] opened 2018-04-16 15:01 UTC
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
App crashes when trying to view a conversation where a message was deleted from notifications screen.

### Steps to reproduce
- Delete an incoming message from the notification rather than the app
- Open the app and try to send a message (through app) to the contact where the message was deleted
- (or) Open the app and try to view new messages in the conversation with the contact with the deleted message

**Actual result:**
The only communication that is possible is one-way outbound communication and only through sharing TO Signal FROM other applications.  Shared content is sent which you can see in conversation overview, but upon clicking the conversation, the application crashes.  The application always crashes when trying to view the conversation in which a message was deleted from the notifications screen, even after the conversation history is deleted.  This is not related to conversation syncing between devices, because no devices are currently linked.

**Expected result:** 
The conversation should be able to be viewed with the message deleted without causing the application to crash.

### Device info
**Device**: iPhone 7
**iOS version**: 11.2 and 11.3
**Signal version:** 2.23.3.2 (and previous version)

### Link to debug log
<https://debuglogs.org/dff96ec880391c18871438302874246c7087d3862a2a03f3c25245bc19a0adb1.zip>

**Comment by Pingmin** [comment] 2018-04-17 03:48
This crash issue is almost as same as #3293 ...

**Comment by oldjamey** [comment] 2018-04-17 13:56
The result is the same, but I'm not sure if the cause is similar.  I have no trouble sharing anything from other apps.  I do not use group chats either, so that is also a difference.  This is specifically when trying to view a chat where a previous message was deleted from the notifications screen rather than within the app itself.

**Comment by Pingmin** [comment] 2018-04-18 01:49
As I mentioned, I also can share from other apps successfully too, and Signal just crash when click the group in Signal.

**Comment by oldjamey** [comment] 2018-07-07 03:08
This is resolved by uninstalling and reinstalling Signal.

**Closed** 2022-01-31 10:47 UTC
Labels: wontfix
