### ISSUE TITLE
Background message notification not working

### ISSUE THREAD

**Issue by caveman1973** [signalapp/Signal-iOS#3223] opened 2018-04-03 12:40 UTC
Let's say I'm taking to Alice and Bob (not a group chat);

When I'm talking to Bob, if Alice sends me a message, i don't receive any notification. Enabling in-app sound is annoying. 

What to expect? A pop-up notification with Alice message.

**Comment by leonardoporpora** [comment] 2018-04-03 15:29
Please complete the issue template don’t simply delete it otherwise developers are not able to understand the problem.

**Comment by caveman1973** [comment] 2018-04-08 12:05
I know it could be clearer but it's the best I could do. 

It's a UI problem, nothing complex. 

It's just annoying not receiving a notification (in the background) when you're chatting with someone else.

**Comment by vinyll** [comment] 2018-04-09 09:28
It might not be a UI issue. Notification should be active on IOS.
When receiving a private message, my iPhone beeps and a Signal popup appears on the screen, just like expected from a messaging app.

However I have a few friends who don't know anything was send until they open occasionnally the app, then the app pops up all notifications at once.
In a behavior standpoint, is similar to [this Android question](https://support.signal.org/hc/en-us/articles/115005547088-Why-do-I-only-see-new-messages-when-I-open-Signal-Android-)

**Comment by vinyll** [comment] 2018-04-09 09:36
@caveman1973 Could this be a duplicate of https://github.com/signalapp/Signal-iOS/issues/1342 ?

**Comment by caveman1973** [comment] 2018-04-26 01:45
No. The problem is that when I'm chatting with A (Signal, active window) and B sends me a message, I don't receive the pop-up notification [after I disabled in-app sounds]. 

I want to disable JUST the sound. It's annoying when you talk to two people at the same time (Signal) and the phone keeps making the text sound.

**Comment by DemiGuru** [comment] 2018-09-09 20:30
I concur - I’m experiencing the very same issue.

**Comment by jpaasen** [comment] 2019-04-12 09:30
I had a similar issue on iOS, but I realized it had to do with `Background app refresh` being globally disabled when the phone is in `Low Power mode`. When this happened I got a notification sound, but no visual notification.

**Comment by michaelkirk-signal** [comment] 2019-04-12 22:43
> What to expect? A pop-up notification with Alice message.

In-App notifications are in the latest App Store release (as of a couple releases back actually) for all users running iOS10 or newer.

**Closed by michaelkirk-signal** 2019-04-12 22:43 UTC
