### ISSUE TITLE
some PNG files do not render

### ISSUE THREAD

**Issue by dgobaud** [signalapp/Signal-iOS#3862] opened 2018-09-04 04:12 UTC
### Bug description

Some PNG files do not render. One example is iOS 11.4.1 screenshots.

### Steps to reproduce
- take iOS 11.4.1 screenshot and send it in a message

Note the photo can be sent from iOS or OSX same result on iOS when viewing in conversation it does not render. It also does not render in iOS in the message send preview.

I can see the new screenshots use color profile "Display P3" whereas old ones used "sRGB IEC61966-2.1"

working iOS 10 screenshot
![works ios 10 screenshot](https://user-images.githubusercontent.com/240811/45009563-aebb7280-afbd-11e8-8fe4-c5dcf864c734.PNG)

broken iOS 11 screenshot
![broken ios 11 screenshot](https://user-images.githubusercontent.com/240811/45009571-b844da80-afbd-11e8-8860-35ece8495517.PNG)

**Actual result:**
- image does not render in iOS Signal

**Expected result:**
- image should render

### Screenshots

![img_5193b523e8cf-1](https://user-images.githubusercontent.com/240811/45009490-41a7dd00-afbd-11e8-8523-ec5784e66b5e.jpeg)

### Device info

**Device**: iPhone 7 Plus

**iOS version**: 11.4.1

**Signal version:** 2.29.1.1

**Comment by michaelkirk-signal** [comment] 2018-09-04 16:31
Closing this as dupe of https://github.com/signalapp/Signal-iOS/issues/3860

**Closed by michaelkirk-signal** 2018-09-04 16:31 UTC
